# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BuildingExteriorWallOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BuildingExteriorWallOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBuildingExteriorWallOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BuildingExteriorWallOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x33", size_prefixed=size_prefixed)

    # BuildingExteriorWallOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BuildingExteriorWallOp
    def RegionRef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BuildingExteriorWallOp
    def Material(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # BuildingExteriorWallOp
    def RngSeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def BuildingExteriorWallOpStart(builder):
    builder.StartObject(3)

def Start(builder):
    BuildingExteriorWallOpStart(builder)

def BuildingExteriorWallOpAddRegionRef(builder, regionRef):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(regionRef), 0)

def AddRegionRef(builder, regionRef):
    BuildingExteriorWallOpAddRegionRef(builder, regionRef)

def BuildingExteriorWallOpAddMaterial(builder, material):
    builder.PrependInt8Slot(1, material, 0)

def AddMaterial(builder, material):
    BuildingExteriorWallOpAddMaterial(builder, material)

def BuildingExteriorWallOpAddRngSeed(builder, rngSeed):
    builder.PrependUint64Slot(2, rngSeed, 0)

def AddRngSeed(builder, rngSeed):
    BuildingExteriorWallOpAddRngSeed(builder, rngSeed)

def BuildingExteriorWallOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return BuildingExteriorWallOpEnd(builder)


class BuildingExteriorWallOpT(object):

    # BuildingExteriorWallOpT
    def __init__(
        self,
        regionRef = None,
        material = 0,
        rngSeed = 0,
    ):
        self.regionRef = regionRef  # type: Optional[str]
        self.material = material  # type: int
        self.rngSeed = rngSeed  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        buildingExteriorWallOp = BuildingExteriorWallOp()
        buildingExteriorWallOp.Init(buf, pos)
        return cls.InitFromObj(buildingExteriorWallOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, buildingExteriorWallOp):
        x = BuildingExteriorWallOpT()
        x._UnPack(buildingExteriorWallOp)
        return x

    # BuildingExteriorWallOpT
    def _UnPack(self, buildingExteriorWallOp):
        if buildingExteriorWallOp is None:
            return
        self.regionRef = buildingExteriorWallOp.RegionRef()
        self.material = buildingExteriorWallOp.Material()
        self.rngSeed = buildingExteriorWallOp.RngSeed()

    # BuildingExteriorWallOpT
    def Pack(self, builder):
        if self.regionRef is not None:
            regionRef = builder.CreateString(self.regionRef)
        BuildingExteriorWallOpStart(builder)
        if self.regionRef is not None:
            BuildingExteriorWallOpAddRegionRef(builder, regionRef)
        BuildingExteriorWallOpAddMaterial(builder, self.material)
        BuildingExteriorWallOpAddRngSeed(builder, self.rngSeed)
        buildingExteriorWallOp = BuildingExteriorWallOpEnd(builder)
        return buildingExteriorWallOp
