# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CartTracksVariant(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CartTracksVariant()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCartTracksVariant(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CartTracksVariantBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x33", size_prefixed=size_prefixed)

    # CartTracksVariant
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CartTracksVariant
    def Tiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from nhc.rendering.ir._fb.TileCoord import TileCoord
            obj = TileCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CartTracksVariant
    def TilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CartTracksVariant
    def TilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # CartTracksVariant
    def IsHorizontal(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # CartTracksVariant
    def IsHorizontalAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # CartTracksVariant
    def IsHorizontalLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CartTracksVariant
    def IsHorizontalIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def CartTracksVariantStart(builder):
    builder.StartObject(2)

def Start(builder):
    CartTracksVariantStart(builder)

def CartTracksVariantAddTiles(builder, tiles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tiles), 0)

def AddTiles(builder, tiles):
    CartTracksVariantAddTiles(builder, tiles)

def CartTracksVariantStartTilesVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartTilesVector(builder, numElems):
    return CartTracksVariantStartTilesVector(builder, numElems)

def CartTracksVariantAddIsHorizontal(builder, isHorizontal):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(isHorizontal), 0)

def AddIsHorizontal(builder, isHorizontal):
    CartTracksVariantAddIsHorizontal(builder, isHorizontal)

def CartTracksVariantStartIsHorizontalVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartIsHorizontalVector(builder, numElems):
    return CartTracksVariantStartIsHorizontalVector(builder, numElems)

def CartTracksVariantEnd(builder):
    return builder.EndObject()

def End(builder):
    return CartTracksVariantEnd(builder)

import nhc.rendering.ir._fb.TileCoord
try:
    from typing import List
except:
    pass

class CartTracksVariantT(object):

    # CartTracksVariantT
    def __init__(
        self,
        tiles = None,
        isHorizontal = None,
    ):
        self.tiles = tiles  # type: Optional[List[nhc.rendering.ir._fb.TileCoord.TileCoordT]]
        self.isHorizontal = isHorizontal  # type: Optional[List[bool]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cartTracksVariant = CartTracksVariant()
        cartTracksVariant.Init(buf, pos)
        return cls.InitFromObj(cartTracksVariant)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cartTracksVariant):
        x = CartTracksVariantT()
        x._UnPack(cartTracksVariant)
        return x

    # CartTracksVariantT
    def _UnPack(self, cartTracksVariant):
        if cartTracksVariant is None:
            return
        if not cartTracksVariant.TilesIsNone():
            self.tiles = []
            for i in range(cartTracksVariant.TilesLength()):
                if cartTracksVariant.Tiles(i) is None:
                    self.tiles.append(None)
                else:
                    tileCoord_ = nhc.rendering.ir._fb.TileCoord.TileCoordT.InitFromObj(cartTracksVariant.Tiles(i))
                    self.tiles.append(tileCoord_)
        if not cartTracksVariant.IsHorizontalIsNone():
            if np is None:
                self.isHorizontal = []
                for i in range(cartTracksVariant.IsHorizontalLength()):
                    self.isHorizontal.append(cartTracksVariant.IsHorizontal(i))
            else:
                self.isHorizontal = cartTracksVariant.IsHorizontalAsNumpy()

    # CartTracksVariantT
    def Pack(self, builder):
        if self.tiles is not None:
            CartTracksVariantStartTilesVector(builder, len(self.tiles))
            for i in reversed(range(len(self.tiles))):
                self.tiles[i].Pack(builder)
            tiles = builder.EndVector()
        if self.isHorizontal is not None:
            if np is not None and type(self.isHorizontal) is np.ndarray:
                isHorizontal = builder.CreateNumpyVector(self.isHorizontal)
            else:
                CartTracksVariantStartIsHorizontalVector(builder, len(self.isHorizontal))
                for i in reversed(range(len(self.isHorizontal))):
                    builder.PrependBool(self.isHorizontal[i])
                isHorizontal = builder.EndVector()
        CartTracksVariantStart(builder)
        if self.tiles is not None:
            CartTracksVariantAddTiles(builder, tiles)
        if self.isHorizontal is not None:
            CartTracksVariantAddIsHorizontal(builder, isHorizontal)
        cartTracksVariant = CartTracksVariantEnd(builder)
        return cartTracksVariant
