# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CobblestoneOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CobblestoneOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCobblestoneOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CobblestoneOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x46", size_prefixed=size_prefixed)

    # CobblestoneOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CobblestoneOp
    def Tiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from nhc.rendering.ir._fb.TileCoord import TileCoord
            obj = TileCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CobblestoneOp
    def TilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CobblestoneOp
    def TilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # CobblestoneOp
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CobblestoneOp
    def Theme(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CobblestoneOp
    def Pattern(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def CobblestoneOpStart(builder):
    builder.StartObject(4)

def Start(builder):
    CobblestoneOpStart(builder)

def CobblestoneOpAddTiles(builder, tiles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tiles), 0)

def AddTiles(builder, tiles):
    CobblestoneOpAddTiles(builder, tiles)

def CobblestoneOpStartTilesVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartTilesVector(builder, numElems):
    return CobblestoneOpStartTilesVector(builder, numElems)

def CobblestoneOpAddSeed(builder, seed):
    builder.PrependUint64Slot(1, seed, 0)

def AddSeed(builder, seed):
    CobblestoneOpAddSeed(builder, seed)

def CobblestoneOpAddTheme(builder, theme):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(theme), 0)

def AddTheme(builder, theme):
    CobblestoneOpAddTheme(builder, theme)

def CobblestoneOpAddPattern(builder, pattern):
    builder.PrependInt8Slot(3, pattern, 0)

def AddPattern(builder, pattern):
    CobblestoneOpAddPattern(builder, pattern)

def CobblestoneOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return CobblestoneOpEnd(builder)

import nhc.rendering.ir._fb.TileCoord
try:
    from typing import List
except:
    pass

class CobblestoneOpT(object):

    # CobblestoneOpT
    def __init__(
        self,
        tiles = None,
        seed = 0,
        theme = None,
        pattern = 0,
    ):
        self.tiles = tiles  # type: Optional[List[nhc.rendering.ir._fb.TileCoord.TileCoordT]]
        self.seed = seed  # type: int
        self.theme = theme  # type: Optional[str]
        self.pattern = pattern  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cobblestoneOp = CobblestoneOp()
        cobblestoneOp.Init(buf, pos)
        return cls.InitFromObj(cobblestoneOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, cobblestoneOp):
        x = CobblestoneOpT()
        x._UnPack(cobblestoneOp)
        return x

    # CobblestoneOpT
    def _UnPack(self, cobblestoneOp):
        if cobblestoneOp is None:
            return
        if not cobblestoneOp.TilesIsNone():
            self.tiles = []
            for i in range(cobblestoneOp.TilesLength()):
                if cobblestoneOp.Tiles(i) is None:
                    self.tiles.append(None)
                else:
                    tileCoord_ = nhc.rendering.ir._fb.TileCoord.TileCoordT.InitFromObj(cobblestoneOp.Tiles(i))
                    self.tiles.append(tileCoord_)
        self.seed = cobblestoneOp.Seed()
        self.theme = cobblestoneOp.Theme()
        self.pattern = cobblestoneOp.Pattern()

    # CobblestoneOpT
    def Pack(self, builder):
        if self.tiles is not None:
            CobblestoneOpStartTilesVector(builder, len(self.tiles))
            for i in reversed(range(len(self.tiles))):
                self.tiles[i].Pack(builder)
            tiles = builder.EndVector()
        if self.theme is not None:
            theme = builder.CreateString(self.theme)
        CobblestoneOpStart(builder)
        if self.tiles is not None:
            CobblestoneOpAddTiles(builder, tiles)
        CobblestoneOpAddSeed(builder, self.seed)
        if self.theme is not None:
            CobblestoneOpAddTheme(builder, theme)
        CobblestoneOpAddPattern(builder, self.pattern)
        cobblestoneOp = CobblestoneOpEnd(builder)
        return cobblestoneOp
