# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

class CobblePattern(object):
    Cobble = 0
    Brick = 1
    Flagstone = 2
    OpusReticulatum = 3
    Herringbone = 4
    Versailles4 = 5
