# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CorridorWallOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CorridorWallOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCorridorWallOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CorridorWallOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x33", size_prefixed=size_prefixed)

    # CorridorWallOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CorridorWallOp
    def Tiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from nhc.rendering.ir._fb.TileCoord import TileCoord
            obj = TileCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CorridorWallOp
    def TilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CorridorWallOp
    def TilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # CorridorWallOp
    def Style(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def CorridorWallOpStart(builder):
    builder.StartObject(2)

def Start(builder):
    CorridorWallOpStart(builder)

def CorridorWallOpAddTiles(builder, tiles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tiles), 0)

def AddTiles(builder, tiles):
    CorridorWallOpAddTiles(builder, tiles)

def CorridorWallOpStartTilesVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartTilesVector(builder, numElems):
    return CorridorWallOpStartTilesVector(builder, numElems)

def CorridorWallOpAddStyle(builder, style):
    builder.PrependUint8Slot(1, style, 0)

def AddStyle(builder, style):
    CorridorWallOpAddStyle(builder, style)

def CorridorWallOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return CorridorWallOpEnd(builder)

import nhc.rendering.ir._fb.TileCoord
try:
    from typing import List
except:
    pass

class CorridorWallOpT(object):

    # CorridorWallOpT
    def __init__(
        self,
        tiles = None,
        style = 0,
    ):
        self.tiles = tiles  # type: Optional[List[nhc.rendering.ir._fb.TileCoord.TileCoordT]]
        self.style = style  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        corridorWallOp = CorridorWallOp()
        corridorWallOp.Init(buf, pos)
        return cls.InitFromObj(corridorWallOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, corridorWallOp):
        x = CorridorWallOpT()
        x._UnPack(corridorWallOp)
        return x

    # CorridorWallOpT
    def _UnPack(self, corridorWallOp):
        if corridorWallOp is None:
            return
        if not corridorWallOp.TilesIsNone():
            self.tiles = []
            for i in range(corridorWallOp.TilesLength()):
                if corridorWallOp.Tiles(i) is None:
                    self.tiles.append(None)
                else:
                    tileCoord_ = nhc.rendering.ir._fb.TileCoord.TileCoordT.InitFromObj(corridorWallOp.Tiles(i))
                    self.tiles.append(tileCoord_)
        self.style = corridorWallOp.Style()

    # CorridorWallOpT
    def Pack(self, builder):
        if self.tiles is not None:
            CorridorWallOpStartTilesVector(builder, len(self.tiles))
            for i in reversed(range(len(self.tiles))):
                self.tiles[i].Pack(builder)
            tiles = builder.EndVector()
        CorridorWallOpStart(builder)
        if self.tiles is not None:
            CorridorWallOpAddTiles(builder, tiles)
        CorridorWallOpAddStyle(builder, self.style)
        corridorWallOp = CorridorWallOpEnd(builder)
        return corridorWallOp
