# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

class CutStyle(object):
    None_ = 0
    WoodGate = 1
    PortcullisGate = 2
    DoorWood = 3
    DoorStone = 4
    DoorIron = 5
    DoorSecret = 6
    Archway = 7
    DoorWoodOak = 8
    DoorIronBanded = 9
    DoorMagical = 10
    DoorBronze = 11
