# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EnclosureOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EnclosureOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEnclosureOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EnclosureOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x33", size_prefixed=size_prefixed)

    # EnclosureOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EnclosureOp
    def Polygon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from nhc.rendering.ir._fb.Polygon import Polygon
            obj = Polygon()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnclosureOp
    def Style(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # EnclosureOp
    def CornerStyle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # EnclosureOp
    def Gates(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from nhc.rendering.ir._fb.Gate import Gate
            obj = Gate()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnclosureOp
    def GatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EnclosureOp
    def GatesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # EnclosureOp
    def RngSeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def EnclosureOpStart(builder):
    builder.StartObject(5)

def Start(builder):
    EnclosureOpStart(builder)

def EnclosureOpAddPolygon(builder, polygon):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(polygon), 0)

def AddPolygon(builder, polygon):
    EnclosureOpAddPolygon(builder, polygon)

def EnclosureOpAddStyle(builder, style):
    builder.PrependInt8Slot(1, style, 0)

def AddStyle(builder, style):
    EnclosureOpAddStyle(builder, style)

def EnclosureOpAddCornerStyle(builder, cornerStyle):
    builder.PrependInt8Slot(2, cornerStyle, 0)

def AddCornerStyle(builder, cornerStyle):
    EnclosureOpAddCornerStyle(builder, cornerStyle)

def EnclosureOpAddGates(builder, gates):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(gates), 0)

def AddGates(builder, gates):
    EnclosureOpAddGates(builder, gates)

def EnclosureOpStartGatesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartGatesVector(builder, numElems):
    return EnclosureOpStartGatesVector(builder, numElems)

def EnclosureOpAddRngSeed(builder, rngSeed):
    builder.PrependUint64Slot(4, rngSeed, 0)

def AddRngSeed(builder, rngSeed):
    EnclosureOpAddRngSeed(builder, rngSeed)

def EnclosureOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return EnclosureOpEnd(builder)

import nhc.rendering.ir._fb.Gate
import nhc.rendering.ir._fb.Polygon
try:
    from typing import List, Optional
except:
    pass

class EnclosureOpT(object):

    # EnclosureOpT
    def __init__(
        self,
        polygon = None,
        style = 0,
        cornerStyle = 0,
        gates = None,
        rngSeed = 0,
    ):
        self.polygon = polygon  # type: Optional[nhc.rendering.ir._fb.Polygon.PolygonT]
        self.style = style  # type: int
        self.cornerStyle = cornerStyle  # type: int
        self.gates = gates  # type: Optional[List[nhc.rendering.ir._fb.Gate.GateT]]
        self.rngSeed = rngSeed  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        enclosureOp = EnclosureOp()
        enclosureOp.Init(buf, pos)
        return cls.InitFromObj(enclosureOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, enclosureOp):
        x = EnclosureOpT()
        x._UnPack(enclosureOp)
        return x

    # EnclosureOpT
    def _UnPack(self, enclosureOp):
        if enclosureOp is None:
            return
        if enclosureOp.Polygon() is not None:
            self.polygon = nhc.rendering.ir._fb.Polygon.PolygonT.InitFromObj(enclosureOp.Polygon())
        self.style = enclosureOp.Style()
        self.cornerStyle = enclosureOp.CornerStyle()
        if not enclosureOp.GatesIsNone():
            self.gates = []
            for i in range(enclosureOp.GatesLength()):
                if enclosureOp.Gates(i) is None:
                    self.gates.append(None)
                else:
                    gate_ = nhc.rendering.ir._fb.Gate.GateT.InitFromObj(enclosureOp.Gates(i))
                    self.gates.append(gate_)
        self.rngSeed = enclosureOp.RngSeed()

    # EnclosureOpT
    def Pack(self, builder):
        if self.polygon is not None:
            polygon = self.polygon.Pack(builder)
        if self.gates is not None:
            gateslist = []
            for i in range(len(self.gates)):
                gateslist.append(self.gates[i].Pack(builder))
            EnclosureOpStartGatesVector(builder, len(self.gates))
            for i in reversed(range(len(self.gates))):
                builder.PrependUOffsetTRelative(gateslist[i])
            gates = builder.EndVector()
        EnclosureOpStart(builder)
        if self.polygon is not None:
            EnclosureOpAddPolygon(builder, polygon)
        EnclosureOpAddStyle(builder, self.style)
        EnclosureOpAddCornerStyle(builder, self.cornerStyle)
        if self.gates is not None:
            EnclosureOpAddGates(builder, gates)
        EnclosureOpAddRngSeed(builder, self.rngSeed)
        enclosureOp = EnclosureOpEnd(builder)
        return enclosureOp
