# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldStoneVariant(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldStoneVariant()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldStoneVariant(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FieldStoneVariantBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x34", size_prefixed=size_prefixed)

    # FieldStoneVariant
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldStoneVariant
    def Tiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from nhc.rendering.ir._fb.TileCoord import TileCoord
            obj = TileCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FieldStoneVariant
    def TilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FieldStoneVariant
    def TilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def FieldStoneVariantStart(builder):
    builder.StartObject(1)

def Start(builder):
    FieldStoneVariantStart(builder)

def FieldStoneVariantAddTiles(builder, tiles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tiles), 0)

def AddTiles(builder, tiles):
    FieldStoneVariantAddTiles(builder, tiles)

def FieldStoneVariantStartTilesVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartTilesVector(builder, numElems):
    return FieldStoneVariantStartTilesVector(builder, numElems)

def FieldStoneVariantEnd(builder):
    return builder.EndObject()

def End(builder):
    return FieldStoneVariantEnd(builder)

import nhc.rendering.ir._fb.TileCoord
try:
    from typing import List
except:
    pass

class FieldStoneVariantT(object):

    # FieldStoneVariantT
    def __init__(
        self,
        tiles = None,
    ):
        self.tiles = tiles  # type: Optional[List[nhc.rendering.ir._fb.TileCoord.TileCoordT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fieldStoneVariant = FieldStoneVariant()
        fieldStoneVariant.Init(buf, pos)
        return cls.InitFromObj(fieldStoneVariant)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fieldStoneVariant):
        x = FieldStoneVariantT()
        x._UnPack(fieldStoneVariant)
        return x

    # FieldStoneVariantT
    def _UnPack(self, fieldStoneVariant):
        if fieldStoneVariant is None:
            return
        if not fieldStoneVariant.TilesIsNone():
            self.tiles = []
            for i in range(fieldStoneVariant.TilesLength()):
                if fieldStoneVariant.Tiles(i) is None:
                    self.tiles.append(None)
                else:
                    tileCoord_ = nhc.rendering.ir._fb.TileCoord.TileCoordT.InitFromObj(fieldStoneVariant.Tiles(i))
                    self.tiles.append(tileCoord_)

    # FieldStoneVariantT
    def Pack(self, builder):
        if self.tiles is not None:
            FieldStoneVariantStartTilesVector(builder, len(self.tiles))
            for i in reversed(range(len(self.tiles))):
                self.tiles[i].Pack(builder)
            tiles = builder.EndVector()
        FieldStoneVariantStart(builder)
        if self.tiles is not None:
            FieldStoneVariantAddTiles(builder, tiles)
        fieldStoneVariant = FieldStoneVariantEnd(builder)
        return fieldStoneVariant
