# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FixtureOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FixtureOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFixtureOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FixtureOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x35", size_prefixed=size_prefixed)

    # FixtureOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FixtureOp
    def RegionRef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FixtureOp
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FixtureOp
    def Anchors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            from nhc.rendering.ir._fb.Anchor import Anchor
            obj = Anchor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FixtureOp
    def AnchorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FixtureOp
    def AnchorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # FixtureOp
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FixtureOp
    def Scale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

def FixtureOpStart(builder):
    builder.StartObject(5)

def Start(builder):
    FixtureOpStart(builder)

def FixtureOpAddRegionRef(builder, regionRef):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(regionRef), 0)

def AddRegionRef(builder, regionRef):
    FixtureOpAddRegionRef(builder, regionRef)

def FixtureOpAddKind(builder, kind):
    builder.PrependUint8Slot(1, kind, 0)

def AddKind(builder, kind):
    FixtureOpAddKind(builder, kind)

def FixtureOpAddAnchors(builder, anchors):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(anchors), 0)

def AddAnchors(builder, anchors):
    FixtureOpAddAnchors(builder, anchors)

def FixtureOpStartAnchorsVector(builder, numElems):
    return builder.StartVector(16, numElems, 4)

def StartAnchorsVector(builder, numElems):
    return FixtureOpStartAnchorsVector(builder, numElems)

def FixtureOpAddSeed(builder, seed):
    builder.PrependUint64Slot(3, seed, 0)

def AddSeed(builder, seed):
    FixtureOpAddSeed(builder, seed)

def FixtureOpAddScale(builder, scale):
    builder.PrependFloat32Slot(4, scale, 1.0)

def AddScale(builder, scale):
    FixtureOpAddScale(builder, scale)

def FixtureOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return FixtureOpEnd(builder)

import nhc.rendering.ir._fb.Anchor
try:
    from typing import List
except:
    pass

class FixtureOpT(object):

    # FixtureOpT
    def __init__(
        self,
        regionRef = None,
        kind = 0,
        anchors = None,
        seed = 0,
        scale = 1.0,
    ):
        self.regionRef = regionRef  # type: Optional[str]
        self.kind = kind  # type: int
        self.anchors = anchors  # type: Optional[List[nhc.rendering.ir._fb.Anchor.AnchorT]]
        self.seed = seed  # type: int
        self.scale = scale  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fixtureOp = FixtureOp()
        fixtureOp.Init(buf, pos)
        return cls.InitFromObj(fixtureOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fixtureOp):
        x = FixtureOpT()
        x._UnPack(fixtureOp)
        return x

    # FixtureOpT
    def _UnPack(self, fixtureOp):
        if fixtureOp is None:
            return
        self.regionRef = fixtureOp.RegionRef()
        self.kind = fixtureOp.Kind()
        if not fixtureOp.AnchorsIsNone():
            self.anchors = []
            for i in range(fixtureOp.AnchorsLength()):
                if fixtureOp.Anchors(i) is None:
                    self.anchors.append(None)
                else:
                    anchor_ = nhc.rendering.ir._fb.Anchor.AnchorT.InitFromObj(fixtureOp.Anchors(i))
                    self.anchors.append(anchor_)
        self.seed = fixtureOp.Seed()
        self.scale = fixtureOp.Scale()

    # FixtureOpT
    def Pack(self, builder):
        if self.regionRef is not None:
            regionRef = builder.CreateString(self.regionRef)
        if self.anchors is not None:
            FixtureOpStartAnchorsVector(builder, len(self.anchors))
            for i in reversed(range(len(self.anchors))):
                self.anchors[i].Pack(builder)
            anchors = builder.EndVector()
        FixtureOpStart(builder)
        if self.regionRef is not None:
            FixtureOpAddRegionRef(builder, regionRef)
        FixtureOpAddKind(builder, self.kind)
        if self.anchors is not None:
            FixtureOpAddAnchors(builder, anchors)
        FixtureOpAddSeed(builder, self.seed)
        FixtureOpAddScale(builder, self.scale)
        fixtureOp = FixtureOpEnd(builder)
        return fixtureOp
