# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FloorGridOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FloorGridOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFloorGridOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FloorGridOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x33", size_prefixed=size_prefixed)

    # FloorGridOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FloorGridOp
    def ClipRegion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FloorGridOp
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FloorGridOp
    def Theme(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FloorGridOp
    def Scale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # FloorGridOp
    def Tiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            from nhc.rendering.ir._fb.FloorGridTile import FloorGridTile
            obj = FloorGridTile()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FloorGridOp
    def TilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FloorGridOp
    def TilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # FloorGridOp
    def RegionRef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def FloorGridOpStart(builder):
    builder.StartObject(6)

def Start(builder):
    FloorGridOpStart(builder)

def FloorGridOpAddClipRegion(builder, clipRegion):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clipRegion), 0)

def AddClipRegion(builder, clipRegion):
    FloorGridOpAddClipRegion(builder, clipRegion)

def FloorGridOpAddSeed(builder, seed):
    builder.PrependUint64Slot(1, seed, 0)

def AddSeed(builder, seed):
    FloorGridOpAddSeed(builder, seed)

def FloorGridOpAddTheme(builder, theme):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(theme), 0)

def AddTheme(builder, theme):
    FloorGridOpAddTheme(builder, theme)

def FloorGridOpAddScale(builder, scale):
    builder.PrependFloat32Slot(3, scale, 1.0)

def AddScale(builder, scale):
    FloorGridOpAddScale(builder, scale)

def FloorGridOpAddTiles(builder, tiles):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(tiles), 0)

def AddTiles(builder, tiles):
    FloorGridOpAddTiles(builder, tiles)

def FloorGridOpStartTilesVector(builder, numElems):
    return builder.StartVector(12, numElems, 4)

def StartTilesVector(builder, numElems):
    return FloorGridOpStartTilesVector(builder, numElems)

def FloorGridOpAddRegionRef(builder, regionRef):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(regionRef), 0)

def AddRegionRef(builder, regionRef):
    FloorGridOpAddRegionRef(builder, regionRef)

def FloorGridOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return FloorGridOpEnd(builder)

import nhc.rendering.ir._fb.FloorGridTile
try:
    from typing import List
except:
    pass

class FloorGridOpT(object):

    # FloorGridOpT
    def __init__(
        self,
        clipRegion = None,
        seed = 0,
        theme = None,
        scale = 1.0,
        tiles = None,
        regionRef = None,
    ):
        self.clipRegion = clipRegion  # type: Optional[str]
        self.seed = seed  # type: int
        self.theme = theme  # type: Optional[str]
        self.scale = scale  # type: float
        self.tiles = tiles  # type: Optional[List[nhc.rendering.ir._fb.FloorGridTile.FloorGridTileT]]
        self.regionRef = regionRef  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        floorGridOp = FloorGridOp()
        floorGridOp.Init(buf, pos)
        return cls.InitFromObj(floorGridOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, floorGridOp):
        x = FloorGridOpT()
        x._UnPack(floorGridOp)
        return x

    # FloorGridOpT
    def _UnPack(self, floorGridOp):
        if floorGridOp is None:
            return
        self.clipRegion = floorGridOp.ClipRegion()
        self.seed = floorGridOp.Seed()
        self.theme = floorGridOp.Theme()
        self.scale = floorGridOp.Scale()
        if not floorGridOp.TilesIsNone():
            self.tiles = []
            for i in range(floorGridOp.TilesLength()):
                if floorGridOp.Tiles(i) is None:
                    self.tiles.append(None)
                else:
                    floorGridTile_ = nhc.rendering.ir._fb.FloorGridTile.FloorGridTileT.InitFromObj(floorGridOp.Tiles(i))
                    self.tiles.append(floorGridTile_)
        self.regionRef = floorGridOp.RegionRef()

    # FloorGridOpT
    def Pack(self, builder):
        if self.clipRegion is not None:
            clipRegion = builder.CreateString(self.clipRegion)
        if self.theme is not None:
            theme = builder.CreateString(self.theme)
        if self.tiles is not None:
            FloorGridOpStartTilesVector(builder, len(self.tiles))
            for i in reversed(range(len(self.tiles))):
                self.tiles[i].Pack(builder)
            tiles = builder.EndVector()
        if self.regionRef is not None:
            regionRef = builder.CreateString(self.regionRef)
        FloorGridOpStart(builder)
        if self.clipRegion is not None:
            FloorGridOpAddClipRegion(builder, clipRegion)
        FloorGridOpAddSeed(builder, self.seed)
        if self.theme is not None:
            FloorGridOpAddTheme(builder, theme)
        FloorGridOpAddScale(builder, self.scale)
        if self.tiles is not None:
            FloorGridOpAddTiles(builder, tiles)
        if self.regionRef is not None:
            FloorGridOpAddRegionRef(builder, regionRef)
        floorGridOp = FloorGridOpEnd(builder)
        return floorGridOp
