# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FloorIR(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FloorIR()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFloorIR(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FloorIRBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x34", size_prefixed=size_prefixed)

    # FloorIR
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FloorIR
    def Major(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FloorIR
    def Minor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FloorIR
    def WidthTiles(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FloorIR
    def HeightTiles(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FloorIR
    def Cell(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 32

    # FloorIR
    def Padding(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 32

    # FloorIR
    def FloorKind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # FloorIR
    def Theme(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FloorIR
    def BaseSeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FloorIR
    def Flags(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from nhc.rendering.ir._fb.FeatureFlags import FeatureFlags
            obj = FeatureFlags()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FloorIR
    def Regions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from nhc.rendering.ir._fb.Region import Region
            obj = Region()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FloorIR
    def RegionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FloorIR
    def RegionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # FloorIR
    def Ops(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from nhc.rendering.ir._fb.OpEntry import OpEntry
            obj = OpEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FloorIR
    def OpsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FloorIR
    def OpsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

    # FloorIR
    def V5Regions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from nhc.rendering.ir._fb.V5Region import V5Region
            obj = V5Region()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FloorIR
    def V5RegionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FloorIR
    def V5RegionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

    # FloorIR
    def V5Ops(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from nhc.rendering.ir._fb.V5OpEntry import V5OpEntry
            obj = V5OpEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FloorIR
    def V5OpsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FloorIR
    def V5OpsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0

def FloorIRStart(builder):
    builder.StartObject(14)

def Start(builder):
    FloorIRStart(builder)

def FloorIRAddMajor(builder, major):
    builder.PrependUint32Slot(0, major, 0)

def AddMajor(builder, major):
    FloorIRAddMajor(builder, major)

def FloorIRAddMinor(builder, minor):
    builder.PrependUint32Slot(1, minor, 0)

def AddMinor(builder, minor):
    FloorIRAddMinor(builder, minor)

def FloorIRAddWidthTiles(builder, widthTiles):
    builder.PrependUint32Slot(2, widthTiles, 0)

def AddWidthTiles(builder, widthTiles):
    FloorIRAddWidthTiles(builder, widthTiles)

def FloorIRAddHeightTiles(builder, heightTiles):
    builder.PrependUint32Slot(3, heightTiles, 0)

def AddHeightTiles(builder, heightTiles):
    FloorIRAddHeightTiles(builder, heightTiles)

def FloorIRAddCell(builder, cell):
    builder.PrependUint32Slot(4, cell, 32)

def AddCell(builder, cell):
    FloorIRAddCell(builder, cell)

def FloorIRAddPadding(builder, padding):
    builder.PrependUint32Slot(5, padding, 32)

def AddPadding(builder, padding):
    FloorIRAddPadding(builder, padding)

def FloorIRAddFloorKind(builder, floorKind):
    builder.PrependInt8Slot(6, floorKind, 0)

def AddFloorKind(builder, floorKind):
    FloorIRAddFloorKind(builder, floorKind)

def FloorIRAddTheme(builder, theme):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(theme), 0)

def AddTheme(builder, theme):
    FloorIRAddTheme(builder, theme)

def FloorIRAddBaseSeed(builder, baseSeed):
    builder.PrependUint64Slot(8, baseSeed, 0)

def AddBaseSeed(builder, baseSeed):
    FloorIRAddBaseSeed(builder, baseSeed)

def FloorIRAddFlags(builder, flags):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(flags), 0)

def AddFlags(builder, flags):
    FloorIRAddFlags(builder, flags)

def FloorIRAddRegions(builder, regions):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(regions), 0)

def AddRegions(builder, regions):
    FloorIRAddRegions(builder, regions)

def FloorIRStartRegionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRegionsVector(builder, numElems):
    return FloorIRStartRegionsVector(builder, numElems)

def FloorIRAddOps(builder, ops):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(ops), 0)

def AddOps(builder, ops):
    FloorIRAddOps(builder, ops)

def FloorIRStartOpsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOpsVector(builder, numElems):
    return FloorIRStartOpsVector(builder, numElems)

def FloorIRAddV5Regions(builder, v5Regions):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(v5Regions), 0)

def AddV5Regions(builder, v5Regions):
    FloorIRAddV5Regions(builder, v5Regions)

def FloorIRStartV5RegionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartV5RegionsVector(builder, numElems):
    return FloorIRStartV5RegionsVector(builder, numElems)

def FloorIRAddV5Ops(builder, v5Ops):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(v5Ops), 0)

def AddV5Ops(builder, v5Ops):
    FloorIRAddV5Ops(builder, v5Ops)

def FloorIRStartV5OpsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartV5OpsVector(builder, numElems):
    return FloorIRStartV5OpsVector(builder, numElems)

def FloorIREnd(builder):
    return builder.EndObject()

def End(builder):
    return FloorIREnd(builder)

import nhc.rendering.ir._fb.FeatureFlags
import nhc.rendering.ir._fb.OpEntry
import nhc.rendering.ir._fb.Region
import nhc.rendering.ir._fb.V5OpEntry
import nhc.rendering.ir._fb.V5Region
try:
    from typing import List, Optional
except:
    pass

class FloorIRT(object):

    # FloorIRT
    def __init__(
        self,
        major = 0,
        minor = 0,
        widthTiles = 0,
        heightTiles = 0,
        cell = 32,
        padding = 32,
        floorKind = 0,
        theme = None,
        baseSeed = 0,
        flags = None,
        regions = None,
        ops = None,
        v5Regions = None,
        v5Ops = None,
    ):
        self.major = major  # type: int
        self.minor = minor  # type: int
        self.widthTiles = widthTiles  # type: int
        self.heightTiles = heightTiles  # type: int
        self.cell = cell  # type: int
        self.padding = padding  # type: int
        self.floorKind = floorKind  # type: int
        self.theme = theme  # type: Optional[str]
        self.baseSeed = baseSeed  # type: int
        self.flags = flags  # type: Optional[nhc.rendering.ir._fb.FeatureFlags.FeatureFlagsT]
        self.regions = regions  # type: Optional[List[nhc.rendering.ir._fb.Region.RegionT]]
        self.ops = ops  # type: Optional[List[nhc.rendering.ir._fb.OpEntry.OpEntryT]]
        self.v5Regions = v5Regions  # type: Optional[List[nhc.rendering.ir._fb.V5Region.V5RegionT]]
        self.v5Ops = v5Ops  # type: Optional[List[nhc.rendering.ir._fb.V5OpEntry.V5OpEntryT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        floorIr = FloorIR()
        floorIr.Init(buf, pos)
        return cls.InitFromObj(floorIr)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, floorIr):
        x = FloorIRT()
        x._UnPack(floorIr)
        return x

    # FloorIRT
    def _UnPack(self, floorIr):
        if floorIr is None:
            return
        self.major = floorIr.Major()
        self.minor = floorIr.Minor()
        self.widthTiles = floorIr.WidthTiles()
        self.heightTiles = floorIr.HeightTiles()
        self.cell = floorIr.Cell()
        self.padding = floorIr.Padding()
        self.floorKind = floorIr.FloorKind()
        self.theme = floorIr.Theme()
        self.baseSeed = floorIr.BaseSeed()
        if floorIr.Flags() is not None:
            self.flags = nhc.rendering.ir._fb.FeatureFlags.FeatureFlagsT.InitFromObj(floorIr.Flags())
        if not floorIr.RegionsIsNone():
            self.regions = []
            for i in range(floorIr.RegionsLength()):
                if floorIr.Regions(i) is None:
                    self.regions.append(None)
                else:
                    region_ = nhc.rendering.ir._fb.Region.RegionT.InitFromObj(floorIr.Regions(i))
                    self.regions.append(region_)
        if not floorIr.OpsIsNone():
            self.ops = []
            for i in range(floorIr.OpsLength()):
                if floorIr.Ops(i) is None:
                    self.ops.append(None)
                else:
                    opEntry_ = nhc.rendering.ir._fb.OpEntry.OpEntryT.InitFromObj(floorIr.Ops(i))
                    self.ops.append(opEntry_)
        if not floorIr.V5RegionsIsNone():
            self.v5Regions = []
            for i in range(floorIr.V5RegionsLength()):
                if floorIr.V5Regions(i) is None:
                    self.v5Regions.append(None)
                else:
                    v5Region_ = nhc.rendering.ir._fb.V5Region.V5RegionT.InitFromObj(floorIr.V5Regions(i))
                    self.v5Regions.append(v5Region_)
        if not floorIr.V5OpsIsNone():
            self.v5Ops = []
            for i in range(floorIr.V5OpsLength()):
                if floorIr.V5Ops(i) is None:
                    self.v5Ops.append(None)
                else:
                    v5OpEntry_ = nhc.rendering.ir._fb.V5OpEntry.V5OpEntryT.InitFromObj(floorIr.V5Ops(i))
                    self.v5Ops.append(v5OpEntry_)

    # FloorIRT
    def Pack(self, builder):
        if self.theme is not None:
            theme = builder.CreateString(self.theme)
        if self.flags is not None:
            flags = self.flags.Pack(builder)
        if self.regions is not None:
            regionslist = []
            for i in range(len(self.regions)):
                regionslist.append(self.regions[i].Pack(builder))
            FloorIRStartRegionsVector(builder, len(self.regions))
            for i in reversed(range(len(self.regions))):
                builder.PrependUOffsetTRelative(regionslist[i])
            regions = builder.EndVector()
        if self.ops is not None:
            opslist = []
            for i in range(len(self.ops)):
                opslist.append(self.ops[i].Pack(builder))
            FloorIRStartOpsVector(builder, len(self.ops))
            for i in reversed(range(len(self.ops))):
                builder.PrependUOffsetTRelative(opslist[i])
            ops = builder.EndVector()
        if self.v5Regions is not None:
            v5Regionslist = []
            for i in range(len(self.v5Regions)):
                v5Regionslist.append(self.v5Regions[i].Pack(builder))
            FloorIRStartV5RegionsVector(builder, len(self.v5Regions))
            for i in reversed(range(len(self.v5Regions))):
                builder.PrependUOffsetTRelative(v5Regionslist[i])
            v5Regions = builder.EndVector()
        if self.v5Ops is not None:
            v5Opslist = []
            for i in range(len(self.v5Ops)):
                v5Opslist.append(self.v5Ops[i].Pack(builder))
            FloorIRStartV5OpsVector(builder, len(self.v5Ops))
            for i in reversed(range(len(self.v5Ops))):
                builder.PrependUOffsetTRelative(v5Opslist[i])
            v5Ops = builder.EndVector()
        FloorIRStart(builder)
        FloorIRAddMajor(builder, self.major)
        FloorIRAddMinor(builder, self.minor)
        FloorIRAddWidthTiles(builder, self.widthTiles)
        FloorIRAddHeightTiles(builder, self.heightTiles)
        FloorIRAddCell(builder, self.cell)
        FloorIRAddPadding(builder, self.padding)
        FloorIRAddFloorKind(builder, self.floorKind)
        if self.theme is not None:
            FloorIRAddTheme(builder, theme)
        FloorIRAddBaseSeed(builder, self.baseSeed)
        if self.flags is not None:
            FloorIRAddFlags(builder, flags)
        if self.regions is not None:
            FloorIRAddRegions(builder, regions)
        if self.ops is not None:
            FloorIRAddOps(builder, ops)
        if self.v5Regions is not None:
            FloorIRAddV5Regions(builder, v5Regions)
        if self.v5Ops is not None:
            FloorIRAddV5Ops(builder, v5Ops)
        floorIr = FloorIREnd(builder)
        return floorIr
