# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FloorDetailOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FloorDetailOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFloorDetailOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FloorDetailOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x46", size_prefixed=size_prefixed)

    # FloorDetailOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FloorDetailOp
    def Tiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from nhc.rendering.ir._fb.TileCoord import TileCoord
            obj = TileCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FloorDetailOp
    def TilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FloorDetailOp
    def TilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # FloorDetailOp
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FloorDetailOp
    def Theme(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FloorDetailOp
    def RoomGroups(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # FloorDetailOp
    def RoomGroupsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FloorDetailOp
    def RoomGroupsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # FloorDetailOp
    def CorridorGroups(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # FloorDetailOp
    def CorridorGroupsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FloorDetailOp
    def CorridorGroupsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # FloorDetailOp
    def ClipRegion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FloorDetailOp
    def DecoratorGroups(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # FloorDetailOp
    def DecoratorGroupsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FloorDetailOp
    def DecoratorGroupsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # FloorDetailOp
    def WoodFloorGroups(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # FloorDetailOp
    def WoodFloorGroupsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FloorDetailOp
    def WoodFloorGroupsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

def FloorDetailOpStart(builder):
    builder.StartObject(8)

def Start(builder):
    FloorDetailOpStart(builder)

def FloorDetailOpAddTiles(builder, tiles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tiles), 0)

def AddTiles(builder, tiles):
    FloorDetailOpAddTiles(builder, tiles)

def FloorDetailOpStartTilesVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartTilesVector(builder, numElems):
    return FloorDetailOpStartTilesVector(builder, numElems)

def FloorDetailOpAddSeed(builder, seed):
    builder.PrependUint64Slot(1, seed, 0)

def AddSeed(builder, seed):
    FloorDetailOpAddSeed(builder, seed)

def FloorDetailOpAddTheme(builder, theme):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(theme), 0)

def AddTheme(builder, theme):
    FloorDetailOpAddTheme(builder, theme)

def FloorDetailOpAddRoomGroups(builder, roomGroups):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(roomGroups), 0)

def AddRoomGroups(builder, roomGroups):
    FloorDetailOpAddRoomGroups(builder, roomGroups)

def FloorDetailOpStartRoomGroupsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRoomGroupsVector(builder, numElems):
    return FloorDetailOpStartRoomGroupsVector(builder, numElems)

def FloorDetailOpAddCorridorGroups(builder, corridorGroups):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(corridorGroups), 0)

def AddCorridorGroups(builder, corridorGroups):
    FloorDetailOpAddCorridorGroups(builder, corridorGroups)

def FloorDetailOpStartCorridorGroupsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCorridorGroupsVector(builder, numElems):
    return FloorDetailOpStartCorridorGroupsVector(builder, numElems)

def FloorDetailOpAddClipRegion(builder, clipRegion):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(clipRegion), 0)

def AddClipRegion(builder, clipRegion):
    FloorDetailOpAddClipRegion(builder, clipRegion)

def FloorDetailOpAddDecoratorGroups(builder, decoratorGroups):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(decoratorGroups), 0)

def AddDecoratorGroups(builder, decoratorGroups):
    FloorDetailOpAddDecoratorGroups(builder, decoratorGroups)

def FloorDetailOpStartDecoratorGroupsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDecoratorGroupsVector(builder, numElems):
    return FloorDetailOpStartDecoratorGroupsVector(builder, numElems)

def FloorDetailOpAddWoodFloorGroups(builder, woodFloorGroups):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(woodFloorGroups), 0)

def AddWoodFloorGroups(builder, woodFloorGroups):
    FloorDetailOpAddWoodFloorGroups(builder, woodFloorGroups)

def FloorDetailOpStartWoodFloorGroupsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartWoodFloorGroupsVector(builder, numElems):
    return FloorDetailOpStartWoodFloorGroupsVector(builder, numElems)

def FloorDetailOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return FloorDetailOpEnd(builder)

import nhc.rendering.ir._fb.TileCoord
try:
    from typing import List
except:
    pass

class FloorDetailOpT(object):

    # FloorDetailOpT
    def __init__(
        self,
        tiles = None,
        seed = 0,
        theme = None,
        roomGroups = None,
        corridorGroups = None,
        clipRegion = None,
        decoratorGroups = None,
        woodFloorGroups = None,
    ):
        self.tiles = tiles  # type: Optional[List[nhc.rendering.ir._fb.TileCoord.TileCoordT]]
        self.seed = seed  # type: int
        self.theme = theme  # type: Optional[str]
        self.roomGroups = roomGroups  # type: Optional[List[Optional[str]]]
        self.corridorGroups = corridorGroups  # type: Optional[List[Optional[str]]]
        self.clipRegion = clipRegion  # type: Optional[str]
        self.decoratorGroups = decoratorGroups  # type: Optional[List[Optional[str]]]
        self.woodFloorGroups = woodFloorGroups  # type: Optional[List[Optional[str]]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        floorDetailOp = FloorDetailOp()
        floorDetailOp.Init(buf, pos)
        return cls.InitFromObj(floorDetailOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, floorDetailOp):
        x = FloorDetailOpT()
        x._UnPack(floorDetailOp)
        return x

    # FloorDetailOpT
    def _UnPack(self, floorDetailOp):
        if floorDetailOp is None:
            return
        if not floorDetailOp.TilesIsNone():
            self.tiles = []
            for i in range(floorDetailOp.TilesLength()):
                if floorDetailOp.Tiles(i) is None:
                    self.tiles.append(None)
                else:
                    tileCoord_ = nhc.rendering.ir._fb.TileCoord.TileCoordT.InitFromObj(floorDetailOp.Tiles(i))
                    self.tiles.append(tileCoord_)
        self.seed = floorDetailOp.Seed()
        self.theme = floorDetailOp.Theme()
        if not floorDetailOp.RoomGroupsIsNone():
            self.roomGroups = []
            for i in range(floorDetailOp.RoomGroupsLength()):
                self.roomGroups.append(floorDetailOp.RoomGroups(i))
        if not floorDetailOp.CorridorGroupsIsNone():
            self.corridorGroups = []
            for i in range(floorDetailOp.CorridorGroupsLength()):
                self.corridorGroups.append(floorDetailOp.CorridorGroups(i))
        self.clipRegion = floorDetailOp.ClipRegion()
        if not floorDetailOp.DecoratorGroupsIsNone():
            self.decoratorGroups = []
            for i in range(floorDetailOp.DecoratorGroupsLength()):
                self.decoratorGroups.append(floorDetailOp.DecoratorGroups(i))
        if not floorDetailOp.WoodFloorGroupsIsNone():
            self.woodFloorGroups = []
            for i in range(floorDetailOp.WoodFloorGroupsLength()):
                self.woodFloorGroups.append(floorDetailOp.WoodFloorGroups(i))

    # FloorDetailOpT
    def Pack(self, builder):
        if self.tiles is not None:
            FloorDetailOpStartTilesVector(builder, len(self.tiles))
            for i in reversed(range(len(self.tiles))):
                self.tiles[i].Pack(builder)
            tiles = builder.EndVector()
        if self.theme is not None:
            theme = builder.CreateString(self.theme)
        if self.roomGroups is not None:
            roomGroupslist = []
            for i in range(len(self.roomGroups)):
                roomGroupslist.append(builder.CreateString(self.roomGroups[i]))
            FloorDetailOpStartRoomGroupsVector(builder, len(self.roomGroups))
            for i in reversed(range(len(self.roomGroups))):
                builder.PrependUOffsetTRelative(roomGroupslist[i])
            roomGroups = builder.EndVector()
        if self.corridorGroups is not None:
            corridorGroupslist = []
            for i in range(len(self.corridorGroups)):
                corridorGroupslist.append(builder.CreateString(self.corridorGroups[i]))
            FloorDetailOpStartCorridorGroupsVector(builder, len(self.corridorGroups))
            for i in reversed(range(len(self.corridorGroups))):
                builder.PrependUOffsetTRelative(corridorGroupslist[i])
            corridorGroups = builder.EndVector()
        if self.clipRegion is not None:
            clipRegion = builder.CreateString(self.clipRegion)
        if self.decoratorGroups is not None:
            decoratorGroupslist = []
            for i in range(len(self.decoratorGroups)):
                decoratorGroupslist.append(builder.CreateString(self.decoratorGroups[i]))
            FloorDetailOpStartDecoratorGroupsVector(builder, len(self.decoratorGroups))
            for i in reversed(range(len(self.decoratorGroups))):
                builder.PrependUOffsetTRelative(decoratorGroupslist[i])
            decoratorGroups = builder.EndVector()
        if self.woodFloorGroups is not None:
            woodFloorGroupslist = []
            for i in range(len(self.woodFloorGroups)):
                woodFloorGroupslist.append(builder.CreateString(self.woodFloorGroups[i]))
            FloorDetailOpStartWoodFloorGroupsVector(builder, len(self.woodFloorGroups))
            for i in reversed(range(len(self.woodFloorGroups))):
                builder.PrependUOffsetTRelative(woodFloorGroupslist[i])
            woodFloorGroups = builder.EndVector()
        FloorDetailOpStart(builder)
        if self.tiles is not None:
            FloorDetailOpAddTiles(builder, tiles)
        FloorDetailOpAddSeed(builder, self.seed)
        if self.theme is not None:
            FloorDetailOpAddTheme(builder, theme)
        if self.roomGroups is not None:
            FloorDetailOpAddRoomGroups(builder, roomGroups)
        if self.corridorGroups is not None:
            FloorDetailOpAddCorridorGroups(builder, corridorGroups)
        if self.clipRegion is not None:
            FloorDetailOpAddClipRegion(builder, clipRegion)
        if self.decoratorGroups is not None:
            FloorDetailOpAddDecoratorGroups(builder, decoratorGroups)
        if self.woodFloorGroups is not None:
            FloorDetailOpAddWoodFloorGroups(builder, woodFloorGroups)
        floorDetailOp = FloorDetailOpEnd(builder)
        return floorDetailOp
