# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FountainFeatureOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FountainFeatureOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFountainFeatureOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FountainFeatureOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x33", size_prefixed=size_prefixed)

    # FountainFeatureOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FountainFeatureOp
    def Tiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from nhc.rendering.ir._fb.TileCoord import TileCoord
            obj = TileCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FountainFeatureOp
    def TilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FountainFeatureOp
    def TilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # FountainFeatureOp
    def Shape(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # FountainFeatureOp
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FountainFeatureOp
    def Theme(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def FountainFeatureOpStart(builder):
    builder.StartObject(4)

def Start(builder):
    FountainFeatureOpStart(builder)

def FountainFeatureOpAddTiles(builder, tiles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tiles), 0)

def AddTiles(builder, tiles):
    FountainFeatureOpAddTiles(builder, tiles)

def FountainFeatureOpStartTilesVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartTilesVector(builder, numElems):
    return FountainFeatureOpStartTilesVector(builder, numElems)

def FountainFeatureOpAddShape(builder, shape):
    builder.PrependInt8Slot(1, shape, 0)

def AddShape(builder, shape):
    FountainFeatureOpAddShape(builder, shape)

def FountainFeatureOpAddSeed(builder, seed):
    builder.PrependUint64Slot(2, seed, 0)

def AddSeed(builder, seed):
    FountainFeatureOpAddSeed(builder, seed)

def FountainFeatureOpAddTheme(builder, theme):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(theme), 0)

def AddTheme(builder, theme):
    FountainFeatureOpAddTheme(builder, theme)

def FountainFeatureOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return FountainFeatureOpEnd(builder)

import nhc.rendering.ir._fb.TileCoord
try:
    from typing import List
except:
    pass

class FountainFeatureOpT(object):

    # FountainFeatureOpT
    def __init__(
        self,
        tiles = None,
        shape = 0,
        seed = 0,
        theme = None,
    ):
        self.tiles = tiles  # type: Optional[List[nhc.rendering.ir._fb.TileCoord.TileCoordT]]
        self.shape = shape  # type: int
        self.seed = seed  # type: int
        self.theme = theme  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fountainFeatureOp = FountainFeatureOp()
        fountainFeatureOp.Init(buf, pos)
        return cls.InitFromObj(fountainFeatureOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fountainFeatureOp):
        x = FountainFeatureOpT()
        x._UnPack(fountainFeatureOp)
        return x

    # FountainFeatureOpT
    def _UnPack(self, fountainFeatureOp):
        if fountainFeatureOp is None:
            return
        if not fountainFeatureOp.TilesIsNone():
            self.tiles = []
            for i in range(fountainFeatureOp.TilesLength()):
                if fountainFeatureOp.Tiles(i) is None:
                    self.tiles.append(None)
                else:
                    tileCoord_ = nhc.rendering.ir._fb.TileCoord.TileCoordT.InitFromObj(fountainFeatureOp.Tiles(i))
                    self.tiles.append(tileCoord_)
        self.shape = fountainFeatureOp.Shape()
        self.seed = fountainFeatureOp.Seed()
        self.theme = fountainFeatureOp.Theme()

    # FountainFeatureOpT
    def Pack(self, builder):
        if self.tiles is not None:
            FountainFeatureOpStartTilesVector(builder, len(self.tiles))
            for i in reversed(range(len(self.tiles))):
                self.tiles[i].Pack(builder)
            tiles = builder.EndVector()
        if self.theme is not None:
            theme = builder.CreateString(self.theme)
        FountainFeatureOpStart(builder)
        if self.tiles is not None:
            FountainFeatureOpAddTiles(builder, tiles)
        FountainFeatureOpAddShape(builder, self.shape)
        FountainFeatureOpAddSeed(builder, self.seed)
        if self.theme is not None:
            FountainFeatureOpAddTheme(builder, theme)
        fountainFeatureOp = FountainFeatureOpEnd(builder)
        return fountainFeatureOp
