# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Gate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Gate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def GateBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x46", size_prefixed=size_prefixed)

    # Gate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Gate
    def EdgeIdx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Gate
    def TCenter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Gate
    def HalfPx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Gate
    def Style(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def GateStart(builder):
    builder.StartObject(4)

def Start(builder):
    GateStart(builder)

def GateAddEdgeIdx(builder, edgeIdx):
    builder.PrependUint32Slot(0, edgeIdx, 0)

def AddEdgeIdx(builder, edgeIdx):
    GateAddEdgeIdx(builder, edgeIdx)

def GateAddTCenter(builder, tCenter):
    builder.PrependFloat32Slot(1, tCenter, 0.0)

def AddTCenter(builder, tCenter):
    GateAddTCenter(builder, tCenter)

def GateAddHalfPx(builder, halfPx):
    builder.PrependFloat32Slot(2, halfPx, 0.0)

def AddHalfPx(builder, halfPx):
    GateAddHalfPx(builder, halfPx)

def GateAddStyle(builder, style):
    builder.PrependInt8Slot(3, style, 0)

def AddStyle(builder, style):
    GateAddStyle(builder, style)

def GateEnd(builder):
    return builder.EndObject()

def End(builder):
    return GateEnd(builder)


class GateT(object):

    # GateT
    def __init__(
        self,
        edgeIdx = 0,
        tCenter = 0.0,
        halfPx = 0.0,
        style = 0,
    ):
        self.edgeIdx = edgeIdx  # type: int
        self.tCenter = tCenter  # type: float
        self.halfPx = halfPx  # type: float
        self.style = style  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        gate = Gate()
        gate.Init(buf, pos)
        return cls.InitFromObj(gate)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, gate):
        x = GateT()
        x._UnPack(gate)
        return x

    # GateT
    def _UnPack(self, gate):
        if gate is None:
            return
        self.edgeIdx = gate.EdgeIdx()
        self.tCenter = gate.TCenter()
        self.halfPx = gate.HalfPx()
        self.style = gate.Style()

    # GateT
    def Pack(self, builder):
        GateStart(builder)
        GateAddEdgeIdx(builder, self.edgeIdx)
        GateAddTCenter(builder, self.tCenter)
        GateAddHalfPx(builder, self.halfPx)
        GateAddStyle(builder, self.style)
        gate = GateEnd(builder)
        return gate
