# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GenericProceduralOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GenericProceduralOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGenericProceduralOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def GenericProceduralOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x33", size_prefixed=size_prefixed)

    # GenericProceduralOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GenericProceduralOp
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GenericProceduralOp
    def Tiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from nhc.rendering.ir._fb.TileCoord import TileCoord
            obj = TileCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GenericProceduralOp
    def TilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GenericProceduralOp
    def TilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # GenericProceduralOp
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # GenericProceduralOp
    def Params(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from nhc.rendering.ir._fb.KV import KV
            obj = KV()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GenericProceduralOp
    def ParamsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GenericProceduralOp
    def ParamsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # GenericProceduralOp
    def Groups(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # GenericProceduralOp
    def GroupsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GenericProceduralOp
    def GroupsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def GenericProceduralOpStart(builder):
    builder.StartObject(5)

def Start(builder):
    GenericProceduralOpStart(builder)

def GenericProceduralOpAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    GenericProceduralOpAddName(builder, name)

def GenericProceduralOpAddTiles(builder, tiles):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(tiles), 0)

def AddTiles(builder, tiles):
    GenericProceduralOpAddTiles(builder, tiles)

def GenericProceduralOpStartTilesVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartTilesVector(builder, numElems):
    return GenericProceduralOpStartTilesVector(builder, numElems)

def GenericProceduralOpAddSeed(builder, seed):
    builder.PrependUint64Slot(2, seed, 0)

def AddSeed(builder, seed):
    GenericProceduralOpAddSeed(builder, seed)

def GenericProceduralOpAddParams(builder, params):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(params), 0)

def AddParams(builder, params):
    GenericProceduralOpAddParams(builder, params)

def GenericProceduralOpStartParamsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartParamsVector(builder, numElems):
    return GenericProceduralOpStartParamsVector(builder, numElems)

def GenericProceduralOpAddGroups(builder, groups):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(groups), 0)

def AddGroups(builder, groups):
    GenericProceduralOpAddGroups(builder, groups)

def GenericProceduralOpStartGroupsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartGroupsVector(builder, numElems):
    return GenericProceduralOpStartGroupsVector(builder, numElems)

def GenericProceduralOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return GenericProceduralOpEnd(builder)

import nhc.rendering.ir._fb.KV
import nhc.rendering.ir._fb.TileCoord
try:
    from typing import List
except:
    pass

class GenericProceduralOpT(object):

    # GenericProceduralOpT
    def __init__(
        self,
        name = None,
        tiles = None,
        seed = 0,
        params = None,
        groups = None,
    ):
        self.name = name  # type: Optional[str]
        self.tiles = tiles  # type: Optional[List[nhc.rendering.ir._fb.TileCoord.TileCoordT]]
        self.seed = seed  # type: int
        self.params = params  # type: Optional[List[nhc.rendering.ir._fb.KV.KVT]]
        self.groups = groups  # type: Optional[List[Optional[str]]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        genericProceduralOp = GenericProceduralOp()
        genericProceduralOp.Init(buf, pos)
        return cls.InitFromObj(genericProceduralOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, genericProceduralOp):
        x = GenericProceduralOpT()
        x._UnPack(genericProceduralOp)
        return x

    # GenericProceduralOpT
    def _UnPack(self, genericProceduralOp):
        if genericProceduralOp is None:
            return
        self.name = genericProceduralOp.Name()
        if not genericProceduralOp.TilesIsNone():
            self.tiles = []
            for i in range(genericProceduralOp.TilesLength()):
                if genericProceduralOp.Tiles(i) is None:
                    self.tiles.append(None)
                else:
                    tileCoord_ = nhc.rendering.ir._fb.TileCoord.TileCoordT.InitFromObj(genericProceduralOp.Tiles(i))
                    self.tiles.append(tileCoord_)
        self.seed = genericProceduralOp.Seed()
        if not genericProceduralOp.ParamsIsNone():
            self.params = []
            for i in range(genericProceduralOp.ParamsLength()):
                if genericProceduralOp.Params(i) is None:
                    self.params.append(None)
                else:
                    kV_ = nhc.rendering.ir._fb.KV.KVT.InitFromObj(genericProceduralOp.Params(i))
                    self.params.append(kV_)
        if not genericProceduralOp.GroupsIsNone():
            self.groups = []
            for i in range(genericProceduralOp.GroupsLength()):
                self.groups.append(genericProceduralOp.Groups(i))

    # GenericProceduralOpT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        if self.tiles is not None:
            GenericProceduralOpStartTilesVector(builder, len(self.tiles))
            for i in reversed(range(len(self.tiles))):
                self.tiles[i].Pack(builder)
            tiles = builder.EndVector()
        if self.params is not None:
            paramslist = []
            for i in range(len(self.params)):
                paramslist.append(self.params[i].Pack(builder))
            GenericProceduralOpStartParamsVector(builder, len(self.params))
            for i in reversed(range(len(self.params))):
                builder.PrependUOffsetTRelative(paramslist[i])
            params = builder.EndVector()
        if self.groups is not None:
            groupslist = []
            for i in range(len(self.groups)):
                groupslist.append(builder.CreateString(self.groups[i]))
            GenericProceduralOpStartGroupsVector(builder, len(self.groups))
            for i in reversed(range(len(self.groups))):
                builder.PrependUOffsetTRelative(groupslist[i])
            groups = builder.EndVector()
        GenericProceduralOpStart(builder)
        if self.name is not None:
            GenericProceduralOpAddName(builder, name)
        if self.tiles is not None:
            GenericProceduralOpAddTiles(builder, tiles)
        GenericProceduralOpAddSeed(builder, self.seed)
        if self.params is not None:
            GenericProceduralOpAddParams(builder, params)
        if self.groups is not None:
            GenericProceduralOpAddGroups(builder, groups)
        genericProceduralOp = GenericProceduralOpEnd(builder)
        return genericProceduralOp
