# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HatchOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HatchOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHatchOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def HatchOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x33", size_prefixed=size_prefixed)

    # HatchOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HatchOp
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # HatchOp
    def RegionOut(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HatchOp
    def RegionIn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HatchOp
    def Tiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from nhc.rendering.ir._fb.TileCoord import TileCoord
            obj = TileCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HatchOp
    def TilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HatchOp
    def TilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # HatchOp
    def ExtentTiles(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 2.0

    # HatchOp
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # HatchOp
    def Stride(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.5

    # HatchOp
    def HatchUnderlayColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HatchOp
    def IsOuter(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # HatchOp
    def IsOuterAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # HatchOp
    def IsOuterLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HatchOp
    def IsOuterIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

def HatchOpStart(builder):
    builder.StartObject(9)

def Start(builder):
    HatchOpStart(builder)

def HatchOpAddKind(builder, kind):
    builder.PrependInt8Slot(0, kind, 0)

def AddKind(builder, kind):
    HatchOpAddKind(builder, kind)

def HatchOpAddRegionOut(builder, regionOut):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(regionOut), 0)

def AddRegionOut(builder, regionOut):
    HatchOpAddRegionOut(builder, regionOut)

def HatchOpAddRegionIn(builder, regionIn):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(regionIn), 0)

def AddRegionIn(builder, regionIn):
    HatchOpAddRegionIn(builder, regionIn)

def HatchOpAddTiles(builder, tiles):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(tiles), 0)

def AddTiles(builder, tiles):
    HatchOpAddTiles(builder, tiles)

def HatchOpStartTilesVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartTilesVector(builder, numElems):
    return HatchOpStartTilesVector(builder, numElems)

def HatchOpAddExtentTiles(builder, extentTiles):
    builder.PrependFloat32Slot(4, extentTiles, 2.0)

def AddExtentTiles(builder, extentTiles):
    HatchOpAddExtentTiles(builder, extentTiles)

def HatchOpAddSeed(builder, seed):
    builder.PrependUint64Slot(5, seed, 0)

def AddSeed(builder, seed):
    HatchOpAddSeed(builder, seed)

def HatchOpAddStride(builder, stride):
    builder.PrependFloat32Slot(6, stride, 0.5)

def AddStride(builder, stride):
    HatchOpAddStride(builder, stride)

def HatchOpAddHatchUnderlayColor(builder, hatchUnderlayColor):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(hatchUnderlayColor), 0)

def AddHatchUnderlayColor(builder, hatchUnderlayColor):
    HatchOpAddHatchUnderlayColor(builder, hatchUnderlayColor)

def HatchOpAddIsOuter(builder, isOuter):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(isOuter), 0)

def AddIsOuter(builder, isOuter):
    HatchOpAddIsOuter(builder, isOuter)

def HatchOpStartIsOuterVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartIsOuterVector(builder, numElems):
    return HatchOpStartIsOuterVector(builder, numElems)

def HatchOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return HatchOpEnd(builder)

import nhc.rendering.ir._fb.TileCoord
try:
    from typing import List
except:
    pass

class HatchOpT(object):

    # HatchOpT
    def __init__(
        self,
        kind = 0,
        regionOut = None,
        regionIn = None,
        tiles = None,
        extentTiles = 2.0,
        seed = 0,
        stride = 0.5,
        hatchUnderlayColor = None,
        isOuter = None,
    ):
        self.kind = kind  # type: int
        self.regionOut = regionOut  # type: Optional[str]
        self.regionIn = regionIn  # type: Optional[str]
        self.tiles = tiles  # type: Optional[List[nhc.rendering.ir._fb.TileCoord.TileCoordT]]
        self.extentTiles = extentTiles  # type: float
        self.seed = seed  # type: int
        self.stride = stride  # type: float
        self.hatchUnderlayColor = hatchUnderlayColor  # type: Optional[str]
        self.isOuter = isOuter  # type: Optional[List[bool]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        hatchOp = HatchOp()
        hatchOp.Init(buf, pos)
        return cls.InitFromObj(hatchOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, hatchOp):
        x = HatchOpT()
        x._UnPack(hatchOp)
        return x

    # HatchOpT
    def _UnPack(self, hatchOp):
        if hatchOp is None:
            return
        self.kind = hatchOp.Kind()
        self.regionOut = hatchOp.RegionOut()
        self.regionIn = hatchOp.RegionIn()
        if not hatchOp.TilesIsNone():
            self.tiles = []
            for i in range(hatchOp.TilesLength()):
                if hatchOp.Tiles(i) is None:
                    self.tiles.append(None)
                else:
                    tileCoord_ = nhc.rendering.ir._fb.TileCoord.TileCoordT.InitFromObj(hatchOp.Tiles(i))
                    self.tiles.append(tileCoord_)
        self.extentTiles = hatchOp.ExtentTiles()
        self.seed = hatchOp.Seed()
        self.stride = hatchOp.Stride()
        self.hatchUnderlayColor = hatchOp.HatchUnderlayColor()
        if not hatchOp.IsOuterIsNone():
            if np is None:
                self.isOuter = []
                for i in range(hatchOp.IsOuterLength()):
                    self.isOuter.append(hatchOp.IsOuter(i))
            else:
                self.isOuter = hatchOp.IsOuterAsNumpy()

    # HatchOpT
    def Pack(self, builder):
        if self.regionOut is not None:
            regionOut = builder.CreateString(self.regionOut)
        if self.regionIn is not None:
            regionIn = builder.CreateString(self.regionIn)
        if self.tiles is not None:
            HatchOpStartTilesVector(builder, len(self.tiles))
            for i in reversed(range(len(self.tiles))):
                self.tiles[i].Pack(builder)
            tiles = builder.EndVector()
        if self.hatchUnderlayColor is not None:
            hatchUnderlayColor = builder.CreateString(self.hatchUnderlayColor)
        if self.isOuter is not None:
            if np is not None and type(self.isOuter) is np.ndarray:
                isOuter = builder.CreateNumpyVector(self.isOuter)
            else:
                HatchOpStartIsOuterVector(builder, len(self.isOuter))
                for i in reversed(range(len(self.isOuter))):
                    builder.PrependBool(self.isOuter[i])
                isOuter = builder.EndVector()
        HatchOpStart(builder)
        HatchOpAddKind(builder, self.kind)
        if self.regionOut is not None:
            HatchOpAddRegionOut(builder, regionOut)
        if self.regionIn is not None:
            HatchOpAddRegionIn(builder, regionIn)
        if self.tiles is not None:
            HatchOpAddTiles(builder, tiles)
        HatchOpAddExtentTiles(builder, self.extentTiles)
        HatchOpAddSeed(builder, self.seed)
        HatchOpAddStride(builder, self.stride)
        if self.hatchUnderlayColor is not None:
            HatchOpAddHatchUnderlayColor(builder, hatchUnderlayColor)
        if self.isOuter is not None:
            HatchOpAddIsOuter(builder, isOuter)
        hatchOp = HatchOpEnd(builder)
        return hatchOp
