# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HatchOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HatchOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHatchOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def HatchOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x35", size_prefixed=size_prefixed)

    # HatchOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HatchOp
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # HatchOp
    def RegionRef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HatchOp
    def SubtractRegionRefs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # HatchOp
    def SubtractRegionRefsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HatchOp
    def SubtractRegionRefsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # HatchOp
    def Tiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from nhc.rendering.ir._fb.TileCoord import TileCoord
            obj = TileCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HatchOp
    def TilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HatchOp
    def TilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # HatchOp
    def IsOuter(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # HatchOp
    def IsOuterAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # HatchOp
    def IsOuterLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HatchOp
    def IsOuterIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # HatchOp
    def ExtentTiles(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 2.0

    # HatchOp
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # HatchOp
    def HatchUnderlayColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def HatchOpStart(builder):
    builder.StartObject(8)

def Start(builder):
    HatchOpStart(builder)

def HatchOpAddKind(builder, kind):
    builder.PrependInt8Slot(0, kind, 0)

def AddKind(builder, kind):
    HatchOpAddKind(builder, kind)

def HatchOpAddRegionRef(builder, regionRef):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(regionRef), 0)

def AddRegionRef(builder, regionRef):
    HatchOpAddRegionRef(builder, regionRef)

def HatchOpAddSubtractRegionRefs(builder, subtractRegionRefs):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(subtractRegionRefs), 0)

def AddSubtractRegionRefs(builder, subtractRegionRefs):
    HatchOpAddSubtractRegionRefs(builder, subtractRegionRefs)

def HatchOpStartSubtractRegionRefsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSubtractRegionRefsVector(builder, numElems):
    return HatchOpStartSubtractRegionRefsVector(builder, numElems)

def HatchOpAddTiles(builder, tiles):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(tiles), 0)

def AddTiles(builder, tiles):
    HatchOpAddTiles(builder, tiles)

def HatchOpStartTilesVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartTilesVector(builder, numElems):
    return HatchOpStartTilesVector(builder, numElems)

def HatchOpAddIsOuter(builder, isOuter):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(isOuter), 0)

def AddIsOuter(builder, isOuter):
    HatchOpAddIsOuter(builder, isOuter)

def HatchOpStartIsOuterVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartIsOuterVector(builder, numElems):
    return HatchOpStartIsOuterVector(builder, numElems)

def HatchOpAddExtentTiles(builder, extentTiles):
    builder.PrependFloat32Slot(5, extentTiles, 2.0)

def AddExtentTiles(builder, extentTiles):
    HatchOpAddExtentTiles(builder, extentTiles)

def HatchOpAddSeed(builder, seed):
    builder.PrependUint64Slot(6, seed, 0)

def AddSeed(builder, seed):
    HatchOpAddSeed(builder, seed)

def HatchOpAddHatchUnderlayColor(builder, hatchUnderlayColor):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(hatchUnderlayColor), 0)

def AddHatchUnderlayColor(builder, hatchUnderlayColor):
    HatchOpAddHatchUnderlayColor(builder, hatchUnderlayColor)

def HatchOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return HatchOpEnd(builder)

import nhc.rendering.ir._fb.TileCoord
try:
    from typing import List
except:
    pass

class HatchOpT(object):

    # HatchOpT
    def __init__(
        self,
        kind = 0,
        regionRef = None,
        subtractRegionRefs = None,
        tiles = None,
        isOuter = None,
        extentTiles = 2.0,
        seed = 0,
        hatchUnderlayColor = None,
    ):
        self.kind = kind  # type: int
        self.regionRef = regionRef  # type: Optional[str]
        self.subtractRegionRefs = subtractRegionRefs  # type: Optional[List[Optional[str]]]
        self.tiles = tiles  # type: Optional[List[nhc.rendering.ir._fb.TileCoord.TileCoordT]]
        self.isOuter = isOuter  # type: Optional[List[bool]]
        self.extentTiles = extentTiles  # type: float
        self.seed = seed  # type: int
        self.hatchUnderlayColor = hatchUnderlayColor  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        hatchOp = HatchOp()
        hatchOp.Init(buf, pos)
        return cls.InitFromObj(hatchOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, hatchOp):
        x = HatchOpT()
        x._UnPack(hatchOp)
        return x

    # HatchOpT
    def _UnPack(self, hatchOp):
        if hatchOp is None:
            return
        self.kind = hatchOp.Kind()
        self.regionRef = hatchOp.RegionRef()
        if not hatchOp.SubtractRegionRefsIsNone():
            self.subtractRegionRefs = []
            for i in range(hatchOp.SubtractRegionRefsLength()):
                self.subtractRegionRefs.append(hatchOp.SubtractRegionRefs(i))
        if not hatchOp.TilesIsNone():
            self.tiles = []
            for i in range(hatchOp.TilesLength()):
                if hatchOp.Tiles(i) is None:
                    self.tiles.append(None)
                else:
                    tileCoord_ = nhc.rendering.ir._fb.TileCoord.TileCoordT.InitFromObj(hatchOp.Tiles(i))
                    self.tiles.append(tileCoord_)
        if not hatchOp.IsOuterIsNone():
            if np is None:
                self.isOuter = []
                for i in range(hatchOp.IsOuterLength()):
                    self.isOuter.append(hatchOp.IsOuter(i))
            else:
                self.isOuter = hatchOp.IsOuterAsNumpy()
        self.extentTiles = hatchOp.ExtentTiles()
        self.seed = hatchOp.Seed()
        self.hatchUnderlayColor = hatchOp.HatchUnderlayColor()

    # HatchOpT
    def Pack(self, builder):
        if self.regionRef is not None:
            regionRef = builder.CreateString(self.regionRef)
        if self.subtractRegionRefs is not None:
            subtractRegionRefslist = []
            for i in range(len(self.subtractRegionRefs)):
                subtractRegionRefslist.append(builder.CreateString(self.subtractRegionRefs[i]))
            HatchOpStartSubtractRegionRefsVector(builder, len(self.subtractRegionRefs))
            for i in reversed(range(len(self.subtractRegionRefs))):
                builder.PrependUOffsetTRelative(subtractRegionRefslist[i])
            subtractRegionRefs = builder.EndVector()
        if self.tiles is not None:
            HatchOpStartTilesVector(builder, len(self.tiles))
            for i in reversed(range(len(self.tiles))):
                self.tiles[i].Pack(builder)
            tiles = builder.EndVector()
        if self.isOuter is not None:
            if np is not None and type(self.isOuter) is np.ndarray:
                isOuter = builder.CreateNumpyVector(self.isOuter)
            else:
                HatchOpStartIsOuterVector(builder, len(self.isOuter))
                for i in reversed(range(len(self.isOuter))):
                    builder.PrependBool(self.isOuter[i])
                isOuter = builder.EndVector()
        if self.hatchUnderlayColor is not None:
            hatchUnderlayColor = builder.CreateString(self.hatchUnderlayColor)
        HatchOpStart(builder)
        HatchOpAddKind(builder, self.kind)
        if self.regionRef is not None:
            HatchOpAddRegionRef(builder, regionRef)
        if self.subtractRegionRefs is not None:
            HatchOpAddSubtractRegionRefs(builder, subtractRegionRefs)
        if self.tiles is not None:
            HatchOpAddTiles(builder, tiles)
        if self.isOuter is not None:
            HatchOpAddIsOuter(builder, isOuter)
        HatchOpAddExtentTiles(builder, self.extentTiles)
        HatchOpAddSeed(builder, self.seed)
        if self.hatchUnderlayColor is not None:
            HatchOpAddHatchUnderlayColor(builder, hatchUnderlayColor)
        hatchOp = HatchOpEnd(builder)
        return hatchOp
