# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class KV(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KV()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKV(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def KVBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x46", size_prefixed=size_prefixed)

    # KV
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KV
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # KV
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def KVStart(builder):
    builder.StartObject(2)

def Start(builder):
    KVStart(builder)

def KVAddKey(builder, key):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def AddKey(builder, key):
    KVAddKey(builder, key)

def KVAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    KVAddValue(builder, value)

def KVEnd(builder):
    return builder.EndObject()

def End(builder):
    return KVEnd(builder)


class KVT(object):

    # KVT
    def __init__(
        self,
        key = None,
        value = None,
    ):
        self.key = key  # type: Optional[str]
        self.value = value  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        kv = KV()
        kv.Init(buf, pos)
        return cls.InitFromObj(kv)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, kv):
        x = KVT()
        x._UnPack(kv)
        return x

    # KVT
    def _UnPack(self, kv):
        if kv is None:
            return
        self.key = kv.Key()
        self.value = kv.Value()

    # KVT
    def Pack(self, builder):
        if self.key is not None:
            key = builder.CreateString(self.key)
        if self.value is not None:
            value = builder.CreateString(self.value)
        KVStart(builder)
        if self.key is not None:
            KVAddKey(builder, key)
        if self.value is not None:
            KVAddValue(builder, value)
        kv = KVEnd(builder)
        return kv
