# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

class MaterialFamily(object):
    Plain = 0
    Cave = 1
    Wood = 2
    Stone = 3
    Earth = 4
    Liquid = 5
    Special = 6
