# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

class Op(object):
    NONE = 0
    ShadowOp = 1
    HatchOp = 2
    WallsAndFloorsOp = 3
    TerrainTintOp = 4
    FloorGridOp = 5
    FloorDetailOp = 6
    ThematicDetailOp = 7
    TerrainDetailOp = 8
    StairsOp = 9
    TreeFeatureOp = 10
    BushFeatureOp = 11
    WellFeatureOp = 12
    FountainFeatureOp = 13
    GenericProceduralOp = 14
    DecoratorOp = 15
    RoofOp = 16
    EnclosureOp = 17
    BuildingExteriorWallOp = 18
    BuildingInteriorWallOp = 19
    FloorOp = 20
    InteriorWallOp = 21
    ExteriorWallOp = 22

def OpCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == Op.ShadowOp:
        import nhc.rendering.ir._fb.ShadowOp
        return nhc.rendering.ir._fb.ShadowOp.ShadowOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.HatchOp:
        import nhc.rendering.ir._fb.HatchOp
        return nhc.rendering.ir._fb.HatchOp.HatchOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.WallsAndFloorsOp:
        import nhc.rendering.ir._fb.WallsAndFloorsOp
        return nhc.rendering.ir._fb.WallsAndFloorsOp.WallsAndFloorsOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.TerrainTintOp:
        import nhc.rendering.ir._fb.TerrainTintOp
        return nhc.rendering.ir._fb.TerrainTintOp.TerrainTintOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.FloorGridOp:
        import nhc.rendering.ir._fb.FloorGridOp
        return nhc.rendering.ir._fb.FloorGridOp.FloorGridOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.FloorDetailOp:
        import nhc.rendering.ir._fb.FloorDetailOp
        return nhc.rendering.ir._fb.FloorDetailOp.FloorDetailOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.ThematicDetailOp:
        import nhc.rendering.ir._fb.ThematicDetailOp
        return nhc.rendering.ir._fb.ThematicDetailOp.ThematicDetailOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.TerrainDetailOp:
        import nhc.rendering.ir._fb.TerrainDetailOp
        return nhc.rendering.ir._fb.TerrainDetailOp.TerrainDetailOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.StairsOp:
        import nhc.rendering.ir._fb.StairsOp
        return nhc.rendering.ir._fb.StairsOp.StairsOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.TreeFeatureOp:
        import nhc.rendering.ir._fb.TreeFeatureOp
        return nhc.rendering.ir._fb.TreeFeatureOp.TreeFeatureOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.BushFeatureOp:
        import nhc.rendering.ir._fb.BushFeatureOp
        return nhc.rendering.ir._fb.BushFeatureOp.BushFeatureOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.WellFeatureOp:
        import nhc.rendering.ir._fb.WellFeatureOp
        return nhc.rendering.ir._fb.WellFeatureOp.WellFeatureOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.FountainFeatureOp:
        import nhc.rendering.ir._fb.FountainFeatureOp
        return nhc.rendering.ir._fb.FountainFeatureOp.FountainFeatureOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.GenericProceduralOp:
        import nhc.rendering.ir._fb.GenericProceduralOp
        return nhc.rendering.ir._fb.GenericProceduralOp.GenericProceduralOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.DecoratorOp:
        import nhc.rendering.ir._fb.DecoratorOp
        return nhc.rendering.ir._fb.DecoratorOp.DecoratorOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.RoofOp:
        import nhc.rendering.ir._fb.RoofOp
        return nhc.rendering.ir._fb.RoofOp.RoofOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.EnclosureOp:
        import nhc.rendering.ir._fb.EnclosureOp
        return nhc.rendering.ir._fb.EnclosureOp.EnclosureOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.BuildingExteriorWallOp:
        import nhc.rendering.ir._fb.BuildingExteriorWallOp
        return nhc.rendering.ir._fb.BuildingExteriorWallOp.BuildingExteriorWallOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.BuildingInteriorWallOp:
        import nhc.rendering.ir._fb.BuildingInteriorWallOp
        return nhc.rendering.ir._fb.BuildingInteriorWallOp.BuildingInteriorWallOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.FloorOp:
        import nhc.rendering.ir._fb.FloorOp
        return nhc.rendering.ir._fb.FloorOp.FloorOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.InteriorWallOp:
        import nhc.rendering.ir._fb.InteriorWallOp
        return nhc.rendering.ir._fb.InteriorWallOp.InteriorWallOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.ExteriorWallOp:
        import nhc.rendering.ir._fb.ExteriorWallOp
        return nhc.rendering.ir._fb.ExteriorWallOp.ExteriorWallOpT.InitFromBuf(table.Bytes, table.Pos)
    return None
