# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

class Op(object):
    NONE = 0
    ShadowOp = 1
    HatchOp = 2
    WallsAndFloorsOp = 3
    TerrainTintOp = 4
    FloorGridOp = 5
    FloorDetailOp = 6
    ThematicDetailOp = 7
    TerrainDetailOp = 8
    StairsOp = 9
    CobblestoneOp = 10
    WoodFloorOp = 11
    GardenOverlayOp = 12
    FieldOverlayOp = 13
    CartTracksOp = 14
    OreDepositsOp = 15
    TreeFeatureOp = 16
    BushFeatureOp = 17
    WellFeatureOp = 18
    FountainFeatureOp = 19
    GenericProceduralOp = 20
    DecoratorOp = 21

def OpCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == Op.ShadowOp:
        import nhc.rendering.ir._fb.ShadowOp
        return nhc.rendering.ir._fb.ShadowOp.ShadowOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.HatchOp:
        import nhc.rendering.ir._fb.HatchOp
        return nhc.rendering.ir._fb.HatchOp.HatchOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.WallsAndFloorsOp:
        import nhc.rendering.ir._fb.WallsAndFloorsOp
        return nhc.rendering.ir._fb.WallsAndFloorsOp.WallsAndFloorsOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.TerrainTintOp:
        import nhc.rendering.ir._fb.TerrainTintOp
        return nhc.rendering.ir._fb.TerrainTintOp.TerrainTintOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.FloorGridOp:
        import nhc.rendering.ir._fb.FloorGridOp
        return nhc.rendering.ir._fb.FloorGridOp.FloorGridOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.FloorDetailOp:
        import nhc.rendering.ir._fb.FloorDetailOp
        return nhc.rendering.ir._fb.FloorDetailOp.FloorDetailOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.ThematicDetailOp:
        import nhc.rendering.ir._fb.ThematicDetailOp
        return nhc.rendering.ir._fb.ThematicDetailOp.ThematicDetailOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.TerrainDetailOp:
        import nhc.rendering.ir._fb.TerrainDetailOp
        return nhc.rendering.ir._fb.TerrainDetailOp.TerrainDetailOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.StairsOp:
        import nhc.rendering.ir._fb.StairsOp
        return nhc.rendering.ir._fb.StairsOp.StairsOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.CobblestoneOp:
        import nhc.rendering.ir._fb.CobblestoneOp
        return nhc.rendering.ir._fb.CobblestoneOp.CobblestoneOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.WoodFloorOp:
        import nhc.rendering.ir._fb.WoodFloorOp
        return nhc.rendering.ir._fb.WoodFloorOp.WoodFloorOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.GardenOverlayOp:
        import nhc.rendering.ir._fb.GardenOverlayOp
        return nhc.rendering.ir._fb.GardenOverlayOp.GardenOverlayOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.FieldOverlayOp:
        import nhc.rendering.ir._fb.FieldOverlayOp
        return nhc.rendering.ir._fb.FieldOverlayOp.FieldOverlayOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.CartTracksOp:
        import nhc.rendering.ir._fb.CartTracksOp
        return nhc.rendering.ir._fb.CartTracksOp.CartTracksOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.OreDepositsOp:
        import nhc.rendering.ir._fb.OreDepositsOp
        return nhc.rendering.ir._fb.OreDepositsOp.OreDepositsOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.TreeFeatureOp:
        import nhc.rendering.ir._fb.TreeFeatureOp
        return nhc.rendering.ir._fb.TreeFeatureOp.TreeFeatureOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.BushFeatureOp:
        import nhc.rendering.ir._fb.BushFeatureOp
        return nhc.rendering.ir._fb.BushFeatureOp.BushFeatureOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.WellFeatureOp:
        import nhc.rendering.ir._fb.WellFeatureOp
        return nhc.rendering.ir._fb.WellFeatureOp.WellFeatureOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.FountainFeatureOp:
        import nhc.rendering.ir._fb.FountainFeatureOp
        return nhc.rendering.ir._fb.FountainFeatureOp.FountainFeatureOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.GenericProceduralOp:
        import nhc.rendering.ir._fb.GenericProceduralOp
        return nhc.rendering.ir._fb.GenericProceduralOp.GenericProceduralOpT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Op.DecoratorOp:
        import nhc.rendering.ir._fb.DecoratorOp
        return nhc.rendering.ir._fb.DecoratorOp.DecoratorOpT.InitFromBuf(table.Bytes, table.Pos)
    return None
