# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OpusRomanoVariant(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OpusRomanoVariant()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOpusRomanoVariant(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def OpusRomanoVariantBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x33", size_prefixed=size_prefixed)

    # OpusRomanoVariant
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OpusRomanoVariant
    def Tiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from nhc.rendering.ir._fb.TileCoord import TileCoord
            obj = TileCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OpusRomanoVariant
    def TilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OpusRomanoVariant
    def TilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def OpusRomanoVariantStart(builder):
    builder.StartObject(1)

def Start(builder):
    OpusRomanoVariantStart(builder)

def OpusRomanoVariantAddTiles(builder, tiles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tiles), 0)

def AddTiles(builder, tiles):
    OpusRomanoVariantAddTiles(builder, tiles)

def OpusRomanoVariantStartTilesVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartTilesVector(builder, numElems):
    return OpusRomanoVariantStartTilesVector(builder, numElems)

def OpusRomanoVariantEnd(builder):
    return builder.EndObject()

def End(builder):
    return OpusRomanoVariantEnd(builder)

import nhc.rendering.ir._fb.TileCoord
try:
    from typing import List
except:
    pass

class OpusRomanoVariantT(object):

    # OpusRomanoVariantT
    def __init__(
        self,
        tiles = None,
    ):
        self.tiles = tiles  # type: Optional[List[nhc.rendering.ir._fb.TileCoord.TileCoordT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        opusRomanoVariant = OpusRomanoVariant()
        opusRomanoVariant.Init(buf, pos)
        return cls.InitFromObj(opusRomanoVariant)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, opusRomanoVariant):
        x = OpusRomanoVariantT()
        x._UnPack(opusRomanoVariant)
        return x

    # OpusRomanoVariantT
    def _UnPack(self, opusRomanoVariant):
        if opusRomanoVariant is None:
            return
        if not opusRomanoVariant.TilesIsNone():
            self.tiles = []
            for i in range(opusRomanoVariant.TilesLength()):
                if opusRomanoVariant.Tiles(i) is None:
                    self.tiles.append(None)
                else:
                    tileCoord_ = nhc.rendering.ir._fb.TileCoord.TileCoordT.InitFromObj(opusRomanoVariant.Tiles(i))
                    self.tiles.append(tileCoord_)

    # OpusRomanoVariantT
    def Pack(self, builder):
        if self.tiles is not None:
            OpusRomanoVariantStartTilesVector(builder, len(self.tiles))
            for i in reversed(range(len(self.tiles))):
                self.tiles[i].Pack(builder)
            tiles = builder.EndVector()
        OpusRomanoVariantStart(builder)
        if self.tiles is not None:
            OpusRomanoVariantAddTiles(builder, tiles)
        opusRomanoVariant = OpusRomanoVariantEnd(builder)
        return opusRomanoVariant
