# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Outline(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Outline()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOutline(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def OutlineBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x33", size_prefixed=size_prefixed)

    # Outline
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Outline
    def Vertices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from nhc.rendering.ir._fb.Vec2 import Vec2
            obj = Vec2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Outline
    def VerticesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Outline
    def VerticesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Outline
    def Cuts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from nhc.rendering.ir._fb.Cut import Cut
            obj = Cut()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Outline
    def CutsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Outline
    def CutsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Outline
    def Closed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # Outline
    def DescriptorKind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Outline
    def Cx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Outline
    def Cy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Outline
    def Rx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Outline
    def Ry(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Outline
    def Rings(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            from nhc.rendering.ir._fb.PathRange import PathRange
            obj = PathRange()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Outline
    def RingsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Outline
    def RingsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

def OutlineStart(builder):
    builder.StartObject(9)

def Start(builder):
    OutlineStart(builder)

def OutlineAddVertices(builder, vertices):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(vertices), 0)

def AddVertices(builder, vertices):
    OutlineAddVertices(builder, vertices)

def OutlineStartVerticesVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartVerticesVector(builder, numElems):
    return OutlineStartVerticesVector(builder, numElems)

def OutlineAddCuts(builder, cuts):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(cuts), 0)

def AddCuts(builder, cuts):
    OutlineAddCuts(builder, cuts)

def OutlineStartCutsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCutsVector(builder, numElems):
    return OutlineStartCutsVector(builder, numElems)

def OutlineAddClosed(builder, closed):
    builder.PrependBoolSlot(2, closed, 1)

def AddClosed(builder, closed):
    OutlineAddClosed(builder, closed)

def OutlineAddDescriptorKind(builder, descriptorKind):
    builder.PrependUint8Slot(3, descriptorKind, 0)

def AddDescriptorKind(builder, descriptorKind):
    OutlineAddDescriptorKind(builder, descriptorKind)

def OutlineAddCx(builder, cx):
    builder.PrependFloat32Slot(4, cx, 0.0)

def AddCx(builder, cx):
    OutlineAddCx(builder, cx)

def OutlineAddCy(builder, cy):
    builder.PrependFloat32Slot(5, cy, 0.0)

def AddCy(builder, cy):
    OutlineAddCy(builder, cy)

def OutlineAddRx(builder, rx):
    builder.PrependFloat32Slot(6, rx, 0.0)

def AddRx(builder, rx):
    OutlineAddRx(builder, rx)

def OutlineAddRy(builder, ry):
    builder.PrependFloat32Slot(7, ry, 0.0)

def AddRy(builder, ry):
    OutlineAddRy(builder, ry)

def OutlineAddRings(builder, rings):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(rings), 0)

def AddRings(builder, rings):
    OutlineAddRings(builder, rings)

def OutlineStartRingsVector(builder, numElems):
    return builder.StartVector(12, numElems, 4)

def StartRingsVector(builder, numElems):
    return OutlineStartRingsVector(builder, numElems)

def OutlineEnd(builder):
    return builder.EndObject()

def End(builder):
    return OutlineEnd(builder)

import nhc.rendering.ir._fb.Cut
import nhc.rendering.ir._fb.PathRange
import nhc.rendering.ir._fb.Vec2
try:
    from typing import List
except:
    pass

class OutlineT(object):

    # OutlineT
    def __init__(
        self,
        vertices = None,
        cuts = None,
        closed = True,
        descriptorKind = 0,
        cx = 0.0,
        cy = 0.0,
        rx = 0.0,
        ry = 0.0,
        rings = None,
    ):
        self.vertices = vertices  # type: Optional[List[nhc.rendering.ir._fb.Vec2.Vec2T]]
        self.cuts = cuts  # type: Optional[List[nhc.rendering.ir._fb.Cut.CutT]]
        self.closed = closed  # type: bool
        self.descriptorKind = descriptorKind  # type: int
        self.cx = cx  # type: float
        self.cy = cy  # type: float
        self.rx = rx  # type: float
        self.ry = ry  # type: float
        self.rings = rings  # type: Optional[List[nhc.rendering.ir._fb.PathRange.PathRangeT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        outline = Outline()
        outline.Init(buf, pos)
        return cls.InitFromObj(outline)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, outline):
        x = OutlineT()
        x._UnPack(outline)
        return x

    # OutlineT
    def _UnPack(self, outline):
        if outline is None:
            return
        if not outline.VerticesIsNone():
            self.vertices = []
            for i in range(outline.VerticesLength()):
                if outline.Vertices(i) is None:
                    self.vertices.append(None)
                else:
                    vec2_ = nhc.rendering.ir._fb.Vec2.Vec2T.InitFromObj(outline.Vertices(i))
                    self.vertices.append(vec2_)
        if not outline.CutsIsNone():
            self.cuts = []
            for i in range(outline.CutsLength()):
                if outline.Cuts(i) is None:
                    self.cuts.append(None)
                else:
                    cut_ = nhc.rendering.ir._fb.Cut.CutT.InitFromObj(outline.Cuts(i))
                    self.cuts.append(cut_)
        self.closed = outline.Closed()
        self.descriptorKind = outline.DescriptorKind()
        self.cx = outline.Cx()
        self.cy = outline.Cy()
        self.rx = outline.Rx()
        self.ry = outline.Ry()
        if not outline.RingsIsNone():
            self.rings = []
            for i in range(outline.RingsLength()):
                if outline.Rings(i) is None:
                    self.rings.append(None)
                else:
                    pathRange_ = nhc.rendering.ir._fb.PathRange.PathRangeT.InitFromObj(outline.Rings(i))
                    self.rings.append(pathRange_)

    # OutlineT
    def Pack(self, builder):
        if self.vertices is not None:
            OutlineStartVerticesVector(builder, len(self.vertices))
            for i in reversed(range(len(self.vertices))):
                self.vertices[i].Pack(builder)
            vertices = builder.EndVector()
        if self.cuts is not None:
            cutslist = []
            for i in range(len(self.cuts)):
                cutslist.append(self.cuts[i].Pack(builder))
            OutlineStartCutsVector(builder, len(self.cuts))
            for i in reversed(range(len(self.cuts))):
                builder.PrependUOffsetTRelative(cutslist[i])
            cuts = builder.EndVector()
        if self.rings is not None:
            OutlineStartRingsVector(builder, len(self.rings))
            for i in reversed(range(len(self.rings))):
                self.rings[i].Pack(builder)
            rings = builder.EndVector()
        OutlineStart(builder)
        if self.vertices is not None:
            OutlineAddVertices(builder, vertices)
        if self.cuts is not None:
            OutlineAddCuts(builder, cuts)
        OutlineAddClosed(builder, self.closed)
        OutlineAddDescriptorKind(builder, self.descriptorKind)
        OutlineAddCx(builder, self.cx)
        OutlineAddCy(builder, self.cy)
        OutlineAddRx(builder, self.rx)
        OutlineAddRy(builder, self.ry)
        if self.rings is not None:
            OutlineAddRings(builder, rings)
        outline = OutlineEnd(builder)
        return outline
