# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RoofOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RoofOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRoofOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RoofOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x34", size_prefixed=size_prefixed)

    # RoofOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RoofOp
    def RegionRef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RoofOp
    def Style(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # RoofOp
    def Tint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RoofOp
    def RngSeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def RoofOpStart(builder):
    builder.StartObject(4)

def Start(builder):
    RoofOpStart(builder)

def RoofOpAddRegionRef(builder, regionRef):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(regionRef), 0)

def AddRegionRef(builder, regionRef):
    RoofOpAddRegionRef(builder, regionRef)

def RoofOpAddStyle(builder, style):
    builder.PrependInt8Slot(1, style, 0)

def AddStyle(builder, style):
    RoofOpAddStyle(builder, style)

def RoofOpAddTint(builder, tint):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(tint), 0)

def AddTint(builder, tint):
    RoofOpAddTint(builder, tint)

def RoofOpAddRngSeed(builder, rngSeed):
    builder.PrependUint64Slot(3, rngSeed, 0)

def AddRngSeed(builder, rngSeed):
    RoofOpAddRngSeed(builder, rngSeed)

def RoofOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return RoofOpEnd(builder)


class RoofOpT(object):

    # RoofOpT
    def __init__(
        self,
        regionRef = None,
        style = 0,
        tint = None,
        rngSeed = 0,
    ):
        self.regionRef = regionRef  # type: Optional[str]
        self.style = style  # type: int
        self.tint = tint  # type: Optional[str]
        self.rngSeed = rngSeed  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        roofOp = RoofOp()
        roofOp.Init(buf, pos)
        return cls.InitFromObj(roofOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, roofOp):
        x = RoofOpT()
        x._UnPack(roofOp)
        return x

    # RoofOpT
    def _UnPack(self, roofOp):
        if roofOp is None:
            return
        self.regionRef = roofOp.RegionRef()
        self.style = roofOp.Style()
        self.tint = roofOp.Tint()
        self.rngSeed = roofOp.RngSeed()

    # RoofOpT
    def Pack(self, builder):
        if self.regionRef is not None:
            regionRef = builder.CreateString(self.regionRef)
        if self.tint is not None:
            tint = builder.CreateString(self.tint)
        RoofOpStart(builder)
        if self.regionRef is not None:
            RoofOpAddRegionRef(builder, regionRef)
        RoofOpAddStyle(builder, self.style)
        if self.tint is not None:
            RoofOpAddTint(builder, tint)
        RoofOpAddRngSeed(builder, self.rngSeed)
        roofOp = RoofOpEnd(builder)
        return roofOp
