# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RoomWash(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RoomWash()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRoomWash(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RoomWashBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x34", size_prefixed=size_prefixed)

    # RoomWash
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RoomWash
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RoomWash
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RoomWash
    def W(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RoomWash
    def H(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RoomWash
    def Color(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RoomWash
    def Opacity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def RoomWashStart(builder):
    builder.StartObject(6)

def Start(builder):
    RoomWashStart(builder)

def RoomWashAddX(builder, x):
    builder.PrependInt32Slot(0, x, 0)

def AddX(builder, x):
    RoomWashAddX(builder, x)

def RoomWashAddY(builder, y):
    builder.PrependInt32Slot(1, y, 0)

def AddY(builder, y):
    RoomWashAddY(builder, y)

def RoomWashAddW(builder, w):
    builder.PrependInt32Slot(2, w, 0)

def AddW(builder, w):
    RoomWashAddW(builder, w)

def RoomWashAddH(builder, h):
    builder.PrependInt32Slot(3, h, 0)

def AddH(builder, h):
    RoomWashAddH(builder, h)

def RoomWashAddColor(builder, color):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(color), 0)

def AddColor(builder, color):
    RoomWashAddColor(builder, color)

def RoomWashAddOpacity(builder, opacity):
    builder.PrependFloat32Slot(5, opacity, 0.0)

def AddOpacity(builder, opacity):
    RoomWashAddOpacity(builder, opacity)

def RoomWashEnd(builder):
    return builder.EndObject()

def End(builder):
    return RoomWashEnd(builder)


class RoomWashT(object):

    # RoomWashT
    def __init__(
        self,
        x = 0,
        y = 0,
        w = 0,
        h = 0,
        color = None,
        opacity = 0.0,
    ):
        self.x = x  # type: int
        self.y = y  # type: int
        self.w = w  # type: int
        self.h = h  # type: int
        self.color = color  # type: Optional[str]
        self.opacity = opacity  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        roomWash = RoomWash()
        roomWash.Init(buf, pos)
        return cls.InitFromObj(roomWash)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, roomWash):
        x = RoomWashT()
        x._UnPack(roomWash)
        return x

    # RoomWashT
    def _UnPack(self, roomWash):
        if roomWash is None:
            return
        self.x = roomWash.X()
        self.y = roomWash.Y()
        self.w = roomWash.W()
        self.h = roomWash.H()
        self.color = roomWash.Color()
        self.opacity = roomWash.Opacity()

    # RoomWashT
    def Pack(self, builder):
        if self.color is not None:
            color = builder.CreateString(self.color)
        RoomWashStart(builder)
        RoomWashAddX(builder, self.x)
        RoomWashAddY(builder, self.y)
        RoomWashAddW(builder, self.w)
        RoomWashAddH(builder, self.h)
        if self.color is not None:
            RoomWashAddColor(builder, color)
        RoomWashAddOpacity(builder, self.opacity)
        roomWash = RoomWashEnd(builder)
        return roomWash
