# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StairsOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StairsOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStairsOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StairsOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x34", size_prefixed=size_prefixed)

    # StairsOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StairsOp
    def Stairs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            from nhc.rendering.ir._fb.StairTile import StairTile
            obj = StairTile()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StairsOp
    def StairsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StairsOp
    def StairsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # StairsOp
    def Theme(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StairsOp
    def FillColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def StairsOpStart(builder):
    builder.StartObject(3)

def Start(builder):
    StairsOpStart(builder)

def StairsOpAddStairs(builder, stairs):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(stairs), 0)

def AddStairs(builder, stairs):
    StairsOpAddStairs(builder, stairs)

def StairsOpStartStairsVector(builder, numElems):
    return builder.StartVector(12, numElems, 4)

def StartStairsVector(builder, numElems):
    return StairsOpStartStairsVector(builder, numElems)

def StairsOpAddTheme(builder, theme):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(theme), 0)

def AddTheme(builder, theme):
    StairsOpAddTheme(builder, theme)

def StairsOpAddFillColor(builder, fillColor):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(fillColor), 0)

def AddFillColor(builder, fillColor):
    StairsOpAddFillColor(builder, fillColor)

def StairsOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return StairsOpEnd(builder)

import nhc.rendering.ir._fb.StairTile
try:
    from typing import List
except:
    pass

class StairsOpT(object):

    # StairsOpT
    def __init__(
        self,
        stairs = None,
        theme = None,
        fillColor = None,
    ):
        self.stairs = stairs  # type: Optional[List[nhc.rendering.ir._fb.StairTile.StairTileT]]
        self.theme = theme  # type: Optional[str]
        self.fillColor = fillColor  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        stairsOp = StairsOp()
        stairsOp.Init(buf, pos)
        return cls.InitFromObj(stairsOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, stairsOp):
        x = StairsOpT()
        x._UnPack(stairsOp)
        return x

    # StairsOpT
    def _UnPack(self, stairsOp):
        if stairsOp is None:
            return
        if not stairsOp.StairsIsNone():
            self.stairs = []
            for i in range(stairsOp.StairsLength()):
                if stairsOp.Stairs(i) is None:
                    self.stairs.append(None)
                else:
                    stairTile_ = nhc.rendering.ir._fb.StairTile.StairTileT.InitFromObj(stairsOp.Stairs(i))
                    self.stairs.append(stairTile_)
        self.theme = stairsOp.Theme()
        self.fillColor = stairsOp.FillColor()

    # StairsOpT
    def Pack(self, builder):
        if self.stairs is not None:
            StairsOpStartStairsVector(builder, len(self.stairs))
            for i in reversed(range(len(self.stairs))):
                self.stairs[i].Pack(builder)
            stairs = builder.EndVector()
        if self.theme is not None:
            theme = builder.CreateString(self.theme)
        if self.fillColor is not None:
            fillColor = builder.CreateString(self.fillColor)
        StairsOpStart(builder)
        if self.stairs is not None:
            StairsOpAddStairs(builder, stairs)
        if self.theme is not None:
            StairsOpAddTheme(builder, theme)
        if self.fillColor is not None:
            StairsOpAddFillColor(builder, fillColor)
        stairsOp = StairsOpEnd(builder)
        return stairsOp
