# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StrokeOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StrokeOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStrokeOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StrokeOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x35", size_prefixed=size_prefixed)

    # StrokeOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StrokeOp
    def RegionRef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # StrokeOp
    def Outline(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from nhc.rendering.ir._fb.Outline import Outline
            obj = Outline()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StrokeOp
    def WallMaterial(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from nhc.rendering.ir._fb.WallMaterial import WallMaterial
            obj = WallMaterial()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StrokeOp
    def Cuts(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from nhc.rendering.ir._fb.Cut import Cut
            obj = Cut()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StrokeOp
    def CutsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StrokeOp
    def CutsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def StrokeOpStart(builder):
    builder.StartObject(4)

def Start(builder):
    StrokeOpStart(builder)

def StrokeOpAddRegionRef(builder, regionRef):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(regionRef), 0)

def AddRegionRef(builder, regionRef):
    StrokeOpAddRegionRef(builder, regionRef)

def StrokeOpAddOutline(builder, outline):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(outline), 0)

def AddOutline(builder, outline):
    StrokeOpAddOutline(builder, outline)

def StrokeOpAddWallMaterial(builder, wallMaterial):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(wallMaterial), 0)

def AddWallMaterial(builder, wallMaterial):
    StrokeOpAddWallMaterial(builder, wallMaterial)

def StrokeOpAddCuts(builder, cuts):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(cuts), 0)

def AddCuts(builder, cuts):
    StrokeOpAddCuts(builder, cuts)

def StrokeOpStartCutsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCutsVector(builder, numElems):
    return StrokeOpStartCutsVector(builder, numElems)

def StrokeOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return StrokeOpEnd(builder)

import nhc.rendering.ir._fb.Cut
import nhc.rendering.ir._fb.Outline
import nhc.rendering.ir._fb.WallMaterial
try:
    from typing import List, Optional
except:
    pass

class StrokeOpT(object):

    # StrokeOpT
    def __init__(
        self,
        regionRef = None,
        outline = None,
        wallMaterial = None,
        cuts = None,
    ):
        self.regionRef = regionRef  # type: Optional[str]
        self.outline = outline  # type: Optional[nhc.rendering.ir._fb.Outline.OutlineT]
        self.wallMaterial = wallMaterial  # type: Optional[nhc.rendering.ir._fb.WallMaterial.WallMaterialT]
        self.cuts = cuts  # type: Optional[List[nhc.rendering.ir._fb.Cut.CutT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        strokeOp = StrokeOp()
        strokeOp.Init(buf, pos)
        return cls.InitFromObj(strokeOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, strokeOp):
        x = StrokeOpT()
        x._UnPack(strokeOp)
        return x

    # StrokeOpT
    def _UnPack(self, strokeOp):
        if strokeOp is None:
            return
        self.regionRef = strokeOp.RegionRef()
        if strokeOp.Outline() is not None:
            self.outline = nhc.rendering.ir._fb.Outline.OutlineT.InitFromObj(strokeOp.Outline())
        if strokeOp.WallMaterial() is not None:
            self.wallMaterial = nhc.rendering.ir._fb.WallMaterial.WallMaterialT.InitFromObj(strokeOp.WallMaterial())
        if not strokeOp.CutsIsNone():
            self.cuts = []
            for i in range(strokeOp.CutsLength()):
                if strokeOp.Cuts(i) is None:
                    self.cuts.append(None)
                else:
                    cut_ = nhc.rendering.ir._fb.Cut.CutT.InitFromObj(strokeOp.Cuts(i))
                    self.cuts.append(cut_)

    # StrokeOpT
    def Pack(self, builder):
        if self.regionRef is not None:
            regionRef = builder.CreateString(self.regionRef)
        if self.outline is not None:
            outline = self.outline.Pack(builder)
        if self.wallMaterial is not None:
            wallMaterial = self.wallMaterial.Pack(builder)
        if self.cuts is not None:
            cutslist = []
            for i in range(len(self.cuts)):
                cutslist.append(self.cuts[i].Pack(builder))
            StrokeOpStartCutsVector(builder, len(self.cuts))
            for i in reversed(range(len(self.cuts))):
                builder.PrependUOffsetTRelative(cutslist[i])
            cuts = builder.EndVector()
        StrokeOpStart(builder)
        if self.regionRef is not None:
            StrokeOpAddRegionRef(builder, regionRef)
        if self.outline is not None:
            StrokeOpAddOutline(builder, outline)
        if self.wallMaterial is not None:
            StrokeOpAddWallMaterial(builder, wallMaterial)
        if self.cuts is not None:
            StrokeOpAddCuts(builder, cuts)
        strokeOp = StrokeOpEnd(builder)
        return strokeOp
