# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TerrainDetailTile(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 12

    # TerrainDetailTile
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TerrainDetailTile
    def X(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # TerrainDetailTile
    def Y(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # TerrainDetailTile
    def Kind(self): return self._tab.Get(flatbuffers.number_types.Int8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # TerrainDetailTile
    def IsCorridor(self): return self._tab.Get(flatbuffers.number_types.BoolFlags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(9))
    # TerrainDetailTile
    def Pad0(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(10))
    # TerrainDetailTile
    def Pad1(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(11))

def CreateTerrainDetailTile(builder, x, y, kind, isCorridor, pad0, pad1):
    builder.Prep(4, 12)
    builder.PrependUint8(pad1)
    builder.PrependUint8(pad0)
    builder.PrependBool(isCorridor)
    builder.PrependInt8(kind)
    builder.PrependInt32(y)
    builder.PrependInt32(x)
    return builder.Offset()


class TerrainDetailTileT(object):

    # TerrainDetailTileT
    def __init__(
        self,
        x = 0,
        y = 0,
        kind = 0,
        isCorridor = False,
        pad0 = 0,
        pad1 = 0,
    ):
        self.x = x  # type: int
        self.y = y  # type: int
        self.kind = kind  # type: int
        self.isCorridor = isCorridor  # type: bool
        self.pad0 = pad0  # type: int
        self.pad1 = pad1  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        terrainDetailTile = TerrainDetailTile()
        terrainDetailTile.Init(buf, pos)
        return cls.InitFromObj(terrainDetailTile)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, terrainDetailTile):
        x = TerrainDetailTileT()
        x._UnPack(terrainDetailTile)
        return x

    # TerrainDetailTileT
    def _UnPack(self, terrainDetailTile):
        if terrainDetailTile is None:
            return
        self.x = terrainDetailTile.X()
        self.y = terrainDetailTile.Y()
        self.kind = terrainDetailTile.Kind()
        self.isCorridor = terrainDetailTile.IsCorridor()
        self.pad0 = terrainDetailTile.Pad0()
        self.pad1 = terrainDetailTile.Pad1()

    # TerrainDetailTileT
    def Pack(self, builder):
        return CreateTerrainDetailTile(builder, self.x, self.y, self.kind, self.isCorridor, self.pad0, self.pad1)
