# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TerrainDetailOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TerrainDetailOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTerrainDetailOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TerrainDetailOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x46", size_prefixed=size_prefixed)

    # TerrainDetailOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TerrainDetailOp
    def Tiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            from nhc.rendering.ir._fb.TerrainDetailTile import TerrainDetailTile
            obj = TerrainDetailTile()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TerrainDetailOp
    def TilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TerrainDetailOp
    def TilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # TerrainDetailOp
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TerrainDetailOp
    def Theme(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TerrainDetailOp
    def ClipRegion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TerrainDetailOp
    def RoomGroups(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # TerrainDetailOp
    def RoomGroupsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TerrainDetailOp
    def RoomGroupsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # TerrainDetailOp
    def CorridorGroups(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # TerrainDetailOp
    def CorridorGroupsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TerrainDetailOp
    def CorridorGroupsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def TerrainDetailOpStart(builder):
    builder.StartObject(6)

def Start(builder):
    TerrainDetailOpStart(builder)

def TerrainDetailOpAddTiles(builder, tiles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tiles), 0)

def AddTiles(builder, tiles):
    TerrainDetailOpAddTiles(builder, tiles)

def TerrainDetailOpStartTilesVector(builder, numElems):
    return builder.StartVector(12, numElems, 4)

def StartTilesVector(builder, numElems):
    return TerrainDetailOpStartTilesVector(builder, numElems)

def TerrainDetailOpAddSeed(builder, seed):
    builder.PrependUint64Slot(1, seed, 0)

def AddSeed(builder, seed):
    TerrainDetailOpAddSeed(builder, seed)

def TerrainDetailOpAddTheme(builder, theme):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(theme), 0)

def AddTheme(builder, theme):
    TerrainDetailOpAddTheme(builder, theme)

def TerrainDetailOpAddClipRegion(builder, clipRegion):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(clipRegion), 0)

def AddClipRegion(builder, clipRegion):
    TerrainDetailOpAddClipRegion(builder, clipRegion)

def TerrainDetailOpAddRoomGroups(builder, roomGroups):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(roomGroups), 0)

def AddRoomGroups(builder, roomGroups):
    TerrainDetailOpAddRoomGroups(builder, roomGroups)

def TerrainDetailOpStartRoomGroupsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRoomGroupsVector(builder, numElems):
    return TerrainDetailOpStartRoomGroupsVector(builder, numElems)

def TerrainDetailOpAddCorridorGroups(builder, corridorGroups):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(corridorGroups), 0)

def AddCorridorGroups(builder, corridorGroups):
    TerrainDetailOpAddCorridorGroups(builder, corridorGroups)

def TerrainDetailOpStartCorridorGroupsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCorridorGroupsVector(builder, numElems):
    return TerrainDetailOpStartCorridorGroupsVector(builder, numElems)

def TerrainDetailOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return TerrainDetailOpEnd(builder)

import nhc.rendering.ir._fb.TerrainDetailTile
try:
    from typing import List
except:
    pass

class TerrainDetailOpT(object):

    # TerrainDetailOpT
    def __init__(
        self,
        tiles = None,
        seed = 0,
        theme = None,
        clipRegion = None,
        roomGroups = None,
        corridorGroups = None,
    ):
        self.tiles = tiles  # type: Optional[List[nhc.rendering.ir._fb.TerrainDetailTile.TerrainDetailTileT]]
        self.seed = seed  # type: int
        self.theme = theme  # type: Optional[str]
        self.clipRegion = clipRegion  # type: Optional[str]
        self.roomGroups = roomGroups  # type: Optional[List[Optional[str]]]
        self.corridorGroups = corridorGroups  # type: Optional[List[Optional[str]]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        terrainDetailOp = TerrainDetailOp()
        terrainDetailOp.Init(buf, pos)
        return cls.InitFromObj(terrainDetailOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, terrainDetailOp):
        x = TerrainDetailOpT()
        x._UnPack(terrainDetailOp)
        return x

    # TerrainDetailOpT
    def _UnPack(self, terrainDetailOp):
        if terrainDetailOp is None:
            return
        if not terrainDetailOp.TilesIsNone():
            self.tiles = []
            for i in range(terrainDetailOp.TilesLength()):
                if terrainDetailOp.Tiles(i) is None:
                    self.tiles.append(None)
                else:
                    terrainDetailTile_ = nhc.rendering.ir._fb.TerrainDetailTile.TerrainDetailTileT.InitFromObj(terrainDetailOp.Tiles(i))
                    self.tiles.append(terrainDetailTile_)
        self.seed = terrainDetailOp.Seed()
        self.theme = terrainDetailOp.Theme()
        self.clipRegion = terrainDetailOp.ClipRegion()
        if not terrainDetailOp.RoomGroupsIsNone():
            self.roomGroups = []
            for i in range(terrainDetailOp.RoomGroupsLength()):
                self.roomGroups.append(terrainDetailOp.RoomGroups(i))
        if not terrainDetailOp.CorridorGroupsIsNone():
            self.corridorGroups = []
            for i in range(terrainDetailOp.CorridorGroupsLength()):
                self.corridorGroups.append(terrainDetailOp.CorridorGroups(i))

    # TerrainDetailOpT
    def Pack(self, builder):
        if self.tiles is not None:
            TerrainDetailOpStartTilesVector(builder, len(self.tiles))
            for i in reversed(range(len(self.tiles))):
                self.tiles[i].Pack(builder)
            tiles = builder.EndVector()
        if self.theme is not None:
            theme = builder.CreateString(self.theme)
        if self.clipRegion is not None:
            clipRegion = builder.CreateString(self.clipRegion)
        if self.roomGroups is not None:
            roomGroupslist = []
            for i in range(len(self.roomGroups)):
                roomGroupslist.append(builder.CreateString(self.roomGroups[i]))
            TerrainDetailOpStartRoomGroupsVector(builder, len(self.roomGroups))
            for i in reversed(range(len(self.roomGroups))):
                builder.PrependUOffsetTRelative(roomGroupslist[i])
            roomGroups = builder.EndVector()
        if self.corridorGroups is not None:
            corridorGroupslist = []
            for i in range(len(self.corridorGroups)):
                corridorGroupslist.append(builder.CreateString(self.corridorGroups[i]))
            TerrainDetailOpStartCorridorGroupsVector(builder, len(self.corridorGroups))
            for i in reversed(range(len(self.corridorGroups))):
                builder.PrependUOffsetTRelative(corridorGroupslist[i])
            corridorGroups = builder.EndVector()
        TerrainDetailOpStart(builder)
        if self.tiles is not None:
            TerrainDetailOpAddTiles(builder, tiles)
        TerrainDetailOpAddSeed(builder, self.seed)
        if self.theme is not None:
            TerrainDetailOpAddTheme(builder, theme)
        if self.clipRegion is not None:
            TerrainDetailOpAddClipRegion(builder, clipRegion)
        if self.roomGroups is not None:
            TerrainDetailOpAddRoomGroups(builder, roomGroups)
        if self.corridorGroups is not None:
            TerrainDetailOpAddCorridorGroups(builder, corridorGroups)
        terrainDetailOp = TerrainDetailOpEnd(builder)
        return terrainDetailOp
