# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ThematicDetailOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ThematicDetailOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsThematicDetailOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ThematicDetailOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x46", size_prefixed=size_prefixed)

    # ThematicDetailOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ThematicDetailOp
    def Tiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from nhc.rendering.ir._fb.TileCoord import TileCoord
            obj = TileCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ThematicDetailOp
    def TilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ThematicDetailOp
    def TilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ThematicDetailOp
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ThematicDetailOp
    def Theme(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ThematicDetailOpStart(builder):
    builder.StartObject(3)

def Start(builder):
    ThematicDetailOpStart(builder)

def ThematicDetailOpAddTiles(builder, tiles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tiles), 0)

def AddTiles(builder, tiles):
    ThematicDetailOpAddTiles(builder, tiles)

def ThematicDetailOpStartTilesVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartTilesVector(builder, numElems):
    return ThematicDetailOpStartTilesVector(builder, numElems)

def ThematicDetailOpAddSeed(builder, seed):
    builder.PrependUint64Slot(1, seed, 0)

def AddSeed(builder, seed):
    ThematicDetailOpAddSeed(builder, seed)

def ThematicDetailOpAddTheme(builder, theme):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(theme), 0)

def AddTheme(builder, theme):
    ThematicDetailOpAddTheme(builder, theme)

def ThematicDetailOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return ThematicDetailOpEnd(builder)

import nhc.rendering.ir._fb.TileCoord
try:
    from typing import List
except:
    pass

class ThematicDetailOpT(object):

    # ThematicDetailOpT
    def __init__(
        self,
        tiles = None,
        seed = 0,
        theme = None,
    ):
        self.tiles = tiles  # type: Optional[List[nhc.rendering.ir._fb.TileCoord.TileCoordT]]
        self.seed = seed  # type: int
        self.theme = theme  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        thematicDetailOp = ThematicDetailOp()
        thematicDetailOp.Init(buf, pos)
        return cls.InitFromObj(thematicDetailOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, thematicDetailOp):
        x = ThematicDetailOpT()
        x._UnPack(thematicDetailOp)
        return x

    # ThematicDetailOpT
    def _UnPack(self, thematicDetailOp):
        if thematicDetailOp is None:
            return
        if not thematicDetailOp.TilesIsNone():
            self.tiles = []
            for i in range(thematicDetailOp.TilesLength()):
                if thematicDetailOp.Tiles(i) is None:
                    self.tiles.append(None)
                else:
                    tileCoord_ = nhc.rendering.ir._fb.TileCoord.TileCoordT.InitFromObj(thematicDetailOp.Tiles(i))
                    self.tiles.append(tileCoord_)
        self.seed = thematicDetailOp.Seed()
        self.theme = thematicDetailOp.Theme()

    # ThematicDetailOpT
    def Pack(self, builder):
        if self.tiles is not None:
            ThematicDetailOpStartTilesVector(builder, len(self.tiles))
            for i in reversed(range(len(self.tiles))):
                self.tiles[i].Pack(builder)
            tiles = builder.EndVector()
        if self.theme is not None:
            theme = builder.CreateString(self.theme)
        ThematicDetailOpStart(builder)
        if self.tiles is not None:
            ThematicDetailOpAddTiles(builder, tiles)
        ThematicDetailOpAddSeed(builder, self.seed)
        if self.theme is not None:
            ThematicDetailOpAddTheme(builder, theme)
        thematicDetailOp = ThematicDetailOpEnd(builder)
        return thematicDetailOp
