# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class V5Anchor(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # V5Anchor
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # V5Anchor
    def X(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # V5Anchor
    def Y(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # V5Anchor
    def Variant(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # V5Anchor
    def Orientation(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(9))
    # V5Anchor
    def Scale(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(10))
    # V5Anchor
    def Pad0(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(11))
    # V5Anchor
    def GroupId(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateV5Anchor(builder, x, y, variant, orientation, scale, pad0, groupId):
    builder.Prep(4, 16)
    builder.PrependUint32(groupId)
    builder.PrependUint8(pad0)
    builder.PrependUint8(scale)
    builder.PrependUint8(orientation)
    builder.PrependUint8(variant)
    builder.PrependInt32(y)
    builder.PrependInt32(x)
    return builder.Offset()


class V5AnchorT(object):

    # V5AnchorT
    def __init__(
        self,
        x = 0,
        y = 0,
        variant = 0,
        orientation = 0,
        scale = 0,
        pad0 = 0,
        groupId = 0,
    ):
        self.x = x  # type: int
        self.y = y  # type: int
        self.variant = variant  # type: int
        self.orientation = orientation  # type: int
        self.scale = scale  # type: int
        self.pad0 = pad0  # type: int
        self.groupId = groupId  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        v5Anchor = V5Anchor()
        v5Anchor.Init(buf, pos)
        return cls.InitFromObj(v5Anchor)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, v5Anchor):
        x = V5AnchorT()
        x._UnPack(v5Anchor)
        return x

    # V5AnchorT
    def _UnPack(self, v5Anchor):
        if v5Anchor is None:
            return
        self.x = v5Anchor.X()
        self.y = v5Anchor.Y()
        self.variant = v5Anchor.Variant()
        self.orientation = v5Anchor.Orientation()
        self.scale = v5Anchor.Scale()
        self.pad0 = v5Anchor.Pad0()
        self.groupId = v5Anchor.GroupId()

    # V5AnchorT
    def Pack(self, builder):
        return CreateV5Anchor(builder, self.x, self.y, self.variant, self.orientation, self.scale, self.pad0, self.groupId)
