# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class V5FixtureOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = V5FixtureOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsV5FixtureOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def V5FixtureOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x34", size_prefixed=size_prefixed)

    # V5FixtureOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # V5FixtureOp
    def RegionRef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # V5FixtureOp
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # V5FixtureOp
    def Anchors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            from nhc.rendering.ir._fb.V5Anchor import V5Anchor
            obj = V5Anchor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # V5FixtureOp
    def AnchorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # V5FixtureOp
    def AnchorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # V5FixtureOp
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def V5FixtureOpStart(builder):
    builder.StartObject(4)

def Start(builder):
    V5FixtureOpStart(builder)

def V5FixtureOpAddRegionRef(builder, regionRef):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(regionRef), 0)

def AddRegionRef(builder, regionRef):
    V5FixtureOpAddRegionRef(builder, regionRef)

def V5FixtureOpAddKind(builder, kind):
    builder.PrependUint8Slot(1, kind, 0)

def AddKind(builder, kind):
    V5FixtureOpAddKind(builder, kind)

def V5FixtureOpAddAnchors(builder, anchors):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(anchors), 0)

def AddAnchors(builder, anchors):
    V5FixtureOpAddAnchors(builder, anchors)

def V5FixtureOpStartAnchorsVector(builder, numElems):
    return builder.StartVector(16, numElems, 4)

def StartAnchorsVector(builder, numElems):
    return V5FixtureOpStartAnchorsVector(builder, numElems)

def V5FixtureOpAddSeed(builder, seed):
    builder.PrependUint64Slot(3, seed, 0)

def AddSeed(builder, seed):
    V5FixtureOpAddSeed(builder, seed)

def V5FixtureOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return V5FixtureOpEnd(builder)

import nhc.rendering.ir._fb.V5Anchor
try:
    from typing import List
except:
    pass

class V5FixtureOpT(object):

    # V5FixtureOpT
    def __init__(
        self,
        regionRef = None,
        kind = 0,
        anchors = None,
        seed = 0,
    ):
        self.regionRef = regionRef  # type: Optional[str]
        self.kind = kind  # type: int
        self.anchors = anchors  # type: Optional[List[nhc.rendering.ir._fb.V5Anchor.V5AnchorT]]
        self.seed = seed  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        v5FixtureOp = V5FixtureOp()
        v5FixtureOp.Init(buf, pos)
        return cls.InitFromObj(v5FixtureOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, v5FixtureOp):
        x = V5FixtureOpT()
        x._UnPack(v5FixtureOp)
        return x

    # V5FixtureOpT
    def _UnPack(self, v5FixtureOp):
        if v5FixtureOp is None:
            return
        self.regionRef = v5FixtureOp.RegionRef()
        self.kind = v5FixtureOp.Kind()
        if not v5FixtureOp.AnchorsIsNone():
            self.anchors = []
            for i in range(v5FixtureOp.AnchorsLength()):
                if v5FixtureOp.Anchors(i) is None:
                    self.anchors.append(None)
                else:
                    v5Anchor_ = nhc.rendering.ir._fb.V5Anchor.V5AnchorT.InitFromObj(v5FixtureOp.Anchors(i))
                    self.anchors.append(v5Anchor_)
        self.seed = v5FixtureOp.Seed()

    # V5FixtureOpT
    def Pack(self, builder):
        if self.regionRef is not None:
            regionRef = builder.CreateString(self.regionRef)
        if self.anchors is not None:
            V5FixtureOpStartAnchorsVector(builder, len(self.anchors))
            for i in reversed(range(len(self.anchors))):
                self.anchors[i].Pack(builder)
            anchors = builder.EndVector()
        V5FixtureOpStart(builder)
        if self.regionRef is not None:
            V5FixtureOpAddRegionRef(builder, regionRef)
        V5FixtureOpAddKind(builder, self.kind)
        if self.anchors is not None:
            V5FixtureOpAddAnchors(builder, anchors)
        V5FixtureOpAddSeed(builder, self.seed)
        v5FixtureOp = V5FixtureOpEnd(builder)
        return v5FixtureOp
