# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

class V5FixtureKind(object):
    Web = 0
    Skull = 1
    Bone = 2
    LooseStone = 3
    Tree = 4
    Bush = 5
    Well = 6
    Fountain = 7
    Stair = 8
    Gravestone = 9
    Sign = 10
    Mushroom = 11
