# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class V5OpEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = V5OpEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsV5OpEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def V5OpEntryBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x34", size_prefixed=size_prefixed)

    # V5OpEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # V5OpEntry
    def OpType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # V5OpEntry
    def Op(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def V5OpEntryStart(builder):
    builder.StartObject(2)

def Start(builder):
    V5OpEntryStart(builder)

def V5OpEntryAddOpType(builder, opType):
    builder.PrependUint8Slot(0, opType, 0)

def AddOpType(builder, opType):
    V5OpEntryAddOpType(builder, opType)

def V5OpEntryAddOp(builder, op):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(op), 0)

def AddOp(builder, op):
    V5OpEntryAddOp(builder, op)

def V5OpEntryEnd(builder):
    return builder.EndObject()

def End(builder):
    return V5OpEntryEnd(builder)

import nhc.rendering.ir._fb.ShadowOp
import nhc.rendering.ir._fb.V5FixtureOp
import nhc.rendering.ir._fb.V5HatchOp
import nhc.rendering.ir._fb.V5Op
import nhc.rendering.ir._fb.V5PaintOp
import nhc.rendering.ir._fb.V5PathOp
import nhc.rendering.ir._fb.V5RoofOp
import nhc.rendering.ir._fb.V5StampOp
import nhc.rendering.ir._fb.V5StrokeOp
try:
    from typing import Union
except:
    pass

class V5OpEntryT(object):

    # V5OpEntryT
    def __init__(
        self,
        opType = 0,
        op = None,
    ):
        self.opType = opType  # type: int
        self.op = op  # type: Union[None, 'nhc.rendering.ir._fb.V5PaintOp.V5PaintOpT', 'nhc.rendering.ir._fb.V5StampOp.V5StampOpT', 'nhc.rendering.ir._fb.V5PathOp.V5PathOpT', 'nhc.rendering.ir._fb.V5FixtureOp.V5FixtureOpT', 'nhc.rendering.ir._fb.V5StrokeOp.V5StrokeOpT', 'nhc.rendering.ir._fb.ShadowOp.ShadowOpT', 'nhc.rendering.ir._fb.V5HatchOp.V5HatchOpT', 'nhc.rendering.ir._fb.V5RoofOp.V5RoofOpT']

    @classmethod
    def InitFromBuf(cls, buf, pos):
        v5OpEntry = V5OpEntry()
        v5OpEntry.Init(buf, pos)
        return cls.InitFromObj(v5OpEntry)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, v5OpEntry):
        x = V5OpEntryT()
        x._UnPack(v5OpEntry)
        return x

    # V5OpEntryT
    def _UnPack(self, v5OpEntry):
        if v5OpEntry is None:
            return
        self.opType = v5OpEntry.OpType()
        self.op = nhc.rendering.ir._fb.V5Op.V5OpCreator(self.opType, v5OpEntry.Op())

    # V5OpEntryT
    def Pack(self, builder):
        if self.op is not None:
            op = self.op.Pack(builder)
        V5OpEntryStart(builder)
        V5OpEntryAddOpType(builder, self.opType)
        if self.op is not None:
            V5OpEntryAddOp(builder, op)
        v5OpEntry = V5OpEntryEnd(builder)
        return v5OpEntry
