# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class V5PaintOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = V5PaintOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsV5PaintOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def V5PaintOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x34", size_prefixed=size_prefixed)

    # V5PaintOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # V5PaintOp
    def RegionRef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # V5PaintOp
    def SubtractRegionRefs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # V5PaintOp
    def SubtractRegionRefsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # V5PaintOp
    def SubtractRegionRefsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # V5PaintOp
    def Material(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from nhc.rendering.ir._fb.V5Material import V5Material
            obj = V5Material()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def V5PaintOpStart(builder):
    builder.StartObject(3)

def Start(builder):
    V5PaintOpStart(builder)

def V5PaintOpAddRegionRef(builder, regionRef):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(regionRef), 0)

def AddRegionRef(builder, regionRef):
    V5PaintOpAddRegionRef(builder, regionRef)

def V5PaintOpAddSubtractRegionRefs(builder, subtractRegionRefs):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(subtractRegionRefs), 0)

def AddSubtractRegionRefs(builder, subtractRegionRefs):
    V5PaintOpAddSubtractRegionRefs(builder, subtractRegionRefs)

def V5PaintOpStartSubtractRegionRefsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSubtractRegionRefsVector(builder, numElems):
    return V5PaintOpStartSubtractRegionRefsVector(builder, numElems)

def V5PaintOpAddMaterial(builder, material):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(material), 0)

def AddMaterial(builder, material):
    V5PaintOpAddMaterial(builder, material)

def V5PaintOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return V5PaintOpEnd(builder)

import nhc.rendering.ir._fb.V5Material
try:
    from typing import List, Optional
except:
    pass

class V5PaintOpT(object):

    # V5PaintOpT
    def __init__(
        self,
        regionRef = None,
        subtractRegionRefs = None,
        material = None,
    ):
        self.regionRef = regionRef  # type: Optional[str]
        self.subtractRegionRefs = subtractRegionRefs  # type: Optional[List[Optional[str]]]
        self.material = material  # type: Optional[nhc.rendering.ir._fb.V5Material.V5MaterialT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        v5PaintOp = V5PaintOp()
        v5PaintOp.Init(buf, pos)
        return cls.InitFromObj(v5PaintOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, v5PaintOp):
        x = V5PaintOpT()
        x._UnPack(v5PaintOp)
        return x

    # V5PaintOpT
    def _UnPack(self, v5PaintOp):
        if v5PaintOp is None:
            return
        self.regionRef = v5PaintOp.RegionRef()
        if not v5PaintOp.SubtractRegionRefsIsNone():
            self.subtractRegionRefs = []
            for i in range(v5PaintOp.SubtractRegionRefsLength()):
                self.subtractRegionRefs.append(v5PaintOp.SubtractRegionRefs(i))
        if v5PaintOp.Material() is not None:
            self.material = nhc.rendering.ir._fb.V5Material.V5MaterialT.InitFromObj(v5PaintOp.Material())

    # V5PaintOpT
    def Pack(self, builder):
        if self.regionRef is not None:
            regionRef = builder.CreateString(self.regionRef)
        if self.subtractRegionRefs is not None:
            subtractRegionRefslist = []
            for i in range(len(self.subtractRegionRefs)):
                subtractRegionRefslist.append(builder.CreateString(self.subtractRegionRefs[i]))
            V5PaintOpStartSubtractRegionRefsVector(builder, len(self.subtractRegionRefs))
            for i in reversed(range(len(self.subtractRegionRefs))):
                builder.PrependUOffsetTRelative(subtractRegionRefslist[i])
            subtractRegionRefs = builder.EndVector()
        if self.material is not None:
            material = self.material.Pack(builder)
        V5PaintOpStart(builder)
        if self.regionRef is not None:
            V5PaintOpAddRegionRef(builder, regionRef)
        if self.subtractRegionRefs is not None:
            V5PaintOpAddSubtractRegionRefs(builder, subtractRegionRefs)
        if self.material is not None:
            V5PaintOpAddMaterial(builder, material)
        v5PaintOp = V5PaintOpEnd(builder)
        return v5PaintOp
