# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class V5RoofOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = V5RoofOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsV5RoofOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def V5RoofOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x34", size_prefixed=size_prefixed)

    # V5RoofOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # V5RoofOp
    def RegionRef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # V5RoofOp
    def Style(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # V5RoofOp
    def Tone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # V5RoofOp
    def Tint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # V5RoofOp
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def V5RoofOpStart(builder):
    builder.StartObject(5)

def Start(builder):
    V5RoofOpStart(builder)

def V5RoofOpAddRegionRef(builder, regionRef):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(regionRef), 0)

def AddRegionRef(builder, regionRef):
    V5RoofOpAddRegionRef(builder, regionRef)

def V5RoofOpAddStyle(builder, style):
    builder.PrependUint8Slot(1, style, 0)

def AddStyle(builder, style):
    V5RoofOpAddStyle(builder, style)

def V5RoofOpAddTone(builder, tone):
    builder.PrependUint8Slot(2, tone, 0)

def AddTone(builder, tone):
    V5RoofOpAddTone(builder, tone)

def V5RoofOpAddTint(builder, tint):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(tint), 0)

def AddTint(builder, tint):
    V5RoofOpAddTint(builder, tint)

def V5RoofOpAddSeed(builder, seed):
    builder.PrependUint64Slot(4, seed, 0)

def AddSeed(builder, seed):
    V5RoofOpAddSeed(builder, seed)

def V5RoofOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return V5RoofOpEnd(builder)


class V5RoofOpT(object):

    # V5RoofOpT
    def __init__(
        self,
        regionRef = None,
        style = 0,
        tone = 0,
        tint = None,
        seed = 0,
    ):
        self.regionRef = regionRef  # type: Optional[str]
        self.style = style  # type: int
        self.tone = tone  # type: int
        self.tint = tint  # type: Optional[str]
        self.seed = seed  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        v5RoofOp = V5RoofOp()
        v5RoofOp.Init(buf, pos)
        return cls.InitFromObj(v5RoofOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, v5RoofOp):
        x = V5RoofOpT()
        x._UnPack(v5RoofOp)
        return x

    # V5RoofOpT
    def _UnPack(self, v5RoofOp):
        if v5RoofOp is None:
            return
        self.regionRef = v5RoofOp.RegionRef()
        self.style = v5RoofOp.Style()
        self.tone = v5RoofOp.Tone()
        self.tint = v5RoofOp.Tint()
        self.seed = v5RoofOp.Seed()

    # V5RoofOpT
    def Pack(self, builder):
        if self.regionRef is not None:
            regionRef = builder.CreateString(self.regionRef)
        if self.tint is not None:
            tint = builder.CreateString(self.tint)
        V5RoofOpStart(builder)
        if self.regionRef is not None:
            V5RoofOpAddRegionRef(builder, regionRef)
        V5RoofOpAddStyle(builder, self.style)
        V5RoofOpAddTone(builder, self.tone)
        if self.tint is not None:
            V5RoofOpAddTint(builder, tint)
        V5RoofOpAddSeed(builder, self.seed)
        v5RoofOp = V5RoofOpEnd(builder)
        return v5RoofOp
