# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class V5StampOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = V5StampOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsV5StampOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def V5StampOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x34", size_prefixed=size_prefixed)

    # V5StampOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # V5StampOp
    def RegionRef(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # V5StampOp
    def SubtractRegionRefs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # V5StampOp
    def SubtractRegionRefsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # V5StampOp
    def SubtractRegionRefsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # V5StampOp
    def DecoratorMask(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # V5StampOp
    def Density(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 128

    # V5StampOp
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def V5StampOpStart(builder):
    builder.StartObject(5)

def Start(builder):
    V5StampOpStart(builder)

def V5StampOpAddRegionRef(builder, regionRef):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(regionRef), 0)

def AddRegionRef(builder, regionRef):
    V5StampOpAddRegionRef(builder, regionRef)

def V5StampOpAddSubtractRegionRefs(builder, subtractRegionRefs):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(subtractRegionRefs), 0)

def AddSubtractRegionRefs(builder, subtractRegionRefs):
    V5StampOpAddSubtractRegionRefs(builder, subtractRegionRefs)

def V5StampOpStartSubtractRegionRefsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSubtractRegionRefsVector(builder, numElems):
    return V5StampOpStartSubtractRegionRefsVector(builder, numElems)

def V5StampOpAddDecoratorMask(builder, decoratorMask):
    builder.PrependUint32Slot(2, decoratorMask, 0)

def AddDecoratorMask(builder, decoratorMask):
    V5StampOpAddDecoratorMask(builder, decoratorMask)

def V5StampOpAddDensity(builder, density):
    builder.PrependUint8Slot(3, density, 128)

def AddDensity(builder, density):
    V5StampOpAddDensity(builder, density)

def V5StampOpAddSeed(builder, seed):
    builder.PrependUint64Slot(4, seed, 0)

def AddSeed(builder, seed):
    V5StampOpAddSeed(builder, seed)

def V5StampOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return V5StampOpEnd(builder)

try:
    from typing import List
except:
    pass

class V5StampOpT(object):

    # V5StampOpT
    def __init__(
        self,
        regionRef = None,
        subtractRegionRefs = None,
        decoratorMask = 0,
        density = 128,
        seed = 0,
    ):
        self.regionRef = regionRef  # type: Optional[str]
        self.subtractRegionRefs = subtractRegionRefs  # type: Optional[List[Optional[str]]]
        self.decoratorMask = decoratorMask  # type: int
        self.density = density  # type: int
        self.seed = seed  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        v5StampOp = V5StampOp()
        v5StampOp.Init(buf, pos)
        return cls.InitFromObj(v5StampOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, v5StampOp):
        x = V5StampOpT()
        x._UnPack(v5StampOp)
        return x

    # V5StampOpT
    def _UnPack(self, v5StampOp):
        if v5StampOp is None:
            return
        self.regionRef = v5StampOp.RegionRef()
        if not v5StampOp.SubtractRegionRefsIsNone():
            self.subtractRegionRefs = []
            for i in range(v5StampOp.SubtractRegionRefsLength()):
                self.subtractRegionRefs.append(v5StampOp.SubtractRegionRefs(i))
        self.decoratorMask = v5StampOp.DecoratorMask()
        self.density = v5StampOp.Density()
        self.seed = v5StampOp.Seed()

    # V5StampOpT
    def Pack(self, builder):
        if self.regionRef is not None:
            regionRef = builder.CreateString(self.regionRef)
        if self.subtractRegionRefs is not None:
            subtractRegionRefslist = []
            for i in range(len(self.subtractRegionRefs)):
                subtractRegionRefslist.append(builder.CreateString(self.subtractRegionRefs[i]))
            V5StampOpStartSubtractRegionRefsVector(builder, len(self.subtractRegionRefs))
            for i in reversed(range(len(self.subtractRegionRefs))):
                builder.PrependUOffsetTRelative(subtractRegionRefslist[i])
            subtractRegionRefs = builder.EndVector()
        V5StampOpStart(builder)
        if self.regionRef is not None:
            V5StampOpAddRegionRef(builder, regionRef)
        if self.subtractRegionRefs is not None:
            V5StampOpAddSubtractRegionRefs(builder, subtractRegionRefs)
        V5StampOpAddDecoratorMask(builder, self.decoratorMask)
        V5StampOpAddDensity(builder, self.density)
        V5StampOpAddSeed(builder, self.seed)
        v5StampOp = V5StampOpEnd(builder)
        return v5StampOp
