# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class V5WallMaterial(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = V5WallMaterial()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsV5WallMaterial(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def V5WallMaterialBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x34", size_prefixed=size_prefixed)

    # V5WallMaterial
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # V5WallMaterial
    def Family(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # V5WallMaterial
    def Style(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # V5WallMaterial
    def Treatment(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # V5WallMaterial
    def CornerStyle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # V5WallMaterial
    def Tone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # V5WallMaterial
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def V5WallMaterialStart(builder):
    builder.StartObject(6)

def Start(builder):
    V5WallMaterialStart(builder)

def V5WallMaterialAddFamily(builder, family):
    builder.PrependUint8Slot(0, family, 0)

def AddFamily(builder, family):
    V5WallMaterialAddFamily(builder, family)

def V5WallMaterialAddStyle(builder, style):
    builder.PrependUint8Slot(1, style, 0)

def AddStyle(builder, style):
    V5WallMaterialAddStyle(builder, style)

def V5WallMaterialAddTreatment(builder, treatment):
    builder.PrependUint8Slot(2, treatment, 0)

def AddTreatment(builder, treatment):
    V5WallMaterialAddTreatment(builder, treatment)

def V5WallMaterialAddCornerStyle(builder, cornerStyle):
    builder.PrependInt8Slot(3, cornerStyle, 0)

def AddCornerStyle(builder, cornerStyle):
    V5WallMaterialAddCornerStyle(builder, cornerStyle)

def V5WallMaterialAddTone(builder, tone):
    builder.PrependUint8Slot(4, tone, 0)

def AddTone(builder, tone):
    V5WallMaterialAddTone(builder, tone)

def V5WallMaterialAddSeed(builder, seed):
    builder.PrependUint64Slot(5, seed, 0)

def AddSeed(builder, seed):
    V5WallMaterialAddSeed(builder, seed)

def V5WallMaterialEnd(builder):
    return builder.EndObject()

def End(builder):
    return V5WallMaterialEnd(builder)


class V5WallMaterialT(object):

    # V5WallMaterialT
    def __init__(
        self,
        family = 0,
        style = 0,
        treatment = 0,
        cornerStyle = 0,
        tone = 0,
        seed = 0,
    ):
        self.family = family  # type: int
        self.style = style  # type: int
        self.treatment = treatment  # type: int
        self.cornerStyle = cornerStyle  # type: int
        self.tone = tone  # type: int
        self.seed = seed  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        v5WallMaterial = V5WallMaterial()
        v5WallMaterial.Init(buf, pos)
        return cls.InitFromObj(v5WallMaterial)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, v5WallMaterial):
        x = V5WallMaterialT()
        x._UnPack(v5WallMaterial)
        return x

    # V5WallMaterialT
    def _UnPack(self, v5WallMaterial):
        if v5WallMaterial is None:
            return
        self.family = v5WallMaterial.Family()
        self.style = v5WallMaterial.Style()
        self.treatment = v5WallMaterial.Treatment()
        self.cornerStyle = v5WallMaterial.CornerStyle()
        self.tone = v5WallMaterial.Tone()
        self.seed = v5WallMaterial.Seed()

    # V5WallMaterialT
    def Pack(self, builder):
        V5WallMaterialStart(builder)
        V5WallMaterialAddFamily(builder, self.family)
        V5WallMaterialAddStyle(builder, self.style)
        V5WallMaterialAddTreatment(builder, self.treatment)
        V5WallMaterialAddCornerStyle(builder, self.cornerStyle)
        V5WallMaterialAddTone(builder, self.tone)
        V5WallMaterialAddSeed(builder, self.seed)
        v5WallMaterial = V5WallMaterialEnd(builder)
        return v5WallMaterial
