# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WallsAndFloorsOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WallsAndFloorsOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWallsAndFloorsOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WallsAndFloorsOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x46", size_prefixed=size_prefixed)

    # WallsAndFloorsOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WallsAndFloorsOp
    def SmoothRoomRegions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # WallsAndFloorsOp
    def SmoothRoomRegionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WallsAndFloorsOp
    def SmoothRoomRegionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # WallsAndFloorsOp
    def RectRooms(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from nhc.rendering.ir._fb.RectRoom import RectRoom
            obj = RectRoom()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WallsAndFloorsOp
    def RectRoomsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WallsAndFloorsOp
    def RectRoomsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # WallsAndFloorsOp
    def CorridorTiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from nhc.rendering.ir._fb.TileCoord import TileCoord
            obj = TileCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WallsAndFloorsOp
    def CorridorTilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WallsAndFloorsOp
    def CorridorTilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # WallsAndFloorsOp
    def CaveRegion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WallsAndFloorsOp
    def WallSegments(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # WallsAndFloorsOp
    def WallSegmentsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WallsAndFloorsOp
    def WallSegmentsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # WallsAndFloorsOp
    def FloorColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WallsAndFloorsOp
    def CaveFloorColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WallsAndFloorsOp
    def WallColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WallsAndFloorsOp
    def WallWidth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # WallsAndFloorsOp
    def BuildingFootprint(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from nhc.rendering.ir._fb.TileCoord import TileCoord
            obj = TileCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WallsAndFloorsOp
    def BuildingFootprintLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WallsAndFloorsOp
    def BuildingFootprintIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

def WallsAndFloorsOpStart(builder):
    builder.StartObject(10)

def Start(builder):
    WallsAndFloorsOpStart(builder)

def WallsAndFloorsOpAddSmoothRoomRegions(builder, smoothRoomRegions):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(smoothRoomRegions), 0)

def AddSmoothRoomRegions(builder, smoothRoomRegions):
    WallsAndFloorsOpAddSmoothRoomRegions(builder, smoothRoomRegions)

def WallsAndFloorsOpStartSmoothRoomRegionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSmoothRoomRegionsVector(builder, numElems):
    return WallsAndFloorsOpStartSmoothRoomRegionsVector(builder, numElems)

def WallsAndFloorsOpAddRectRooms(builder, rectRooms):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(rectRooms), 0)

def AddRectRooms(builder, rectRooms):
    WallsAndFloorsOpAddRectRooms(builder, rectRooms)

def WallsAndFloorsOpStartRectRoomsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRectRoomsVector(builder, numElems):
    return WallsAndFloorsOpStartRectRoomsVector(builder, numElems)

def WallsAndFloorsOpAddCorridorTiles(builder, corridorTiles):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(corridorTiles), 0)

def AddCorridorTiles(builder, corridorTiles):
    WallsAndFloorsOpAddCorridorTiles(builder, corridorTiles)

def WallsAndFloorsOpStartCorridorTilesVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartCorridorTilesVector(builder, numElems):
    return WallsAndFloorsOpStartCorridorTilesVector(builder, numElems)

def WallsAndFloorsOpAddCaveRegion(builder, caveRegion):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(caveRegion), 0)

def AddCaveRegion(builder, caveRegion):
    WallsAndFloorsOpAddCaveRegion(builder, caveRegion)

def WallsAndFloorsOpAddWallSegments(builder, wallSegments):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(wallSegments), 0)

def AddWallSegments(builder, wallSegments):
    WallsAndFloorsOpAddWallSegments(builder, wallSegments)

def WallsAndFloorsOpStartWallSegmentsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartWallSegmentsVector(builder, numElems):
    return WallsAndFloorsOpStartWallSegmentsVector(builder, numElems)

def WallsAndFloorsOpAddFloorColor(builder, floorColor):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(floorColor), 0)

def AddFloorColor(builder, floorColor):
    WallsAndFloorsOpAddFloorColor(builder, floorColor)

def WallsAndFloorsOpAddCaveFloorColor(builder, caveFloorColor):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(caveFloorColor), 0)

def AddCaveFloorColor(builder, caveFloorColor):
    WallsAndFloorsOpAddCaveFloorColor(builder, caveFloorColor)

def WallsAndFloorsOpAddWallColor(builder, wallColor):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(wallColor), 0)

def AddWallColor(builder, wallColor):
    WallsAndFloorsOpAddWallColor(builder, wallColor)

def WallsAndFloorsOpAddWallWidth(builder, wallWidth):
    builder.PrependFloat32Slot(8, wallWidth, 1.0)

def AddWallWidth(builder, wallWidth):
    WallsAndFloorsOpAddWallWidth(builder, wallWidth)

def WallsAndFloorsOpAddBuildingFootprint(builder, buildingFootprint):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(buildingFootprint), 0)

def AddBuildingFootprint(builder, buildingFootprint):
    WallsAndFloorsOpAddBuildingFootprint(builder, buildingFootprint)

def WallsAndFloorsOpStartBuildingFootprintVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartBuildingFootprintVector(builder, numElems):
    return WallsAndFloorsOpStartBuildingFootprintVector(builder, numElems)

def WallsAndFloorsOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return WallsAndFloorsOpEnd(builder)

import nhc.rendering.ir._fb.RectRoom
import nhc.rendering.ir._fb.TileCoord
try:
    from typing import List
except:
    pass

class WallsAndFloorsOpT(object):

    # WallsAndFloorsOpT
    def __init__(
        self,
        smoothRoomRegions = None,
        rectRooms = None,
        corridorTiles = None,
        caveRegion = None,
        wallSegments = None,
        floorColor = None,
        caveFloorColor = None,
        wallColor = None,
        wallWidth = 1.0,
        buildingFootprint = None,
    ):
        self.smoothRoomRegions = smoothRoomRegions  # type: Optional[List[Optional[str]]]
        self.rectRooms = rectRooms  # type: Optional[List[nhc.rendering.ir._fb.RectRoom.RectRoomT]]
        self.corridorTiles = corridorTiles  # type: Optional[List[nhc.rendering.ir._fb.TileCoord.TileCoordT]]
        self.caveRegion = caveRegion  # type: Optional[str]
        self.wallSegments = wallSegments  # type: Optional[List[Optional[str]]]
        self.floorColor = floorColor  # type: Optional[str]
        self.caveFloorColor = caveFloorColor  # type: Optional[str]
        self.wallColor = wallColor  # type: Optional[str]
        self.wallWidth = wallWidth  # type: float
        self.buildingFootprint = buildingFootprint  # type: Optional[List[nhc.rendering.ir._fb.TileCoord.TileCoordT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        wallsAndFloorsOp = WallsAndFloorsOp()
        wallsAndFloorsOp.Init(buf, pos)
        return cls.InitFromObj(wallsAndFloorsOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, wallsAndFloorsOp):
        x = WallsAndFloorsOpT()
        x._UnPack(wallsAndFloorsOp)
        return x

    # WallsAndFloorsOpT
    def _UnPack(self, wallsAndFloorsOp):
        if wallsAndFloorsOp is None:
            return
        if not wallsAndFloorsOp.SmoothRoomRegionsIsNone():
            self.smoothRoomRegions = []
            for i in range(wallsAndFloorsOp.SmoothRoomRegionsLength()):
                self.smoothRoomRegions.append(wallsAndFloorsOp.SmoothRoomRegions(i))
        if not wallsAndFloorsOp.RectRoomsIsNone():
            self.rectRooms = []
            for i in range(wallsAndFloorsOp.RectRoomsLength()):
                if wallsAndFloorsOp.RectRooms(i) is None:
                    self.rectRooms.append(None)
                else:
                    rectRoom_ = nhc.rendering.ir._fb.RectRoom.RectRoomT.InitFromObj(wallsAndFloorsOp.RectRooms(i))
                    self.rectRooms.append(rectRoom_)
        if not wallsAndFloorsOp.CorridorTilesIsNone():
            self.corridorTiles = []
            for i in range(wallsAndFloorsOp.CorridorTilesLength()):
                if wallsAndFloorsOp.CorridorTiles(i) is None:
                    self.corridorTiles.append(None)
                else:
                    tileCoord_ = nhc.rendering.ir._fb.TileCoord.TileCoordT.InitFromObj(wallsAndFloorsOp.CorridorTiles(i))
                    self.corridorTiles.append(tileCoord_)
        self.caveRegion = wallsAndFloorsOp.CaveRegion()
        if not wallsAndFloorsOp.WallSegmentsIsNone():
            self.wallSegments = []
            for i in range(wallsAndFloorsOp.WallSegmentsLength()):
                self.wallSegments.append(wallsAndFloorsOp.WallSegments(i))
        self.floorColor = wallsAndFloorsOp.FloorColor()
        self.caveFloorColor = wallsAndFloorsOp.CaveFloorColor()
        self.wallColor = wallsAndFloorsOp.WallColor()
        self.wallWidth = wallsAndFloorsOp.WallWidth()
        if not wallsAndFloorsOp.BuildingFootprintIsNone():
            self.buildingFootprint = []
            for i in range(wallsAndFloorsOp.BuildingFootprintLength()):
                if wallsAndFloorsOp.BuildingFootprint(i) is None:
                    self.buildingFootprint.append(None)
                else:
                    tileCoord_ = nhc.rendering.ir._fb.TileCoord.TileCoordT.InitFromObj(wallsAndFloorsOp.BuildingFootprint(i))
                    self.buildingFootprint.append(tileCoord_)

    # WallsAndFloorsOpT
    def Pack(self, builder):
        if self.smoothRoomRegions is not None:
            smoothRoomRegionslist = []
            for i in range(len(self.smoothRoomRegions)):
                smoothRoomRegionslist.append(builder.CreateString(self.smoothRoomRegions[i]))
            WallsAndFloorsOpStartSmoothRoomRegionsVector(builder, len(self.smoothRoomRegions))
            for i in reversed(range(len(self.smoothRoomRegions))):
                builder.PrependUOffsetTRelative(smoothRoomRegionslist[i])
            smoothRoomRegions = builder.EndVector()
        if self.rectRooms is not None:
            rectRoomslist = []
            for i in range(len(self.rectRooms)):
                rectRoomslist.append(self.rectRooms[i].Pack(builder))
            WallsAndFloorsOpStartRectRoomsVector(builder, len(self.rectRooms))
            for i in reversed(range(len(self.rectRooms))):
                builder.PrependUOffsetTRelative(rectRoomslist[i])
            rectRooms = builder.EndVector()
        if self.corridorTiles is not None:
            WallsAndFloorsOpStartCorridorTilesVector(builder, len(self.corridorTiles))
            for i in reversed(range(len(self.corridorTiles))):
                self.corridorTiles[i].Pack(builder)
            corridorTiles = builder.EndVector()
        if self.caveRegion is not None:
            caveRegion = builder.CreateString(self.caveRegion)
        if self.wallSegments is not None:
            wallSegmentslist = []
            for i in range(len(self.wallSegments)):
                wallSegmentslist.append(builder.CreateString(self.wallSegments[i]))
            WallsAndFloorsOpStartWallSegmentsVector(builder, len(self.wallSegments))
            for i in reversed(range(len(self.wallSegments))):
                builder.PrependUOffsetTRelative(wallSegmentslist[i])
            wallSegments = builder.EndVector()
        if self.floorColor is not None:
            floorColor = builder.CreateString(self.floorColor)
        if self.caveFloorColor is not None:
            caveFloorColor = builder.CreateString(self.caveFloorColor)
        if self.wallColor is not None:
            wallColor = builder.CreateString(self.wallColor)
        if self.buildingFootprint is not None:
            WallsAndFloorsOpStartBuildingFootprintVector(builder, len(self.buildingFootprint))
            for i in reversed(range(len(self.buildingFootprint))):
                self.buildingFootprint[i].Pack(builder)
            buildingFootprint = builder.EndVector()
        WallsAndFloorsOpStart(builder)
        if self.smoothRoomRegions is not None:
            WallsAndFloorsOpAddSmoothRoomRegions(builder, smoothRoomRegions)
        if self.rectRooms is not None:
            WallsAndFloorsOpAddRectRooms(builder, rectRooms)
        if self.corridorTiles is not None:
            WallsAndFloorsOpAddCorridorTiles(builder, corridorTiles)
        if self.caveRegion is not None:
            WallsAndFloorsOpAddCaveRegion(builder, caveRegion)
        if self.wallSegments is not None:
            WallsAndFloorsOpAddWallSegments(builder, wallSegments)
        if self.floorColor is not None:
            WallsAndFloorsOpAddFloorColor(builder, floorColor)
        if self.caveFloorColor is not None:
            WallsAndFloorsOpAddCaveFloorColor(builder, caveFloorColor)
        if self.wallColor is not None:
            WallsAndFloorsOpAddWallColor(builder, wallColor)
        WallsAndFloorsOpAddWallWidth(builder, self.wallWidth)
        if self.buildingFootprint is not None:
            WallsAndFloorsOpAddBuildingFootprint(builder, buildingFootprint)
        wallsAndFloorsOp = WallsAndFloorsOpEnd(builder)
        return wallsAndFloorsOp
