# automatically generated by the FlatBuffers compiler, do not modify

# namespace: _fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WellFeatureOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WellFeatureOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWellFeatureOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WellFeatureOpBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x4E\x49\x52\x33", size_prefixed=size_prefixed)

    # WellFeatureOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WellFeatureOp
    def Tiles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from nhc.rendering.ir._fb.TileCoord import TileCoord
            obj = TileCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WellFeatureOp
    def TilesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WellFeatureOp
    def TilesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # WellFeatureOp
    def Shape(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # WellFeatureOp
    def Seed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WellFeatureOp
    def Theme(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def WellFeatureOpStart(builder):
    builder.StartObject(4)

def Start(builder):
    WellFeatureOpStart(builder)

def WellFeatureOpAddTiles(builder, tiles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tiles), 0)

def AddTiles(builder, tiles):
    WellFeatureOpAddTiles(builder, tiles)

def WellFeatureOpStartTilesVector(builder, numElems):
    return builder.StartVector(8, numElems, 4)

def StartTilesVector(builder, numElems):
    return WellFeatureOpStartTilesVector(builder, numElems)

def WellFeatureOpAddShape(builder, shape):
    builder.PrependInt8Slot(1, shape, 0)

def AddShape(builder, shape):
    WellFeatureOpAddShape(builder, shape)

def WellFeatureOpAddSeed(builder, seed):
    builder.PrependUint64Slot(2, seed, 0)

def AddSeed(builder, seed):
    WellFeatureOpAddSeed(builder, seed)

def WellFeatureOpAddTheme(builder, theme):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(theme), 0)

def AddTheme(builder, theme):
    WellFeatureOpAddTheme(builder, theme)

def WellFeatureOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return WellFeatureOpEnd(builder)

import nhc.rendering.ir._fb.TileCoord
try:
    from typing import List
except:
    pass

class WellFeatureOpT(object):

    # WellFeatureOpT
    def __init__(
        self,
        tiles = None,
        shape = 0,
        seed = 0,
        theme = None,
    ):
        self.tiles = tiles  # type: Optional[List[nhc.rendering.ir._fb.TileCoord.TileCoordT]]
        self.shape = shape  # type: int
        self.seed = seed  # type: int
        self.theme = theme  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        wellFeatureOp = WellFeatureOp()
        wellFeatureOp.Init(buf, pos)
        return cls.InitFromObj(wellFeatureOp)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, wellFeatureOp):
        x = WellFeatureOpT()
        x._UnPack(wellFeatureOp)
        return x

    # WellFeatureOpT
    def _UnPack(self, wellFeatureOp):
        if wellFeatureOp is None:
            return
        if not wellFeatureOp.TilesIsNone():
            self.tiles = []
            for i in range(wellFeatureOp.TilesLength()):
                if wellFeatureOp.Tiles(i) is None:
                    self.tiles.append(None)
                else:
                    tileCoord_ = nhc.rendering.ir._fb.TileCoord.TileCoordT.InitFromObj(wellFeatureOp.Tiles(i))
                    self.tiles.append(tileCoord_)
        self.shape = wellFeatureOp.Shape()
        self.seed = wellFeatureOp.Seed()
        self.theme = wellFeatureOp.Theme()

    # WellFeatureOpT
    def Pack(self, builder):
        if self.tiles is not None:
            WellFeatureOpStartTilesVector(builder, len(self.tiles))
            for i in reversed(range(len(self.tiles))):
                self.tiles[i].Pack(builder)
            tiles = builder.EndVector()
        if self.theme is not None:
            theme = builder.CreateString(self.theme)
        WellFeatureOpStart(builder)
        if self.tiles is not None:
            WellFeatureOpAddTiles(builder, tiles)
        WellFeatureOpAddShape(builder, self.shape)
        WellFeatureOpAddSeed(builder, self.seed)
        if self.theme is not None:
            WellFeatureOpAddTheme(builder, theme)
        wellFeatureOp = WellFeatureOpEnd(builder)
        return wellFeatureOp
