// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { WallMaterial } from '../../../../nhc/rendering/ir/fb/wall-material.js';


export class BuildingExteriorWallOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BuildingExteriorWallOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBuildingExteriorWallOp(bb:flatbuffers.ByteBuffer, obj?:BuildingExteriorWallOp):BuildingExteriorWallOp {
  return (obj || new BuildingExteriorWallOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBuildingExteriorWallOp(bb:flatbuffers.ByteBuffer, obj?:BuildingExteriorWallOp):BuildingExteriorWallOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BuildingExteriorWallOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

regionRef():string|null
regionRef(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
regionRef(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

material():WallMaterial {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : WallMaterial.Brick;
}

rngSeed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startBuildingExteriorWallOp(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addRegionRef(builder:flatbuffers.Builder, regionRefOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, regionRefOffset, 0);
}

static addMaterial(builder:flatbuffers.Builder, material:WallMaterial) {
  builder.addFieldInt8(1, material, WallMaterial.Brick);
}

static addRngSeed(builder:flatbuffers.Builder, rngSeed:bigint) {
  builder.addFieldInt64(2, rngSeed, BigInt('0'));
}

static endBuildingExteriorWallOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createBuildingExteriorWallOp(builder:flatbuffers.Builder, regionRefOffset:flatbuffers.Offset, material:WallMaterial, rngSeed:bigint):flatbuffers.Offset {
  BuildingExteriorWallOp.startBuildingExteriorWallOp(builder);
  BuildingExteriorWallOp.addRegionRef(builder, regionRefOffset);
  BuildingExteriorWallOp.addMaterial(builder, material);
  BuildingExteriorWallOp.addRngSeed(builder, rngSeed);
  return BuildingExteriorWallOp.endBuildingExteriorWallOp(builder);
}
}
