// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TileCoord } from '../../../../nhc/rendering/ir/fb/tile-coord.js';


export class CartTracksVariant {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CartTracksVariant {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCartTracksVariant(bb:flatbuffers.ByteBuffer, obj?:CartTracksVariant):CartTracksVariant {
  return (obj || new CartTracksVariant()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCartTracksVariant(bb:flatbuffers.ByteBuffer, obj?:CartTracksVariant):CartTracksVariant {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CartTracksVariant()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tiles(index: number, obj?:TileCoord):TileCoord|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TileCoord()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

tilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

openSides(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

openSidesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

openSidesArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startCartTracksVariant(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTiles(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, tilesOffset, 0);
}

static startTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addOpenSides(builder:flatbuffers.Builder, openSidesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, openSidesOffset, 0);
}

static createOpenSidesVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startOpenSidesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endCartTracksVariant(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCartTracksVariant(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset, openSidesOffset:flatbuffers.Offset):flatbuffers.Offset {
  CartTracksVariant.startCartTracksVariant(builder);
  CartTracksVariant.addTiles(builder, tilesOffset);
  CartTracksVariant.addOpenSides(builder, openSidesOffset);
  return CartTracksVariant.endCartTracksVariant(builder);
}
}
