// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CobblePattern } from '../../../../nhc/rendering/ir/fb/cobble-pattern.js';
import { TileCoord } from '../../../../nhc/rendering/ir/fb/tile-coord.js';


export class CobblestoneVariant {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CobblestoneVariant {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCobblestoneVariant(bb:flatbuffers.ByteBuffer, obj?:CobblestoneVariant):CobblestoneVariant {
  return (obj || new CobblestoneVariant()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCobblestoneVariant(bb:flatbuffers.ByteBuffer, obj?:CobblestoneVariant):CobblestoneVariant {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CobblestoneVariant()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tiles(index: number, obj?:TileCoord):TileCoord|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TileCoord()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

tilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

pattern():CobblePattern {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : CobblePattern.Cobble;
}

static startCobblestoneVariant(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTiles(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, tilesOffset, 0);
}

static startTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addPattern(builder:flatbuffers.Builder, pattern:CobblePattern) {
  builder.addFieldInt8(1, pattern, CobblePattern.Cobble);
}

static endCobblestoneVariant(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCobblestoneVariant(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset, pattern:CobblePattern):flatbuffers.Offset {
  CobblestoneVariant.startCobblestoneVariant(builder);
  CobblestoneVariant.addTiles(builder, tilesOffset);
  CobblestoneVariant.addPattern(builder, pattern);
  return CobblestoneVariant.endCobblestoneVariant(builder);
}
}
