// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TileCoord } from '../../../../nhc/rendering/ir/fb/tile-coord.js';
import { WallStyle } from '../../../../nhc/rendering/ir/fb/wall-style.js';


export class CorridorWallOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CorridorWallOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCorridorWallOp(bb:flatbuffers.ByteBuffer, obj?:CorridorWallOp):CorridorWallOp {
  return (obj || new CorridorWallOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCorridorWallOp(bb:flatbuffers.ByteBuffer, obj?:CorridorWallOp):CorridorWallOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CorridorWallOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tiles(index: number, obj?:TileCoord):TileCoord|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TileCoord()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

tilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

style():WallStyle {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : WallStyle.DungeonInk;
}

static startCorridorWallOp(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTiles(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, tilesOffset, 0);
}

static startTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addStyle(builder:flatbuffers.Builder, style:WallStyle) {
  builder.addFieldInt8(1, style, WallStyle.DungeonInk);
}

static endCorridorWallOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCorridorWallOp(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset, style:WallStyle):flatbuffers.Offset {
  CorridorWallOp.startCorridorWallOp(builder);
  CorridorWallOp.addTiles(builder, tilesOffset);
  CorridorWallOp.addStyle(builder, style);
  return CorridorWallOp.endCorridorWallOp(builder);
}
}
