// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CutStyle } from '../../../../nhc/rendering/ir/fb/cut-style.js';
import { Vec2 } from '../../../../nhc/rendering/ir/fb/vec2.js';


export class Cut {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Cut {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCut(bb:flatbuffers.ByteBuffer, obj?:Cut):Cut {
  return (obj || new Cut()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCut(bb:flatbuffers.ByteBuffer, obj?:Cut):Cut {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Cut()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

start(obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Vec2()).__init(this.bb_pos + offset, this.bb!) : null;
}

end(obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Vec2()).__init(this.bb_pos + offset, this.bb!) : null;
}

style():CutStyle {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : CutStyle.None;
}

static startCut(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addStart(builder:flatbuffers.Builder, startOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, startOffset, 0);
}

static addEnd(builder:flatbuffers.Builder, endOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, endOffset, 0);
}

static addStyle(builder:flatbuffers.Builder, style:CutStyle) {
  builder.addFieldInt8(2, style, CutStyle.None);
}

static endCut(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
