// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CornerStyle } from '../../../../nhc/rendering/ir/fb/corner-style.js';
import { EnclosureStyle } from '../../../../nhc/rendering/ir/fb/enclosure-style.js';
import { Gate } from '../../../../nhc/rendering/ir/fb/gate.js';
import { Polygon } from '../../../../nhc/rendering/ir/fb/polygon.js';


export class EnclosureOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EnclosureOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEnclosureOp(bb:flatbuffers.ByteBuffer, obj?:EnclosureOp):EnclosureOp {
  return (obj || new EnclosureOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEnclosureOp(bb:flatbuffers.ByteBuffer, obj?:EnclosureOp):EnclosureOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EnclosureOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

polygon(obj?:Polygon):Polygon|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Polygon()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

style():EnclosureStyle {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : EnclosureStyle.Palisade;
}

cornerStyle():CornerStyle {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : CornerStyle.Merlon;
}

gates(index: number, obj?:Gate):Gate|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Gate()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

gatesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

rngSeed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startEnclosureOp(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addPolygon(builder:flatbuffers.Builder, polygonOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, polygonOffset, 0);
}

static addStyle(builder:flatbuffers.Builder, style:EnclosureStyle) {
  builder.addFieldInt8(1, style, EnclosureStyle.Palisade);
}

static addCornerStyle(builder:flatbuffers.Builder, cornerStyle:CornerStyle) {
  builder.addFieldInt8(2, cornerStyle, CornerStyle.Merlon);
}

static addGates(builder:flatbuffers.Builder, gatesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, gatesOffset, 0);
}

static createGatesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startGatesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRngSeed(builder:flatbuffers.Builder, rngSeed:bigint) {
  builder.addFieldInt64(4, rngSeed, BigInt('0'));
}

static endEnclosureOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEnclosureOp(builder:flatbuffers.Builder, polygonOffset:flatbuffers.Offset, style:EnclosureStyle, cornerStyle:CornerStyle, gatesOffset:flatbuffers.Offset, rngSeed:bigint):flatbuffers.Offset {
  EnclosureOp.startEnclosureOp(builder);
  EnclosureOp.addPolygon(builder, polygonOffset);
  EnclosureOp.addStyle(builder, style);
  EnclosureOp.addCornerStyle(builder, cornerStyle);
  EnclosureOp.addGates(builder, gatesOffset);
  EnclosureOp.addRngSeed(builder, rngSeed);
  return EnclosureOp.endEnclosureOp(builder);
}
}
