// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TileCoord } from '../../../../nhc/rendering/ir/fb/tile-coord.js';


export class FieldStoneVariant {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FieldStoneVariant {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFieldStoneVariant(bb:flatbuffers.ByteBuffer, obj?:FieldStoneVariant):FieldStoneVariant {
  return (obj || new FieldStoneVariant()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFieldStoneVariant(bb:flatbuffers.ByteBuffer, obj?:FieldStoneVariant):FieldStoneVariant {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FieldStoneVariant()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tiles(index: number, obj?:TileCoord):TileCoord|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TileCoord()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

tilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startFieldStoneVariant(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTiles(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, tilesOffset, 0);
}

static startTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static endFieldStoneVariant(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFieldStoneVariant(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset):flatbuffers.Offset {
  FieldStoneVariant.startFieldStoneVariant(builder);
  FieldStoneVariant.addTiles(builder, tilesOffset);
  return FieldStoneVariant.endFieldStoneVariant(builder);
}
}
