// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Anchor } from '../../../../nhc/rendering/ir/fb/anchor.js';
import { FixtureKind } from '../../../../nhc/rendering/ir/fb/fixture-kind.js';


export class FixtureOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FixtureOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFixtureOp(bb:flatbuffers.ByteBuffer, obj?:FixtureOp):FixtureOp {
  return (obj || new FixtureOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFixtureOp(bb:flatbuffers.ByteBuffer, obj?:FixtureOp):FixtureOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FixtureOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

regionRef():string|null
regionRef(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
regionRef(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

kind():FixtureKind {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : FixtureKind.Web;
}

anchors(index: number, obj?:Anchor):Anchor|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Anchor()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 16, this.bb!) : null;
}

anchorsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

seed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startFixtureOp(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addRegionRef(builder:flatbuffers.Builder, regionRefOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, regionRefOffset, 0);
}

static addKind(builder:flatbuffers.Builder, kind:FixtureKind) {
  builder.addFieldInt8(1, kind, FixtureKind.Web);
}

static addAnchors(builder:flatbuffers.Builder, anchorsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, anchorsOffset, 0);
}

static startAnchorsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(16, numElems, 4);
}

static addSeed(builder:flatbuffers.Builder, seed:bigint) {
  builder.addFieldInt64(3, seed, BigInt('0'));
}

static endFixtureOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFixtureOp(builder:flatbuffers.Builder, regionRefOffset:flatbuffers.Offset, kind:FixtureKind, anchorsOffset:flatbuffers.Offset, seed:bigint):flatbuffers.Offset {
  FixtureOp.startFixtureOp(builder);
  FixtureOp.addRegionRef(builder, regionRefOffset);
  FixtureOp.addKind(builder, kind);
  FixtureOp.addAnchors(builder, anchorsOffset);
  FixtureOp.addSeed(builder, seed);
  return FixtureOp.endFixtureOp(builder);
}
}
