// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FloorGridTile } from '../../../../nhc/rendering/ir/fb/floor-grid-tile.js';


export class FloorGridOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FloorGridOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFloorGridOp(bb:flatbuffers.ByteBuffer, obj?:FloorGridOp):FloorGridOp {
  return (obj || new FloorGridOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFloorGridOp(bb:flatbuffers.ByteBuffer, obj?:FloorGridOp):FloorGridOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FloorGridOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

clipRegion():string|null
clipRegion(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
clipRegion(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

seed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

theme():string|null
theme(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
theme(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

scale():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

tiles(index: number, obj?:FloorGridTile):FloorGridTile|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new FloorGridTile()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 12, this.bb!) : null;
}

tilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startFloorGridOp(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addClipRegion(builder:flatbuffers.Builder, clipRegionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, clipRegionOffset, 0);
}

static addSeed(builder:flatbuffers.Builder, seed:bigint) {
  builder.addFieldInt64(1, seed, BigInt('0'));
}

static addTheme(builder:flatbuffers.Builder, themeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, themeOffset, 0);
}

static addScale(builder:flatbuffers.Builder, scale:number) {
  builder.addFieldFloat32(3, scale, 1.0);
}

static addTiles(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, tilesOffset, 0);
}

static startTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(12, numElems, 4);
}

static endFloorGridOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFloorGridOp(builder:flatbuffers.Builder, clipRegionOffset:flatbuffers.Offset, seed:bigint, themeOffset:flatbuffers.Offset, scale:number, tilesOffset:flatbuffers.Offset):flatbuffers.Offset {
  FloorGridOp.startFloorGridOp(builder);
  FloorGridOp.addClipRegion(builder, clipRegionOffset);
  FloorGridOp.addSeed(builder, seed);
  FloorGridOp.addTheme(builder, themeOffset);
  FloorGridOp.addScale(builder, scale);
  FloorGridOp.addTiles(builder, tilesOffset);
  return FloorGridOp.endFloorGridOp(builder);
}
}
