// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FeatureFlags } from '../../../../nhc/rendering/ir/fb/feature-flags.js';
import { FloorKind } from '../../../../nhc/rendering/ir/fb/floor-kind.js';
import { OpEntry } from '../../../../nhc/rendering/ir/fb/op-entry.js';
import { Region } from '../../../../nhc/rendering/ir/fb/region.js';


export class FloorIR {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FloorIR {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFloorIR(bb:flatbuffers.ByteBuffer, obj?:FloorIR):FloorIR {
  return (obj || new FloorIR()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFloorIR(bb:flatbuffers.ByteBuffer, obj?:FloorIR):FloorIR {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FloorIR()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static bufferHasIdentifier(bb:flatbuffers.ByteBuffer):boolean {
  return bb.__has_identifier('NIR4');
}

major():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

minor():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

widthTiles():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

heightTiles():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

cell():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 32;
}

padding():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 32;
}

floorKind():FloorKind {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : FloorKind.Dungeon;
}

theme():string|null
theme(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
theme(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

baseSeed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

flags(obj?:FeatureFlags):FeatureFlags|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new FeatureFlags()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

regions(index: number, obj?:Region):Region|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? (obj || new Region()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

regionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

ops(index: number, obj?:OpEntry):OpEntry|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? (obj || new OpEntry()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

opsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startFloorIR(builder:flatbuffers.Builder) {
  builder.startObject(12);
}

static addMajor(builder:flatbuffers.Builder, major:number) {
  builder.addFieldInt32(0, major, 0);
}

static addMinor(builder:flatbuffers.Builder, minor:number) {
  builder.addFieldInt32(1, minor, 0);
}

static addWidthTiles(builder:flatbuffers.Builder, widthTiles:number) {
  builder.addFieldInt32(2, widthTiles, 0);
}

static addHeightTiles(builder:flatbuffers.Builder, heightTiles:number) {
  builder.addFieldInt32(3, heightTiles, 0);
}

static addCell(builder:flatbuffers.Builder, cell:number) {
  builder.addFieldInt32(4, cell, 32);
}

static addPadding(builder:flatbuffers.Builder, padding:number) {
  builder.addFieldInt32(5, padding, 32);
}

static addFloorKind(builder:flatbuffers.Builder, floorKind:FloorKind) {
  builder.addFieldInt8(6, floorKind, FloorKind.Dungeon);
}

static addTheme(builder:flatbuffers.Builder, themeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, themeOffset, 0);
}

static addBaseSeed(builder:flatbuffers.Builder, baseSeed:bigint) {
  builder.addFieldInt64(8, baseSeed, BigInt('0'));
}

static addFlags(builder:flatbuffers.Builder, flagsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, flagsOffset, 0);
}

static addRegions(builder:flatbuffers.Builder, regionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, regionsOffset, 0);
}

static createRegionsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRegionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addOps(builder:flatbuffers.Builder, opsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(11, opsOffset, 0);
}

static createOpsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startOpsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endFloorIR(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishFloorIRBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'NIR4');
}

static finishSizePrefixedFloorIRBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'NIR4', true);
}

}
