// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RectRoom } from '../../../../nhc/rendering/ir/fb/rect-room.js';
import { TileCoord } from '../../../../nhc/rendering/ir/fb/tile-coord.js';
import { Vec2 } from '../../../../nhc/rendering/ir/fb/vec2.js';


export class FloorDetailOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FloorDetailOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFloorDetailOp(bb:flatbuffers.ByteBuffer, obj?:FloorDetailOp):FloorDetailOp {
  return (obj || new FloorDetailOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFloorDetailOp(bb:flatbuffers.ByteBuffer, obj?:FloorDetailOp):FloorDetailOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FloorDetailOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tiles(index: number, obj?:TileCoord):TileCoord|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TileCoord()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

tilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

seed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

theme():string|null
theme(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
theme(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

roomGroups(index: number):string
roomGroups(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
roomGroups(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

roomGroupsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

corridorGroups(index: number):string
corridorGroups(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
corridorGroups(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

corridorGroupsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

clipRegion():string|null
clipRegion(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
clipRegion(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

isCorridor(index: number):boolean|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? !!this.bb!.readInt8(this.bb!.__vector(this.bb_pos + offset) + index) : false;
}

isCorridorLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

isCorridorArray():Int8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? new Int8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

woodTiles(index: number, obj?:TileCoord):TileCoord|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new TileCoord()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

woodTilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

woodBuildingPolygon(index: number, obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new Vec2()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

woodBuildingPolygonLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

woodRooms(index: number, obj?:RectRoom):RectRoom|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new RectRoom()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

woodRoomsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

regionRef():string|null
regionRef(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
regionRef(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startFloorDetailOp(builder:flatbuffers.Builder) {
  builder.startObject(11);
}

static addTiles(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, tilesOffset, 0);
}

static startTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addSeed(builder:flatbuffers.Builder, seed:bigint) {
  builder.addFieldInt64(1, seed, BigInt('0'));
}

static addTheme(builder:flatbuffers.Builder, themeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, themeOffset, 0);
}

static addRoomGroups(builder:flatbuffers.Builder, roomGroupsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, roomGroupsOffset, 0);
}

static createRoomGroupsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRoomGroupsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addCorridorGroups(builder:flatbuffers.Builder, corridorGroupsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, corridorGroupsOffset, 0);
}

static createCorridorGroupsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCorridorGroupsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addClipRegion(builder:flatbuffers.Builder, clipRegionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, clipRegionOffset, 0);
}

static addIsCorridor(builder:flatbuffers.Builder, isCorridorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, isCorridorOffset, 0);
}

static createIsCorridorVector(builder:flatbuffers.Builder, data:boolean[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(+data[i]!);
  }
  return builder.endVector();
}

static startIsCorridorVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addWoodTiles(builder:flatbuffers.Builder, woodTilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, woodTilesOffset, 0);
}

static startWoodTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addWoodBuildingPolygon(builder:flatbuffers.Builder, woodBuildingPolygonOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, woodBuildingPolygonOffset, 0);
}

static startWoodBuildingPolygonVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addWoodRooms(builder:flatbuffers.Builder, woodRoomsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, woodRoomsOffset, 0);
}

static createWoodRoomsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startWoodRoomsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRegionRef(builder:flatbuffers.Builder, regionRefOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, regionRefOffset, 0);
}

static endFloorDetailOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFloorDetailOp(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset, seed:bigint, themeOffset:flatbuffers.Offset, roomGroupsOffset:flatbuffers.Offset, corridorGroupsOffset:flatbuffers.Offset, clipRegionOffset:flatbuffers.Offset, isCorridorOffset:flatbuffers.Offset, woodTilesOffset:flatbuffers.Offset, woodBuildingPolygonOffset:flatbuffers.Offset, woodRoomsOffset:flatbuffers.Offset, regionRefOffset:flatbuffers.Offset):flatbuffers.Offset {
  FloorDetailOp.startFloorDetailOp(builder);
  FloorDetailOp.addTiles(builder, tilesOffset);
  FloorDetailOp.addSeed(builder, seed);
  FloorDetailOp.addTheme(builder, themeOffset);
  FloorDetailOp.addRoomGroups(builder, roomGroupsOffset);
  FloorDetailOp.addCorridorGroups(builder, corridorGroupsOffset);
  FloorDetailOp.addClipRegion(builder, clipRegionOffset);
  FloorDetailOp.addIsCorridor(builder, isCorridorOffset);
  FloorDetailOp.addWoodTiles(builder, woodTilesOffset);
  FloorDetailOp.addWoodBuildingPolygon(builder, woodBuildingPolygonOffset);
  FloorDetailOp.addWoodRooms(builder, woodRoomsOffset);
  FloorDetailOp.addRegionRef(builder, regionRefOffset);
  return FloorDetailOp.endFloorDetailOp(builder);
}
}
