// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum FloorKind {
  Dungeon = 0,
  Cave = 1,
  Building = 2,
  Surface = 3
}
