// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FountainShape } from '../../../../nhc/rendering/ir/fb/fountain-shape.js';
import { TileCoord } from '../../../../nhc/rendering/ir/fb/tile-coord.js';


export class FountainFeatureOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FountainFeatureOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFountainFeatureOp(bb:flatbuffers.ByteBuffer, obj?:FountainFeatureOp):FountainFeatureOp {
  return (obj || new FountainFeatureOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFountainFeatureOp(bb:flatbuffers.ByteBuffer, obj?:FountainFeatureOp):FountainFeatureOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FountainFeatureOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tiles(index: number, obj?:TileCoord):TileCoord|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TileCoord()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

tilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

shape():FountainShape {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : FountainShape.Round;
}

seed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

theme():string|null
theme(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
theme(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startFountainFeatureOp(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addTiles(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, tilesOffset, 0);
}

static startTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addShape(builder:flatbuffers.Builder, shape:FountainShape) {
  builder.addFieldInt8(1, shape, FountainShape.Round);
}

static addSeed(builder:flatbuffers.Builder, seed:bigint) {
  builder.addFieldInt64(2, seed, BigInt('0'));
}

static addTheme(builder:flatbuffers.Builder, themeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, themeOffset, 0);
}

static endFountainFeatureOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFountainFeatureOp(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset, shape:FountainShape, seed:bigint, themeOffset:flatbuffers.Offset):flatbuffers.Offset {
  FountainFeatureOp.startFountainFeatureOp(builder);
  FountainFeatureOp.addTiles(builder, tilesOffset);
  FountainFeatureOp.addShape(builder, shape);
  FountainFeatureOp.addSeed(builder, seed);
  FountainFeatureOp.addTheme(builder, themeOffset);
  return FountainFeatureOp.endFountainFeatureOp(builder);
}
}
