// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Polygon } from '../../../../nhc/rendering/ir/fb/polygon.js';


export class GrovePolygon {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GrovePolygon {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGrovePolygon(bb:flatbuffers.ByteBuffer, obj?:GrovePolygon):GrovePolygon {
  return (obj || new GrovePolygon()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGrovePolygon(bb:flatbuffers.ByteBuffer, obj?:GrovePolygon):GrovePolygon {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GrovePolygon()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

polygon(obj?:Polygon):Polygon|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Polygon()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startGrovePolygon(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPolygon(builder:flatbuffers.Builder, polygonOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, polygonOffset, 0);
}

static endGrovePolygon(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGrovePolygon(builder:flatbuffers.Builder, polygonOffset:flatbuffers.Offset):flatbuffers.Offset {
  GrovePolygon.startGrovePolygon(builder);
  GrovePolygon.addPolygon(builder, polygonOffset);
  return GrovePolygon.endGrovePolygon(builder);
}
}
