// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum InteriorWallMaterial {
  Stone = 0,
  Brick = 1,
  Wood = 2
}
