// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TileCorner } from '../../../../nhc/rendering/ir/fb/tile-corner.js';


export class InteriorEdge {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):InteriorEdge {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

ax():number {
  return this.bb!.readInt32(this.bb_pos);
}

ay():number {
  return this.bb!.readInt32(this.bb_pos + 4);
}

aCorner():TileCorner {
  return this.bb!.readInt8(this.bb_pos + 8);
}

bx():number {
  return this.bb!.readInt32(this.bb_pos + 12);
}

by():number {
  return this.bb!.readInt32(this.bb_pos + 16);
}

bCorner():TileCorner {
  return this.bb!.readInt8(this.bb_pos + 20);
}

pad0():number {
  return this.bb!.readUint8(this.bb_pos + 21);
}

pad1():number {
  return this.bb!.readUint8(this.bb_pos + 22);
}

static sizeOf():number {
  return 24;
}

static createInteriorEdge(builder:flatbuffers.Builder, ax: number, ay: number, a_corner: TileCorner, bx: number, by: number, b_corner: TileCorner, pad0: number, pad1: number):flatbuffers.Offset {
  builder.prep(4, 24);
  builder.pad(1);
  builder.writeInt8(pad1);
  builder.writeInt8(pad0);
  builder.writeInt8(b_corner);
  builder.writeInt32(by);
  builder.writeInt32(bx);
  builder.pad(3);
  builder.writeInt8(a_corner);
  builder.writeInt32(ay);
  builder.writeInt32(ax);
  return builder.offset();
}

}
