// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MaterialFamily } from '../../../../nhc/rendering/ir/fb/material-family.js';


export class Material {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Material {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMaterial(bb:flatbuffers.ByteBuffer, obj?:Material):Material {
  return (obj || new Material()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMaterial(bb:flatbuffers.ByteBuffer, obj?:Material):Material {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Material()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

family():MaterialFamily {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MaterialFamily.Plain;
}

style():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

subPattern():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

tone():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

seed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startMaterial(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addFamily(builder:flatbuffers.Builder, family:MaterialFamily) {
  builder.addFieldInt8(0, family, MaterialFamily.Plain);
}

static addStyle(builder:flatbuffers.Builder, style:number) {
  builder.addFieldInt8(1, style, 0);
}

static addSubPattern(builder:flatbuffers.Builder, subPattern:number) {
  builder.addFieldInt8(2, subPattern, 0);
}

static addTone(builder:flatbuffers.Builder, tone:number) {
  builder.addFieldInt8(3, tone, 0);
}

static addSeed(builder:flatbuffers.Builder, seed:bigint) {
  builder.addFieldInt64(4, seed, BigInt('0'));
}

static endMaterial(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMaterial(builder:flatbuffers.Builder, family:MaterialFamily, style:number, subPattern:number, tone:number, seed:bigint):flatbuffers.Offset {
  Material.startMaterial(builder);
  Material.addFamily(builder, family);
  Material.addStyle(builder, style);
  Material.addSubPattern(builder, subPattern);
  Material.addTone(builder, tone);
  Material.addSeed(builder, seed);
  return Material.endMaterial(builder);
}
}
