// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum MaterialFamily {
  Plain = 0,
  Cave = 1,
  Wood = 2,
  Stone = 3,
  Earth = 4,
  Liquid = 5,
  Special = 6
}
