// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TileCoord } from '../../../../nhc/rendering/ir/fb/tile-coord.js';


export class OreDepositsOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OreDepositsOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOreDepositsOp(bb:flatbuffers.ByteBuffer, obj?:OreDepositsOp):OreDepositsOp {
  return (obj || new OreDepositsOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOreDepositsOp(bb:flatbuffers.ByteBuffer, obj?:OreDepositsOp):OreDepositsOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new OreDepositsOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tiles(index: number, obj?:TileCoord):TileCoord|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TileCoord()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

tilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

seed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

theme():string|null
theme(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
theme(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startOreDepositsOp(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addTiles(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, tilesOffset, 0);
}

static startTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addSeed(builder:flatbuffers.Builder, seed:bigint) {
  builder.addFieldInt64(1, seed, BigInt('0'));
}

static addTheme(builder:flatbuffers.Builder, themeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, themeOffset, 0);
}

static endOreDepositsOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createOreDepositsOp(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset, seed:bigint, themeOffset:flatbuffers.Offset):flatbuffers.Offset {
  OreDepositsOp.startOreDepositsOp(builder);
  OreDepositsOp.addTiles(builder, tilesOffset);
  OreDepositsOp.addSeed(builder, seed);
  OreDepositsOp.addTheme(builder, themeOffset);
  return OreDepositsOp.endOreDepositsOp(builder);
}
}
