// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class PathRange {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PathRange {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

start():number {
  return this.bb!.readUint32(this.bb_pos);
}

count():number {
  return this.bb!.readUint32(this.bb_pos + 4);
}

isHole():boolean {
  return !!this.bb!.readInt8(this.bb_pos + 8);
}

static sizeOf():number {
  return 12;
}

static createPathRange(builder:flatbuffers.Builder, start: number, count: number, is_hole: boolean):flatbuffers.Offset {
  builder.prep(4, 12);
  builder.pad(3);
  builder.writeInt8(Number(Boolean(is_hole)));
  builder.writeInt32(count);
  builder.writeInt32(start);
  return builder.offset();
}

}
