// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PathRange } from '../../../../nhc/rendering/ir/fb/path-range.js';
import { Vec2 } from '../../../../nhc/rendering/ir/fb/vec2.js';


export class Polygon {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Polygon {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPolygon(bb:flatbuffers.ByteBuffer, obj?:Polygon):Polygon {
  return (obj || new Polygon()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPolygon(bb:flatbuffers.ByteBuffer, obj?:Polygon):Polygon {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Polygon()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

paths(index: number, obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Vec2()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

pathsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

rings(index: number, obj?:PathRange):PathRange|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new PathRange()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 12, this.bb!) : null;
}

ringsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startPolygon(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addPaths(builder:flatbuffers.Builder, pathsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, pathsOffset, 0);
}

static startPathsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addRings(builder:flatbuffers.Builder, ringsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, ringsOffset, 0);
}

static startRingsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(12, numElems, 4);
}

static endPolygon(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPolygon(builder:flatbuffers.Builder, pathsOffset:flatbuffers.Offset, ringsOffset:flatbuffers.Offset):flatbuffers.Offset {
  Polygon.startPolygon(builder);
  Polygon.addPaths(builder, pathsOffset);
  Polygon.addRings(builder, ringsOffset);
  return Polygon.endPolygon(builder);
}
}
