// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Cut } from '../../../../nhc/rendering/ir/fb/cut.js';
import { Outline } from '../../../../nhc/rendering/ir/fb/outline.js';


export class Region {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Region {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRegion(bb:flatbuffers.ByteBuffer, obj?:Region):Region {
  return (obj || new Region()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRegion(bb:flatbuffers.ByteBuffer, obj?:Region):Region {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Region()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

outline(obj?:Outline):Outline|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Outline()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

parentId():string|null
parentId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
parentId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

cuts(index: number, obj?:Cut):Cut|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Cut()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

cutsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

shapeTag():string|null
shapeTag(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
shapeTag(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startRegion(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addOutline(builder:flatbuffers.Builder, outlineOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, outlineOffset, 0);
}

static addParentId(builder:flatbuffers.Builder, parentIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, parentIdOffset, 0);
}

static addCuts(builder:flatbuffers.Builder, cutsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, cutsOffset, 0);
}

static createCutsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCutsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addShapeTag(builder:flatbuffers.Builder, shapeTagOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, shapeTagOffset, 0);
}

static endRegion(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // id
  return offset;
}

}
