// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum RoofTilePattern {
  Shingle = 0,
  Fishscale = 1,
  Thatch = 2,
  Slate = 3
}
