// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RoofStyle } from '../../../../nhc/rendering/ir/fb/roof-style.js';


export class RoofOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoofOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoofOp(bb:flatbuffers.ByteBuffer, obj?:RoofOp):RoofOp {
  return (obj || new RoofOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoofOp(bb:flatbuffers.ByteBuffer, obj?:RoofOp):RoofOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoofOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

regionRef():string|null
regionRef(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
regionRef(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

style():RoofStyle {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : RoofStyle.Simple;
}

tint():string|null
tint(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
tint(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

rngSeed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startRoofOp(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addRegionRef(builder:flatbuffers.Builder, regionRefOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, regionRefOffset, 0);
}

static addStyle(builder:flatbuffers.Builder, style:RoofStyle) {
  builder.addFieldInt8(1, style, RoofStyle.Simple);
}

static addTint(builder:flatbuffers.Builder, tintOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, tintOffset, 0);
}

static addRngSeed(builder:flatbuffers.Builder, rngSeed:bigint) {
  builder.addFieldInt64(3, rngSeed, BigInt('0'));
}

static endRoofOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRoofOp(builder:flatbuffers.Builder, regionRefOffset:flatbuffers.Offset, style:RoofStyle, tintOffset:flatbuffers.Offset, rngSeed:bigint):flatbuffers.Offset {
  RoofOp.startRoofOp(builder);
  RoofOp.addRegionRef(builder, regionRefOffset);
  RoofOp.addStyle(builder, style);
  RoofOp.addTint(builder, tintOffset);
  RoofOp.addRngSeed(builder, rngSeed);
  return RoofOp.endRoofOp(builder);
}
}
