// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ShadowKind } from '../../../../nhc/rendering/ir/fb/shadow-kind.js';
import { TileCoord } from '../../../../nhc/rendering/ir/fb/tile-coord.js';


export class ShadowOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ShadowOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsShadowOp(bb:flatbuffers.ByteBuffer, obj?:ShadowOp):ShadowOp {
  return (obj || new ShadowOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsShadowOp(bb:flatbuffers.ByteBuffer, obj?:ShadowOp):ShadowOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ShadowOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

kind():ShadowKind {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ShadowKind.Room;
}

regionRef():string|null
regionRef(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
regionRef(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

tiles(index: number, obj?:TileCoord):TileCoord|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new TileCoord()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

tilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

dx():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 3.0;
}

dy():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 3.0;
}

opacity():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.08;
}

static startShadowOp(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addKind(builder:flatbuffers.Builder, kind:ShadowKind) {
  builder.addFieldInt8(0, kind, ShadowKind.Room);
}

static addRegionRef(builder:flatbuffers.Builder, regionRefOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, regionRefOffset, 0);
}

static addTiles(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, tilesOffset, 0);
}

static startTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addDx(builder:flatbuffers.Builder, dx:number) {
  builder.addFieldFloat32(3, dx, 3.0);
}

static addDy(builder:flatbuffers.Builder, dy:number) {
  builder.addFieldFloat32(4, dy, 3.0);
}

static addOpacity(builder:flatbuffers.Builder, opacity:number) {
  builder.addFieldFloat32(5, opacity, 0.08);
}

static endShadowOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createShadowOp(builder:flatbuffers.Builder, kind:ShadowKind, regionRefOffset:flatbuffers.Offset, tilesOffset:flatbuffers.Offset, dx:number, dy:number, opacity:number):flatbuffers.Offset {
  ShadowOp.startShadowOp(builder);
  ShadowOp.addKind(builder, kind);
  ShadowOp.addRegionRef(builder, regionRefOffset);
  ShadowOp.addTiles(builder, tilesOffset);
  ShadowOp.addDx(builder, dx);
  ShadowOp.addDy(builder, dy);
  ShadowOp.addOpacity(builder, opacity);
  return ShadowOp.endShadowOp(builder);
}
}
