// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { StairDirection } from '../../../../nhc/rendering/ir/fb/stair-direction.js';


export class StairTile {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StairTile {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

x():number {
  return this.bb!.readInt32(this.bb_pos);
}

y():number {
  return this.bb!.readInt32(this.bb_pos + 4);
}

direction():StairDirection {
  return this.bb!.readInt8(this.bb_pos + 8);
}

pad0():number {
  return this.bb!.readUint8(this.bb_pos + 9);
}

pad1():number {
  return this.bb!.readUint8(this.bb_pos + 10);
}

pad2():number {
  return this.bb!.readUint8(this.bb_pos + 11);
}

static sizeOf():number {
  return 12;
}

static createStairTile(builder:flatbuffers.Builder, x: number, y: number, direction: StairDirection, pad0: number, pad1: number, pad2: number):flatbuffers.Offset {
  builder.prep(4, 12);
  builder.writeInt8(pad2);
  builder.writeInt8(pad1);
  builder.writeInt8(pad0);
  builder.writeInt8(direction);
  builder.writeInt32(y);
  builder.writeInt32(x);
  return builder.offset();
}

}
