// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class StampOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StampOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStampOp(bb:flatbuffers.ByteBuffer, obj?:StampOp):StampOp {
  return (obj || new StampOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStampOp(bb:flatbuffers.ByteBuffer, obj?:StampOp):StampOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StampOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

regionRef():string|null
regionRef(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
regionRef(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

subtractRegionRefs(index: number):string
subtractRegionRefs(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
subtractRegionRefs(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

subtractRegionRefsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

decoratorMask():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

density():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 128;
}

seed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startStampOp(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addRegionRef(builder:flatbuffers.Builder, regionRefOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, regionRefOffset, 0);
}

static addSubtractRegionRefs(builder:flatbuffers.Builder, subtractRegionRefsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, subtractRegionRefsOffset, 0);
}

static createSubtractRegionRefsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSubtractRegionRefsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addDecoratorMask(builder:flatbuffers.Builder, decoratorMask:number) {
  builder.addFieldInt32(2, decoratorMask, 0);
}

static addDensity(builder:flatbuffers.Builder, density:number) {
  builder.addFieldInt8(3, density, 128);
}

static addSeed(builder:flatbuffers.Builder, seed:bigint) {
  builder.addFieldInt64(4, seed, BigInt('0'));
}

static endStampOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStampOp(builder:flatbuffers.Builder, regionRefOffset:flatbuffers.Offset, subtractRegionRefsOffset:flatbuffers.Offset, decoratorMask:number, density:number, seed:bigint):flatbuffers.Offset {
  StampOp.startStampOp(builder);
  StampOp.addRegionRef(builder, regionRefOffset);
  StampOp.addSubtractRegionRefs(builder, subtractRegionRefsOffset);
  StampOp.addDecoratorMask(builder, decoratorMask);
  StampOp.addDensity(builder, density);
  StampOp.addSeed(builder, seed);
  return StampOp.endStampOp(builder);
}
}
