// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Cut } from '../../../../nhc/rendering/ir/fb/cut.js';
import { Outline } from '../../../../nhc/rendering/ir/fb/outline.js';
import { WallMaterial } from '../../../../nhc/rendering/ir/fb/wall-material.js';


export class StrokeOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StrokeOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStrokeOp(bb:flatbuffers.ByteBuffer, obj?:StrokeOp):StrokeOp {
  return (obj || new StrokeOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStrokeOp(bb:flatbuffers.ByteBuffer, obj?:StrokeOp):StrokeOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StrokeOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

regionRef():string|null
regionRef(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
regionRef(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

outline(obj?:Outline):Outline|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Outline()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

wallMaterial(obj?:WallMaterial):WallMaterial|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new WallMaterial()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

cuts(index: number, obj?:Cut):Cut|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Cut()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

cutsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startStrokeOp(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addRegionRef(builder:flatbuffers.Builder, regionRefOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, regionRefOffset, 0);
}

static addOutline(builder:flatbuffers.Builder, outlineOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, outlineOffset, 0);
}

static addWallMaterial(builder:flatbuffers.Builder, wallMaterialOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, wallMaterialOffset, 0);
}

static addCuts(builder:flatbuffers.Builder, cutsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, cutsOffset, 0);
}

static createCutsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCutsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endStrokeOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
