// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum TerrainKind {
  None = 0,
  Water = 1,
  Lava = 2,
  Chasm = 3,
  Grass = 4
}
