// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TerrainKind } from '../../../../nhc/rendering/ir/fb/terrain-kind.js';


export class TerrainDetailTile {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TerrainDetailTile {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

x():number {
  return this.bb!.readInt32(this.bb_pos);
}

y():number {
  return this.bb!.readInt32(this.bb_pos + 4);
}

kind():TerrainKind {
  return this.bb!.readInt8(this.bb_pos + 8);
}

isCorridor():boolean {
  return !!this.bb!.readInt8(this.bb_pos + 9);
}

pad0():number {
  return this.bb!.readUint8(this.bb_pos + 10);
}

pad1():number {
  return this.bb!.readUint8(this.bb_pos + 11);
}

static sizeOf():number {
  return 12;
}

static createTerrainDetailTile(builder:flatbuffers.Builder, x: number, y: number, kind: TerrainKind, is_corridor: boolean, pad0: number, pad1: number):flatbuffers.Offset {
  builder.prep(4, 12);
  builder.writeInt8(pad1);
  builder.writeInt8(pad0);
  builder.writeInt8(Number(Boolean(is_corridor)));
  builder.writeInt8(kind);
  builder.writeInt32(y);
  builder.writeInt32(x);
  return builder.offset();
}

}
