// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum TileCorner {
  NW = 0,
  NE = 1,
  SE = 2,
  SW = 3
}
