// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { GrovePolygon } from '../../../../nhc/rendering/ir/fb/grove-polygon.js';
import { TileCoord } from '../../../../nhc/rendering/ir/fb/tile-coord.js';


export class TreeFeatureOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TreeFeatureOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTreeFeatureOp(bb:flatbuffers.ByteBuffer, obj?:TreeFeatureOp):TreeFeatureOp {
  return (obj || new TreeFeatureOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTreeFeatureOp(bb:flatbuffers.ByteBuffer, obj?:TreeFeatureOp):TreeFeatureOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TreeFeatureOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tiles(index: number, obj?:TileCoord):TileCoord|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TileCoord()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

tilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

seed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

theme():string|null
theme(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
theme(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

groves(index: number, obj?:GrovePolygon):GrovePolygon|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new GrovePolygon()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

grovesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

groups(index: number):string
groups(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
groups(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

groupsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

groveTiles(index: number, obj?:TileCoord):TileCoord|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new TileCoord()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

groveTilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

groveSizes(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

groveSizesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

groveSizesArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startTreeFeatureOp(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addTiles(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, tilesOffset, 0);
}

static startTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addSeed(builder:flatbuffers.Builder, seed:bigint) {
  builder.addFieldInt64(1, seed, BigInt('0'));
}

static addTheme(builder:flatbuffers.Builder, themeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, themeOffset, 0);
}

static addGroves(builder:flatbuffers.Builder, grovesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, grovesOffset, 0);
}

static createGrovesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startGrovesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addGroups(builder:flatbuffers.Builder, groupsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, groupsOffset, 0);
}

static createGroupsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startGroupsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addGroveTiles(builder:flatbuffers.Builder, groveTilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, groveTilesOffset, 0);
}

static startGroveTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addGroveSizes(builder:flatbuffers.Builder, groveSizesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, groveSizesOffset, 0);
}

static createGroveSizesVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createGroveSizesVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createGroveSizesVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startGroveSizesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endTreeFeatureOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTreeFeatureOp(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset, seed:bigint, themeOffset:flatbuffers.Offset, grovesOffset:flatbuffers.Offset, groupsOffset:flatbuffers.Offset, groveTilesOffset:flatbuffers.Offset, groveSizesOffset:flatbuffers.Offset):flatbuffers.Offset {
  TreeFeatureOp.startTreeFeatureOp(builder);
  TreeFeatureOp.addTiles(builder, tilesOffset);
  TreeFeatureOp.addSeed(builder, seed);
  TreeFeatureOp.addTheme(builder, themeOffset);
  TreeFeatureOp.addGroves(builder, grovesOffset);
  TreeFeatureOp.addGroups(builder, groupsOffset);
  TreeFeatureOp.addGroveTiles(builder, groveTilesOffset);
  TreeFeatureOp.addGroveSizes(builder, groveSizesOffset);
  return TreeFeatureOp.endTreeFeatureOp(builder);
}
}
