// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class V5Anchor {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):V5Anchor {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

x():number {
  return this.bb!.readInt32(this.bb_pos);
}

y():number {
  return this.bb!.readInt32(this.bb_pos + 4);
}

variant():number {
  return this.bb!.readUint8(this.bb_pos + 8);
}

orientation():number {
  return this.bb!.readUint8(this.bb_pos + 9);
}

scale():number {
  return this.bb!.readUint8(this.bb_pos + 10);
}

pad0():number {
  return this.bb!.readUint8(this.bb_pos + 11);
}

groupId():number {
  return this.bb!.readUint32(this.bb_pos + 12);
}

static sizeOf():number {
  return 16;
}

static createV5Anchor(builder:flatbuffers.Builder, x: number, y: number, variant: number, orientation: number, scale: number, pad0: number, group_id: number):flatbuffers.Offset {
  builder.prep(4, 16);
  builder.writeInt32(group_id);
  builder.writeInt8(pad0);
  builder.writeInt8(scale);
  builder.writeInt8(orientation);
  builder.writeInt8(variant);
  builder.writeInt32(y);
  builder.writeInt32(x);
  return builder.offset();
}

}
