// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { V5Anchor } from '../../../../nhc/rendering/ir/fb/v5-anchor.js';
import { V5FixtureKind } from '../../../../nhc/rendering/ir/fb/v5-fixture-kind.js';


export class V5FixtureOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):V5FixtureOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsV5FixtureOp(bb:flatbuffers.ByteBuffer, obj?:V5FixtureOp):V5FixtureOp {
  return (obj || new V5FixtureOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsV5FixtureOp(bb:flatbuffers.ByteBuffer, obj?:V5FixtureOp):V5FixtureOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new V5FixtureOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

regionRef():string|null
regionRef(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
regionRef(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

kind():V5FixtureKind {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : V5FixtureKind.Web;
}

anchors(index: number, obj?:V5Anchor):V5Anchor|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new V5Anchor()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 16, this.bb!) : null;
}

anchorsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

seed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startV5FixtureOp(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addRegionRef(builder:flatbuffers.Builder, regionRefOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, regionRefOffset, 0);
}

static addKind(builder:flatbuffers.Builder, kind:V5FixtureKind) {
  builder.addFieldInt8(1, kind, V5FixtureKind.Web);
}

static addAnchors(builder:flatbuffers.Builder, anchorsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, anchorsOffset, 0);
}

static startAnchorsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(16, numElems, 4);
}

static addSeed(builder:flatbuffers.Builder, seed:bigint) {
  builder.addFieldInt64(3, seed, BigInt('0'));
}

static endV5FixtureOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createV5FixtureOp(builder:flatbuffers.Builder, regionRefOffset:flatbuffers.Offset, kind:V5FixtureKind, anchorsOffset:flatbuffers.Offset, seed:bigint):flatbuffers.Offset {
  V5FixtureOp.startV5FixtureOp(builder);
  V5FixtureOp.addRegionRef(builder, regionRefOffset);
  V5FixtureOp.addKind(builder, kind);
  V5FixtureOp.addAnchors(builder, anchorsOffset);
  V5FixtureOp.addSeed(builder, seed);
  return V5FixtureOp.endV5FixtureOp(builder);
}
}
