// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum V5FixtureKind {
  Web = 0,
  Skull = 1,
  Bone = 2,
  LooseStone = 3,
  Tree = 4,
  Bush = 5,
  Well = 6,
  Fountain = 7,
  Stair = 8,
  Gravestone = 9,
  Sign = 10,
  Mushroom = 11
}
