// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ShadowOp } from '../../../../nhc/rendering/ir/fb/shadow-op.js';
import { V5FixtureOp } from '../../../../nhc/rendering/ir/fb/v5-fixture-op.js';
import { V5HatchOp } from '../../../../nhc/rendering/ir/fb/v5-hatch-op.js';
import { V5PaintOp } from '../../../../nhc/rendering/ir/fb/v5-paint-op.js';
import { V5PathOp } from '../../../../nhc/rendering/ir/fb/v5-path-op.js';
import { V5RoofOp } from '../../../../nhc/rendering/ir/fb/v5-roof-op.js';
import { V5StampOp } from '../../../../nhc/rendering/ir/fb/v5-stamp-op.js';
import { V5StrokeOp } from '../../../../nhc/rendering/ir/fb/v5-stroke-op.js';


export enum V5Op {
  NONE = 0,
  V5PaintOp = 1,
  V5StampOp = 2,
  V5PathOp = 3,
  V5FixtureOp = 4,
  V5StrokeOp = 5,
  ShadowOp = 6,
  V5HatchOp = 7,
  V5RoofOp = 8
}

export function unionToV5Op(
  type: V5Op,
  accessor: (obj:ShadowOp|V5FixtureOp|V5HatchOp|V5PaintOp|V5PathOp|V5RoofOp|V5StampOp|V5StrokeOp) => ShadowOp|V5FixtureOp|V5HatchOp|V5PaintOp|V5PathOp|V5RoofOp|V5StampOp|V5StrokeOp|null
): ShadowOp|V5FixtureOp|V5HatchOp|V5PaintOp|V5PathOp|V5RoofOp|V5StampOp|V5StrokeOp|null {
  switch(V5Op[type]) {
    case 'NONE': return null; 
    case 'V5PaintOp': return accessor(new V5PaintOp())! as V5PaintOp;
    case 'V5StampOp': return accessor(new V5StampOp())! as V5StampOp;
    case 'V5PathOp': return accessor(new V5PathOp())! as V5PathOp;
    case 'V5FixtureOp': return accessor(new V5FixtureOp())! as V5FixtureOp;
    case 'V5StrokeOp': return accessor(new V5StrokeOp())! as V5StrokeOp;
    case 'ShadowOp': return accessor(new ShadowOp())! as ShadowOp;
    case 'V5HatchOp': return accessor(new V5HatchOp())! as V5HatchOp;
    case 'V5RoofOp': return accessor(new V5RoofOp())! as V5RoofOp;
    default: return null;
  }
}

export function unionListToV5Op(
  type: V5Op, 
  accessor: (index: number, obj:ShadowOp|V5FixtureOp|V5HatchOp|V5PaintOp|V5PathOp|V5RoofOp|V5StampOp|V5StrokeOp) => ShadowOp|V5FixtureOp|V5HatchOp|V5PaintOp|V5PathOp|V5RoofOp|V5StampOp|V5StrokeOp|null, 
  index: number
): ShadowOp|V5FixtureOp|V5HatchOp|V5PaintOp|V5PathOp|V5RoofOp|V5StampOp|V5StrokeOp|null {
  switch(V5Op[type]) {
    case 'NONE': return null; 
    case 'V5PaintOp': return accessor(index, new V5PaintOp())! as V5PaintOp;
    case 'V5StampOp': return accessor(index, new V5StampOp())! as V5StampOp;
    case 'V5PathOp': return accessor(index, new V5PathOp())! as V5PathOp;
    case 'V5FixtureOp': return accessor(index, new V5FixtureOp())! as V5FixtureOp;
    case 'V5StrokeOp': return accessor(index, new V5StrokeOp())! as V5StrokeOp;
    case 'ShadowOp': return accessor(index, new ShadowOp())! as ShadowOp;
    case 'V5HatchOp': return accessor(index, new V5HatchOp())! as V5HatchOp;
    case 'V5RoofOp': return accessor(index, new V5RoofOp())! as V5RoofOp;
    default: return null;
  }
}
