// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { V5Op, unionToV5Op, unionListToV5Op } from '../../../../nhc/rendering/ir/fb/v5-op.js';


export class V5OpEntry {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):V5OpEntry {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsV5OpEntry(bb:flatbuffers.ByteBuffer, obj?:V5OpEntry):V5OpEntry {
  return (obj || new V5OpEntry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsV5OpEntry(bb:flatbuffers.ByteBuffer, obj?:V5OpEntry):V5OpEntry {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new V5OpEntry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

opType():V5Op {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : V5Op.NONE;
}

op<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startV5OpEntry(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addOpType(builder:flatbuffers.Builder, opType:V5Op) {
  builder.addFieldInt8(0, opType, V5Op.NONE);
}

static addOp(builder:flatbuffers.Builder, opOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, opOffset, 0);
}

static endV5OpEntry(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createV5OpEntry(builder:flatbuffers.Builder, opType:V5Op, opOffset:flatbuffers.Offset):flatbuffers.Offset {
  V5OpEntry.startV5OpEntry(builder);
  V5OpEntry.addOpType(builder, opType);
  V5OpEntry.addOp(builder, opOffset);
  return V5OpEntry.endV5OpEntry(builder);
}
}
