// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { V5Material } from '../../../../nhc/rendering/ir/fb/v5-material.js';


export class V5PaintOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):V5PaintOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsV5PaintOp(bb:flatbuffers.ByteBuffer, obj?:V5PaintOp):V5PaintOp {
  return (obj || new V5PaintOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsV5PaintOp(bb:flatbuffers.ByteBuffer, obj?:V5PaintOp):V5PaintOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new V5PaintOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

regionRef():string|null
regionRef(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
regionRef(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

subtractRegionRefs(index: number):string
subtractRegionRefs(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
subtractRegionRefs(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

subtractRegionRefsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

material(obj?:V5Material):V5Material|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new V5Material()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startV5PaintOp(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addRegionRef(builder:flatbuffers.Builder, regionRefOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, regionRefOffset, 0);
}

static addSubtractRegionRefs(builder:flatbuffers.Builder, subtractRegionRefsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, subtractRegionRefsOffset, 0);
}

static createSubtractRegionRefsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSubtractRegionRefsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addMaterial(builder:flatbuffers.Builder, materialOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, materialOffset, 0);
}

static endV5PaintOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
