// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CornerStyle } from '../../../../nhc/rendering/ir/fb/corner-style.js';
import { V5MaterialFamily } from '../../../../nhc/rendering/ir/fb/v5-material-family.js';
import { V5WallTreatment } from '../../../../nhc/rendering/ir/fb/v5-wall-treatment.js';


export class V5WallMaterial {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):V5WallMaterial {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsV5WallMaterial(bb:flatbuffers.ByteBuffer, obj?:V5WallMaterial):V5WallMaterial {
  return (obj || new V5WallMaterial()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsV5WallMaterial(bb:flatbuffers.ByteBuffer, obj?:V5WallMaterial):V5WallMaterial {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new V5WallMaterial()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

family():V5MaterialFamily {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : V5MaterialFamily.Plain;
}

style():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

treatment():V5WallTreatment {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : V5WallTreatment.PlainStroke;
}

cornerStyle():CornerStyle {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : CornerStyle.Merlon;
}

tone():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

seed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startV5WallMaterial(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addFamily(builder:flatbuffers.Builder, family:V5MaterialFamily) {
  builder.addFieldInt8(0, family, V5MaterialFamily.Plain);
}

static addStyle(builder:flatbuffers.Builder, style:number) {
  builder.addFieldInt8(1, style, 0);
}

static addTreatment(builder:flatbuffers.Builder, treatment:V5WallTreatment) {
  builder.addFieldInt8(2, treatment, V5WallTreatment.PlainStroke);
}

static addCornerStyle(builder:flatbuffers.Builder, cornerStyle:CornerStyle) {
  builder.addFieldInt8(3, cornerStyle, CornerStyle.Merlon);
}

static addTone(builder:flatbuffers.Builder, tone:number) {
  builder.addFieldInt8(4, tone, 0);
}

static addSeed(builder:flatbuffers.Builder, seed:bigint) {
  builder.addFieldInt64(5, seed, BigInt('0'));
}

static endV5WallMaterial(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createV5WallMaterial(builder:flatbuffers.Builder, family:V5MaterialFamily, style:number, treatment:V5WallTreatment, cornerStyle:CornerStyle, tone:number, seed:bigint):flatbuffers.Offset {
  V5WallMaterial.startV5WallMaterial(builder);
  V5WallMaterial.addFamily(builder, family);
  V5WallMaterial.addStyle(builder, style);
  V5WallMaterial.addTreatment(builder, treatment);
  V5WallMaterial.addCornerStyle(builder, cornerStyle);
  V5WallMaterial.addTone(builder, tone);
  V5WallMaterial.addSeed(builder, seed);
  return V5WallMaterial.endV5WallMaterial(builder);
}
}
