// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RectRoom } from '../../../../nhc/rendering/ir/fb/rect-room.js';
import { TileCoord } from '../../../../nhc/rendering/ir/fb/tile-coord.js';


export class WallsAndFloorsOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WallsAndFloorsOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWallsAndFloorsOp(bb:flatbuffers.ByteBuffer, obj?:WallsAndFloorsOp):WallsAndFloorsOp {
  return (obj || new WallsAndFloorsOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWallsAndFloorsOp(bb:flatbuffers.ByteBuffer, obj?:WallsAndFloorsOp):WallsAndFloorsOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WallsAndFloorsOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

smoothRoomRegions(index: number):string
smoothRoomRegions(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
smoothRoomRegions(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

smoothRoomRegionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

rectRooms(index: number, obj?:RectRoom):RectRoom|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new RectRoom()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

rectRoomsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

corridorTiles(index: number, obj?:TileCoord):TileCoord|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new TileCoord()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

corridorTilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

caveRegion():string|null
caveRegion(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
caveRegion(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

wallSegments(index: number):string
wallSegments(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
wallSegments(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

wallSegmentsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

floorColor():string|null
floorColor(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
floorColor(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

caveFloorColor():string|null
caveFloorColor(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
caveFloorColor(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

wallColor():string|null
wallColor(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
wallColor(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

wallWidth():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

buildingFootprint(index: number, obj?:TileCoord):TileCoord|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new TileCoord()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

buildingFootprintLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startWallsAndFloorsOp(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addSmoothRoomRegions(builder:flatbuffers.Builder, smoothRoomRegionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, smoothRoomRegionsOffset, 0);
}

static createSmoothRoomRegionsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSmoothRoomRegionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRectRooms(builder:flatbuffers.Builder, rectRoomsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, rectRoomsOffset, 0);
}

static createRectRoomsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRectRoomsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addCorridorTiles(builder:flatbuffers.Builder, corridorTilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, corridorTilesOffset, 0);
}

static startCorridorTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addCaveRegion(builder:flatbuffers.Builder, caveRegionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, caveRegionOffset, 0);
}

static addWallSegments(builder:flatbuffers.Builder, wallSegmentsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, wallSegmentsOffset, 0);
}

static createWallSegmentsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startWallSegmentsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addFloorColor(builder:flatbuffers.Builder, floorColorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, floorColorOffset, 0);
}

static addCaveFloorColor(builder:flatbuffers.Builder, caveFloorColorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, caveFloorColorOffset, 0);
}

static addWallColor(builder:flatbuffers.Builder, wallColorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, wallColorOffset, 0);
}

static addWallWidth(builder:flatbuffers.Builder, wallWidth:number) {
  builder.addFieldFloat32(8, wallWidth, 1.0);
}

static addBuildingFootprint(builder:flatbuffers.Builder, buildingFootprintOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, buildingFootprintOffset, 0);
}

static startBuildingFootprintVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static endWallsAndFloorsOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWallsAndFloorsOp(builder:flatbuffers.Builder, smoothRoomRegionsOffset:flatbuffers.Offset, rectRoomsOffset:flatbuffers.Offset, corridorTilesOffset:flatbuffers.Offset, caveRegionOffset:flatbuffers.Offset, wallSegmentsOffset:flatbuffers.Offset, floorColorOffset:flatbuffers.Offset, caveFloorColorOffset:flatbuffers.Offset, wallColorOffset:flatbuffers.Offset, wallWidth:number, buildingFootprintOffset:flatbuffers.Offset):flatbuffers.Offset {
  WallsAndFloorsOp.startWallsAndFloorsOp(builder);
  WallsAndFloorsOp.addSmoothRoomRegions(builder, smoothRoomRegionsOffset);
  WallsAndFloorsOp.addRectRooms(builder, rectRoomsOffset);
  WallsAndFloorsOp.addCorridorTiles(builder, corridorTilesOffset);
  WallsAndFloorsOp.addCaveRegion(builder, caveRegionOffset);
  WallsAndFloorsOp.addWallSegments(builder, wallSegmentsOffset);
  WallsAndFloorsOp.addFloorColor(builder, floorColorOffset);
  WallsAndFloorsOp.addCaveFloorColor(builder, caveFloorColorOffset);
  WallsAndFloorsOp.addWallColor(builder, wallColorOffset);
  WallsAndFloorsOp.addWallWidth(builder, wallWidth);
  WallsAndFloorsOp.addBuildingFootprint(builder, buildingFootprintOffset);
  return WallsAndFloorsOp.endWallsAndFloorsOp(builder);
}
}
