// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CornerStyle } from '../../../../nhc/rendering/ir/fb/corner-style.js';
import { MaterialFamily } from '../../../../nhc/rendering/ir/fb/material-family.js';
import { WallTreatment } from '../../../../nhc/rendering/ir/fb/wall-treatment.js';


export class WallMaterial {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WallMaterial {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWallMaterial(bb:flatbuffers.ByteBuffer, obj?:WallMaterial):WallMaterial {
  return (obj || new WallMaterial()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWallMaterial(bb:flatbuffers.ByteBuffer, obj?:WallMaterial):WallMaterial {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WallMaterial()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

family():MaterialFamily {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MaterialFamily.Plain;
}

style():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

treatment():WallTreatment {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : WallTreatment.PlainStroke;
}

cornerStyle():CornerStyle {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : CornerStyle.Merlon;
}

tone():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

seed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startWallMaterial(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addFamily(builder:flatbuffers.Builder, family:MaterialFamily) {
  builder.addFieldInt8(0, family, MaterialFamily.Plain);
}

static addStyle(builder:flatbuffers.Builder, style:number) {
  builder.addFieldInt8(1, style, 0);
}

static addTreatment(builder:flatbuffers.Builder, treatment:WallTreatment) {
  builder.addFieldInt8(2, treatment, WallTreatment.PlainStroke);
}

static addCornerStyle(builder:flatbuffers.Builder, cornerStyle:CornerStyle) {
  builder.addFieldInt8(3, cornerStyle, CornerStyle.Merlon);
}

static addTone(builder:flatbuffers.Builder, tone:number) {
  builder.addFieldInt8(4, tone, 0);
}

static addSeed(builder:flatbuffers.Builder, seed:bigint) {
  builder.addFieldInt64(5, seed, BigInt('0'));
}

static endWallMaterial(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWallMaterial(builder:flatbuffers.Builder, family:MaterialFamily, style:number, treatment:WallTreatment, cornerStyle:CornerStyle, tone:number, seed:bigint):flatbuffers.Offset {
  WallMaterial.startWallMaterial(builder);
  WallMaterial.addFamily(builder, family);
  WallMaterial.addStyle(builder, style);
  WallMaterial.addTreatment(builder, treatment);
  WallMaterial.addCornerStyle(builder, cornerStyle);
  WallMaterial.addTone(builder, tone);
  WallMaterial.addSeed(builder, seed);
  return WallMaterial.endWallMaterial(builder);
}
}
