// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TileCoord } from '../../../../nhc/rendering/ir/fb/tile-coord.js';
import { Vec2 } from '../../../../nhc/rendering/ir/fb/vec2.js';


export class WoodFloorOp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WoodFloorOp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWoodFloorOp(bb:flatbuffers.ByteBuffer, obj?:WoodFloorOp):WoodFloorOp {
  return (obj || new WoodFloorOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWoodFloorOp(bb:flatbuffers.ByteBuffer, obj?:WoodFloorOp):WoodFloorOp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WoodFloorOp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

tiles(index: number, obj?:TileCoord):TileCoord|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TileCoord()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

tilesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

seed():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

theme():string|null
theme(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
theme(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

buildingPolygon(index: number, obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Vec2()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

buildingPolygonLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startWoodFloorOp(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addTiles(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, tilesOffset, 0);
}

static startTilesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addSeed(builder:flatbuffers.Builder, seed:bigint) {
  builder.addFieldInt64(1, seed, BigInt('0'));
}

static addTheme(builder:flatbuffers.Builder, themeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, themeOffset, 0);
}

static addBuildingPolygon(builder:flatbuffers.Builder, buildingPolygonOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, buildingPolygonOffset, 0);
}

static startBuildingPolygonVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static endWoodFloorOp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWoodFloorOp(builder:flatbuffers.Builder, tilesOffset:flatbuffers.Offset, seed:bigint, themeOffset:flatbuffers.Offset, buildingPolygonOffset:flatbuffers.Offset):flatbuffers.Offset {
  WoodFloorOp.startWoodFloorOp(builder);
  WoodFloorOp.addTiles(builder, tilesOffset);
  WoodFloorOp.addSeed(builder, seed);
  WoodFloorOp.addTheme(builder, themeOffset);
  WoodFloorOp.addBuildingPolygon(builder, buildingPolygonOffset);
  return WoodFloorOp.endWoodFloorOp(builder);
}
}
